### ISSUE TITLE
Command line option for Visual Studio version

### ISSUE THREAD

**Issue by tritao** [mono/Embeddinator-4000#11]
As the title says, add a `--vs` CLI option to set the wanted VS version for compilation.

**Comment by MihaMarkic** [comment]
I can take this

**Comment by MihaMarkic** [comment]
Shall we have a finished set of option (like 14.0, 13.0, 12.0 and latest <- default)?

**Comment by tritao** [comment]
I was thinking keying it on VS version (and not the compiler version) as that's how I've historically handled it. so something like `--vs=2015`.

**Comment by tritao** [comment]
Fixed by https://github.com/mono/Embeddinator-4000/commit/e12ece26843579feeeba83b739c7bf69455f9bfe.
