### ISSUE TITLE
[objc][ios] One framework with both simulator and device support, or one framework for simulator and one for device?

### ISSUE THREAD

**Issue by rolfbjarne** [mono/Embeddinator-4000#113]
One framework with both simulator and device is:

* Much easier to consume. Xcode does not make it easy to build with different frameworks (at least I haven't found a way).
* Bigger. We can't strip IL. We might have to disable other linker optimizations that make assemblies non-architecture-agnostic.

We can also build both, and let the user decide.

**Comment by dalexsoto** [comment]
My take is for one big and fat Framework 🍭 

Why? because from my previous experience working on the components team this is what Objective-C developers are used to, most of the projects we bound that distributed binaries were fat binaries and fake frameworks (static binaries disguised as .framework) that also contained sim and device archs.

By having a fat framework it will be a lot easier to just point and consume from Xcode

**Comment by rolfbjarne** [comment]
Maybe we can ship a framework-slimificator that IL strips assemblies on the build machine for device builds.

**Comment by dalexsoto** [comment]
> framework-slimificator

You forgot the 5000 suffix ;)

**Comment by spouliot** [comment]
*Full AOT* is only available for iOS (and tvOS / watchOS). Ideally the tool usage would be (at least by default) identical for all platforms.

Still shipping IL can be a problem in two cases:

1. It has a non-trivial impact on the application size

**Workaround:** We could provide instructions to strip the assemblies from Xcode (as an additional build step).

2. Intellectual Property: if the tool is used to publish a library then people must be aware IL needs to be shipped to support simulator builds.

This will need to be described inside the documentation.

**Comment by rolfbjarne** [comment]
I decided with the greedy approach: do every option.

We'll create one framework for the simulator, one framework for device, one merged framework, and a shell script to thin the merged framework.

**Comment by rolfbjarne** [comment]
This was implemented in PR #149.
