### ISSUE TITLE
[objc] Map `GetHashCode` and `Equals` to `NSObject` protocol `hash` and `isEqual:`

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#123]
The semantics are identical.

`@property(readonly) NSUInteger hash;`

* `hash` returns an `NSUInteger` so it differs in 32/64 bits, while .NET always return a 32bits integer;

https://developer.apple.com/reference/objectivec/1418956-nsobject/1418859-hash?language=objc

`- (BOOL)isEqual:(id)object;`

* a non-bound `NSObject` (i.e. does not have a managed peer) must not be sent to the mono runtime.

https://developer.apple.com/reference/objectivec/1418956-nsobject/1418795-isequal?language=objc

**Comment by spouliot** [comment]
That would remove warnings like:

> warning EM1031: Method `Boolean Equals(System.Object)` is not generated because of parameter type `System.Object` is not supported.

**Comment by timrisi** [comment]
I'll look into this one

**Comment by timrisi** [comment]
https://github.com/mono/Embeddinator-4000/pull/159

**Comment by timrisi** [comment]
Merged
