### ISSUE TITLE
Gitter Chat for easier following workflow and discussions

### ISSUE THREAD

**Issue by realvictorprm** [mono/Embeddinator-4000#16]
Hello Joao,

I would like to see a gitter chat for this. 
Simply because I'm having questions,  want to talk about it etc. but with having the community involved too. Would be nice if you add it ;)

PS:
Of course, something different would be fine too. It's just about talking with devs easier about this library with informing the community too.

**Comment by tritao** [comment]
Sounds good.

**Comment by tritao** [comment]
Done: https://gitter.im/managed-interop
