### ISSUE TITLE
[objc] Better operator support

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#183]
Libraries that wants to be CLS compliant are likely to provide friendly-named methods [1] that match the  (non-CLS compliant) operator overloads.

That means:

1. we should emit ObjC code using the friendly names (consistency);

2. if both the operator and the friendly name are present (in .net) then only one should be generated in ObjC (since they _should_ be duplicate);

[1] https://msdn.microsoft.com/en-us/library/ms229032(v=vs.110).aspx

**Comment by chamons** [comment]
https://github.com/mono/Embeddinator-4000/pull/190 landed
