### ISSUE TITLE
[objc] Array <-> NSArray support 

### ISSUE THREAD

**Issue by dalexsoto** [mono/Embeddinator-4000#189]
- `byte []` <-> `NSData`
- `string []` <-> `NSArray<NSString>`
- `Foo []` <-> `NSArray<NSFoo>`

**Comment by spouliot** [comment]
There's also the, less common, `System.ArrayList` [1] that _could_ map to non-generic `NSArray`.

However it's not clear if it's worth doing, e.g.  it could be very costly to copy elements and the untyped object types might not have any useful representation in ObjC.

It's worth a comment (in the source) but it's not to be covered by a PR to fix this.

[1] https://msdn.microsoft.com/en-us/library/system.collections.arraylist(v=VS.100).aspx

**Comment by rolfbjarne** [comment]
I wonder if we can create our own NSData/NSArray subclasses that contains a reference to the managed object, and only fetches data/items when requested.

This would be much faster, and it would also mean writes on one side would be visible on the other, since the backing store is the same.

**Comment by spouliot** [comment]
@rolfbjarne that's a very interesting idea :) but we would still need to support the original case

`public byte[] Hash (byte[] input) {...}`

We can control the output to be our special (public or not) subclass of `NSData` (e.g. `NETData`) but we should not force people to use it for `input`.

**Comment by spouliot** [comment]
Note that both `NSArray` and `NSData` [1] are class clusters [2]. Not the funniest types to subclass correctly :(

[1] https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/ClassCluster.html#//apple_ref/doc/uid/TP40008195-CH7-SW1
[2] http://stackoverflow.com/a/5772610/220643

**Comment by spouliot** [comment]
According to [1] _NSData’s primitive methods are -length and -bytes_ - which seems odd compared to the amount of issues people have trying (but they could be due to other difference).

[1] http://www.cimgf.com/2012/02/17/extending-nsdata-and-not-overriding-dealloc/

**Comment by spouliot** [comment]
PR #252 was merged
