### ISSUE TITLE
[general] Support for VS 2017

### ISSUE THREAD

**Issue by realvictorprm** [mono/Embeddinator-4000#19]
Currently embeddinator does not support the usage of VS 2017 which is included in the newest CppSharp version. There are some bugs I'll list here which have to be fixed.

- [ ] fix compilation option for VS 2017
- [x] fix build script for generating VS 2017 solutions (I'll make a PR as soon as possible)
Further bugs can appear. Stand by.

The compilation for VS2017 fails due to that the path of _cl.exe_ is wrong.
For getting the correct one a additional dependency (which is already included in the newest CppSharp version) is needed. Whether we should use it must be discussed. What do you think @tritao ?

**Comment by michalkovy** [comment]
Compilation also can fail earlier when you choose VS2017 in parameter, it fails in Embeddinator-4000\binder\Compilation.cs on line 721 when you have multiple instances of Visual Studio 2017 (e.g. I have Enterprise and Enterprise Preview but you can have even different editions on the same computer)

**Comment by realvictorprm** [comment]
We actually had great progress towards VS 2017 compatibility.

**Comment by realvictorprm** [comment]
But solving VS 2017 compatibility is my keyword, I already handled this for CppSharp @michalkovy 😄

**Comment by tritao** [comment]
Think this one is solved now
