### ISSUE TITLE
[objc] Use word "Value" in method's names after a type

### ISSUE THREAD

**Issue by VincentDondain** [mono/Embeddinator-4000#194]
Following https://github.com/mono/Embeddinator-4000/issues/193 it's pretty common/convention in ObjC to say `Value` after a type if it's what you **have to** use in your method's name.

So https://github.com/mono/Embeddinator-4000/blob/objc/tests/managed/methods.cs#L93-L94 for instance should become:

```
- (int)doItWithInt32Value:(int) i;
- (int)doItWithStringValue:(NSString *) s;
```

**Comment by spouliot** [comment]
Q: When does it make sense ? and when does it not ?

E.g. why not for the `NSString` overload ?

IMO `doItWithNSStringValue` would be quite bad, i.e. the `NS` should not be there

but `doItWithStringValue` ? there's quite a few Apple API with similar signature

Still I prefer `doItWithString` - and there's also many similar signature (without `Value`) in Apple's API

**Comment by VincentDondain** [comment]
We would do it for the `NSString` overload, I fixed the description, was a typo sorry.

**Comment by VincentDondain** [comment]
The rule would be to use `Value` when we're using the type's name as method name. If we're using the argument's name we don't need to add `Value`.

**Comment by VincentDondain** [comment]
You're not using type's names in ObjC methods very often (when you're not generating code :P) and I believe that when you do see a type name in the method's name you expect to see `Value` next to it.

You can disagree with me and close this issue though, I'm just reading the naming methods document but if Apple also break that rule most of the time... (:

**Comment by spouliot** [comment]
No disagreement just trying to extract rules that we can codify :-)

> was a typo sorry.

It's an interesting typo because it (a) looks nice and (b) commonly used by Apple. I mainly saw it because it was near another (non string) case, otherwise I think I would have fell under my radar.

Anyway it applies mostly (but not uniquely) to `NSString` and it's simpler (and consistent, easier when generating code) to have a single rule.

> You're not using type's names in ObjC methods very often

Yeah, we work with what we have :) Right now priority is given to parameter names but those can produce duplicates and type names guarantee an unique signature in .NET.

`bool Compare (int value);` and
`bool Compare (string value);`

**Comment by VincentDondain** [comment]
@spouliot I believe we could use the same input types as https://github.com/mono/Embeddinator-4000/blob/objc/objcgen/NameGenerator.cs#L10-L31 (used for https://github.com/mono/Embeddinator-4000/issues/195).

We'd have some mapping like this:

```
{ "int", "IntValue" },
{ "unsigned int", "UIntValue" },
{ "double", "DoubleValue" },
{ "float", "FloatValue" },
{ "NSString *", "StringValue" },
{ "NSObject", "ObjectValue" },
{ "NSPoint", "PointValue" },
{ "NSRect", "RectValue" },
{ "NSFont", "FontValue" },
{ "SEL", "SelectorValue" },
{ "short", "ShortValue" },
{ "unsigned short", "UShortValue" },
{ "long long", "LongValue" },
{ "unsigned long long", "ULongValue" },
{ "bool", "BoolValue" },
{ "char", "CharValue" },
{ "unsigned char", "UCharValue" },
{ "signed char", "SCharValue" }
```

You asked "where it helps and if/where it does not", the answer is it helps with at least the types above.  
I also think we'll have to handle this **case by case** given that it does not make sense to _just_ append the word "Value" to the type, it needs some polish.

**Comment by spouliot** [comment]
make sense, that's a good starting point :)

**Comment by VincentDondain** [comment]
Closing since https://github.com/mono/Embeddinator-4000/pull/315 has been merged.
