### ISSUE TITLE
[objc] "Avoid one- and two-letter names for arguments" rule

### ISSUE THREAD

**Issue by VincentDondain** [mono/Embeddinator-4000#195]
Rule from [Apple](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF) under "Method Arguments".

If we take this C# code for instance: https://github.com/mono/Embeddinator-4000/blob/objc/tests/managed/methods.cs#L93-L94 (and once https://github.com/mono/Embeddinator-4000/issues/193 and  https://github.com/mono/Embeddinator-4000/issues/194 are fixed :P) we should get:

```
- (int)doItWithInt32Value:(int) anInt;
- (int)doItWithStringValue:(NSString *) aString;
```

**Comment by spouliot** [comment]
In general it will be GIGO (garbage-in, garbage-out) so good .NET code will lead to good parameter names. However we could fallback to the provided list [1] while taking care not to create duplicates, i.e. `(int i, int j)` cannot become `(int) anInt ... (int) anInt`

[1] https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-1001865-BCIBJEFG

**Comment by VincentDondain** [comment]
Lol I was about to comment about the possible duplication issue.

We could go `anIntI` and `anIntJ` in case of duplication but at least we respect the guidelines.

**Comment by timrisi** [comment]
How deep do we want to go on this?  It's pretty easy to set it up simply based on the parameter types (anIntI, aStringB, anObjectX, etc).  Do we want to try to parse keywords as well (atIndex vs intValue vs length for instnace to get index, anInt, numBytes as the parameters)

**Comment by spouliot** [comment]
Not sure I get the last phrase ?!? example ?

**Comment by timrisi** [comment]
From the samples apple listed:
```...alignment:(int)mode
...atIndex:(int)index
...intValue:(int)anInt
...length:(int)numBytes
...tag:(int)anInt```

An int parameter might has 5 different possible argument names from that list.  it's easy to set up to just do,
int -> anInt
double -> aDouble
etc, but do we alsow ant to look at the keywords (atIndex, intValue, length, etc) and try to parse further from there, or just do it based on the parameter type (int, double, float, etc)

**Comment by timrisi** [comment]
https://gist.github.com/timrisi/a893226b357eaad2c4e6eef0ada74649 is my current diff.

Right now I just have a dictionary of Type -> argumentName, without using any of the other keywords, then it appends the original argument name to avoid conflicts, so:
```
int x
```
becomes
```
int anIntX
```

**Comment by spouliot** [comment]
oh I see now :-)

I think `int x` should become `(int)anInt` if it's the lone `int` parameter that needs to be modified.

If there's more than one then the original, short name, can be applied, e.g.
`int x, int y, int z, int theFourthDimension` 

would become:
`(int)anIntX (int)anIntY (int)anIntZ (int) theFourthDimension`

@VincentDondain thoughts ?

**Comment by timrisi** [comment]
Also doable, just requires a bit more work to parse all of the arguments to see if it's a lone short parameter or not

**Comment by VincentDondain** [comment]
@spouliot no more thoughts, you described it perfectly (:

**Comment by spouliot** [comment]
PR #215 was merged
