### ISSUE TITLE
[objc] No space between type declaration and argument

### ISSUE THREAD

**Issue by VincentDondain** [mono/Embeddinator-4000#196]
The usual convention in ObjC is to not put spaces between the type declaration and the argument name.

Check all the methods in [this doc](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF) for instance.

So if I take the piece of code I've been referring to in the 4 previous issues again (poor piece of code): https://github.com/mono/Embeddinator-4000/blob/objc/tests/managed/methods.cs#L93-L94

It should output:

```
- (int)doItWithInt32Value:(int)anInt;
- (int)doItWithStringValue:(NSString *)aString;
```

_Note: There is a space before the next piece of method name which is before the next argument._

**Comment by spouliot** [comment]
You mean

* `(int)anInt;` (good) and
* `(int) anInt`; (bad)

right ?

That should be an easy fix :)

**Comment by VincentDondain** [comment]
@spouliot yup that's what I mean (:

**Comment by timrisi** [comment]
I'll fix this alongside the 1-2 letter arguments since it's in the same code

**Comment by spouliot** [comment]
@timrisi looks like @VincentDondain got to it earlier with PR #205 :)
