### ISSUE TITLE
Only support frameworks (not static/dynamic libraries) when embedding XI/XM.

### ISSUE THREAD

**Issue by rolfbjarne** [mono/Embeddinator-4000#197]
I think we should only support creating frameworks when embedding XI/XM (no static libraries (.a) nor dynamic libraries (.dylib)), since it becomes cumbersome to use (the library consumer would have to keep track of the assemblies as well, and any other related files we may have now or in the future).

**Comment by spouliot** [comment]
I like that, frameworks are the future anyway :)

It does require to have XM (mmp) supports (producing) them (c.c. @chamons).

The other options could be deprecated (not shown by default) and community supported (if there's any interest in them).

**Comment by chamons** [comment]
I'm happy to bite off that mmp work, but i'm not sure what it'd entail.

Can someone point me to the equivalent mtouch code?

**Comment by rolfbjarne** [comment]
I've mostly done this for mmp already (locally).
