### ISSUE TITLE
Operator and "friendly" methods should generate same name

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#204]
This PR adds the ability to have "friendly" versions of functions that we'll generate instead of operator + and the like.

However, they gen to 2 different selectors. They really shouldn't/

https://github.com/mono/Embeddinator-4000/pull/190

**Comment by VincentDondain** [comment]
Let me move my question from the other PR here:

@chamons @spouliot I wonder if we should go:

```
addValue: andValue:
```

```
substractValue: andValue:
```

```
multiplyValue: andValue:
```

Instead of using the argument name.

**Comment by spouliot** [comment]
Not sure I like them better but the closest Apple offers seems to be `NSDecimalNumber`
https://developer.apple.com/reference/foundation/nsdecimalnumber?language=objc

However the core issue is about consistency between the operator overload and the friendly-named methods. We can change the name later - but they should be, and remain, consistent.

**Comment by chamons** [comment]
When done we should update the docs (see https://github.com/mono/Embeddinator-4000/pull/255)

**Comment by chamons** [comment]
https://github.com/mono/Embeddinator-4000/pull/290 is in.

Let me update docs and then we can close this.

**Comment by spouliot** [comment]
PR #297 was merged
