### ISSUE TITLE
[objc] Add support for `IEquatable<T>`

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#219]
We have _cute_ support for `NSObject` protocol which means the managed `bool Equals (object)` generates the expected:

```
- (bool)isEqual:(id _Nullable)other;
```

However other equality methods, like the one required to implement `IEquatable<T>` [1], are still using the _default_ generated code, which looks like:

```
- (bool)equalsObj:(TimeSpan *)obj;
```

That should be changed to generate something like:

```
- (bool)isEqualToTimeSpan:(TimeSpan * _Nullable)other;
```

[1] https://msdn.microsoft.com/en-us/library/ms131187(v=vs.110).aspx

**Comment by timrisi** [comment]
PR 299

**Comment by timrisi** [comment]
Merged
