### ISSUE TITLE
Packaging / Installer?

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#222]
Users being able to try E4K without git clone.

**Comment by spouliot** [comment]
Currently what we need to ship is, minimally, an .exe with Mono.Options.dll - so it requires Mono [1]. This leaves us with a lot of options, e.g

* a zip file with a README - it might be a bit brutal;

* a .dmg (like XS) where you can drag the tool into a pre-determined (or your own) location;

* a .pkg like Xamarin.[iOS|Mac] - that could install stuff inside `/Library/Frameworks/*` using the same convention as XI/XM

* a tool only nuget - _never done that one but it sounds like option_;

more ?

Distribution requirements needs to be discussed with RE.

[1] let's say 5.0 since it should be stable by the time the package/installer is ready

**Comment by chamons** [comment]
I don't understand all of the bits well enough to know if this is a stupid question but:

Could we package everything up inside a Xamarin.Mac bundle? That way we could get a nice self contained bundle to shove inside our zip/dmg/pkg/nuget/whatever

**Comment by spouliot** [comment]
@chamons for dropping the mono requirement ? and/or other advantages ?

For the former we could `mkbundle` the executable (simpler) but it would mean the .exe could not be copied back to windows [1] but it's not something I had really considered [2] and makes the *zip* a bit more attractive.

[1] it technically can generate source on Windows, use not invoke `clang`
[2] it will become more important for other targets than ObjC (but out of our scope)

**Comment by chamons** [comment]
Mostly dropping the mono requirement and making mostly sure all of our bits are relative to each other (the installer generation is a simple invocation to productbuild so it doesn't buy much).

mkbundle would do the same thing simplier, but that outputs just a raw binary, right? If we have to ship other resources they'll either be free or we'll have to make a bundle of some type anyway, right?

**Comment by spouliot** [comment]
Mono is kind of a requirement anyway since the .dylib (to embed) come from it (for macOS + system mono). The other options requires either XM or XI and both of them requires mono to be installed.

**Comment by chamons** [comment]
Fair enough. Then I lean towards .zip file for simplicity or a pkg for possible ability to upgrade in place later.

I know almost nothing about nuget though...

**Comment by VincentDondain** [comment]
I vote for **pkg**.

- zip is too brutal
- I don't see how dmg is a good option for command line tools
- Nuget is good for how easy it is to release but I'm not quite sure how to call the tool within the bundle from command line (also after a quick discussion with Mikayla she didn't show a particular desire to take the Nuget approach, so likely no strong value).

About pkg:
> install stuff inside `/Library/Frameworks/*` using the same convention as XI/XM

Sounds great to me and people will be able to use the command from command line instantly.

**Comment by chamons** [comment]
If we shove in /Library/Frameworks/ (which is 👍  by me) let us consider making a Commands subfolder like XM:

/Library/Frameworks/Xamarin.Mac.framework/Commands

where we have sym links to the "real" command. It's a friendly touch that Aaron added a long time ago that XI doesn't have (yet).

**Comment by spouliot** [comment]
I also prefer a .pkg but that's mostly because it's a known beast :)

The nuget sounded potentially interesting to cover Windows/VS and to have an easier way to upgrade when new versions are published.

**Comment by spouliot** [comment]
The getting started guide will need to be updated afterward
https://github.com/mono/Embeddinator-4000/blob/objc/docs/getting-started-objective-c.md#installation

**Comment by spouliot** [comment]
PR #258 (installer) and https://github.com/mono/Embeddinator-4000/pull/263 (docs) are both merged
