### ISSUE TITLE
Documentation / Getting Started Docs 

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#223]
Features without documentation don't exist, and a product without a getting started doesn't exist.

We should get started on some docs.

**Comment by realvictorprm** [comment]
@chamons Also told in issue #160

**Comment by spouliot** [comment]
@dalexsoto I'd like you to write the macOS getting started based on the weather sample that you wrote;

@rolfbjarne for iOS we need to discuss if we're doing a basic (non XI) or more advanced tutorial before starting;

**Comment by VincentDondain** [comment]
As I mentioned here: https://github.com/mono/Embeddinator-4000/issues/160#issuecomment-298375522 we should have the getting started file as an `md` file in the repo so we can PR to it and likely link that file in a future wiki. Also we should reproduce the behavior of xamarin-macios wrt doc files to push them on the documentation website.

**Comment by spouliot** [comment]
Documentation is already kept inside `/docs` for PR (reviews) and simultaneous commit with the associated feature. The getting started guides will be added along with existing documentation.

Right now (subject to change) docs are published thru Github Pages at https://mono.github.io/Embeddinator-4000/ and requires a merge to master to become visible.

**Comment by spouliot** [comment]
PR #243 has the base for getting started, which should split into separate docs to cover macOS (@dalexsoto) and iOS (@rolfbjarne)

**Comment by rolfbjarne** [comment]
iOS docs in PR #266.

**Comment by spouliot** [comment]
Both PR were merged and everything is also on master.
