### ISSUE TITLE
[objc] Not sure why I need --debug to compile and get a framework

### ISSUE THREAD

**Issue by VincentDondain** [mono/Embeddinator-4000#237]
`mono ./bin/Debug/objcgen.exe -o /Users/vidondai/Desktop/Output ../tests/objc-cli/debug/managed.dll --target=framework -c -platform=ios` > doesn’t work

Non working scenario [gist file](https://gist.github.com/VincentDondain/227e1e39d53f64d4038a99dc6e1fb50b).

`mono ./bin/Debug/objcgen.exe -o /Users/vidondai/Desktop/Output ../tests/objc-cli/debug/managed.dll --target=framework -c -platform=ios --debug` > works

Working scenario [gist file](https://gist.github.com/VincentDondain/28e62bc67120ca679ed11671a5351388).

I'm not quite sure why we need `--debug` here. It's not super obvious and I expect people trying out e4k to be as confused (:

**Comment by spouliot** [comment]
The answer to the question is in your gist ;-)

**Comment by spouliot** [comment]
PR #238 has a fix, a workaround and enable iOS/release in the tests built on the bots.

Assigning to @rolfbjarne for a proper fix to replace the workaround (which disabling stripping native symbols).

**Comment by rolfbjarne** [comment]
This was fixed with PR #305.
