### ISSUE TITLE
[objc] subscript without setters throws a NullReferenceException

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#239]
while trying to duplicate #225 I got this `NullReferenceException` (with newer version of Mono). The code that throws is

```
Type indexType = pi.GetSetMethod ().GetParameters () [0].ParameterType;
```

because `pi.GetSetMethod ()` returns `null` for

```
System.Security.Permissions.KeyContainerPermissionAccessEntryCollection Item
```

since it only has a getter [1]

[1] https://msdn.microsoft.com/en-us/library/system.security.permissions.keycontainerpermissionaccessentrycollection.item(v=vs.110).aspx

**Comment by chamons** [comment]
My subscript code was dumb. It never considered the possibility of get or set only items.

**Comment by spouliot** [comment]
PR 245 was merged
