### ISSUE TITLE
[objc] Map `System.Decimal` with `NSDecimalNumber`

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#254]
Add back and forth conversion between .NET `System.Decimal` and Foundation `NSDecimalNumber`

**Comment by dalexsoto** [comment]
@rolfbjarne / @spouliot I am facing an issue with current implementation (PR #292) in iOS simulator, to get you some context the generated code looks like this.

```csharp
+ (NSDecimalNumber *)zero
{
	static MonoMethod* __method = nil;
	if (!__method) {
#if TOKENLOOKUP
		__method = mono_get_method (__managed_image, 0x06000027, Type_Decimal_class);
#else
		const char __method_name [] = "Type_Decimal:get_Zero()";
		__method = mono_embeddinator_lookup_method (__method_name, Type_Decimal_class);
#endif
	}
	MonoObject* __exception = nil;
	MonoObject* __result = mono_runtime_invoke (__method, nil, nil, &__exception);
	if (__exception) {
		mono_embeddinator_throw_exception (__exception);
	}
	void* __unboxedresult = mono_object_unbox (__result);
	MonoObject* __invariantculture = mono_embeddinator_get_cultureinfo_invariantculture_object ();
	MonoMethod* __tostringmethod = mono_embeddinator_lookup_method (":ToString(System.IFormatProvider)", mono_object_get_class (__result));
	void* __tostringargs [1];
	__tostringargs [0] = __invariantculture;
	MonoObject* __ex = nil;
	MonoString* __decimalmonostr = (MonoString *) mono_runtime_invoke (__tostringmethod, __unboxedresult, __tostringargs, &__ex);
	if (__ex)
		mono_embeddinator_throw_exception (__ex);
	NSString* __decimalnsstr = mono_embeddinator_get_nsstring ((MonoString *) __decimalmonostr);
	NSDictionary* __forcedotseparator = @{ NSLocaleDecimalSeparator : @"." };
	NSDecimalNumber* __nsdecresult = [NSDecimalNumber decimalNumberWithString:__decimalnsstr locale:__forcedotseparator];
	return __nsdecresult;
}
```

All works great on the Mac but in iOS simulator the `ToString (IFormatProvider)` lookup function is returning `NULL`

```csharp
MonoMethod* __tostringmethod = mono_embeddinator_lookup_method (":ToString(System.IFormatProvider)", mono_object_get_class (__result));
```

Do you guys have an idea on why this could be happening?

**Comment by rolfbjarne** [comment]
It was probably linked away.

I guess we'll need a to pass a custom xml linker file to mtouch to tell the linker what we need.

**Comment by spouliot** [comment]
It's the same issue as https://github.com/mono/Embeddinator-4000/pull/251#issuecomment-299082288
We'll need to track SDK types/members using a generate an XML file.

It's also trickier in release, (where `TOKENLOOKUP` is defined, since the token might exists but for something else as the assembly was re-written. No good solution for this one (we'll not regenerate the bindings) we we'll need to turn off `TOKENLOOKUP` generation for code inside the SDK (only).

**Comment by rolfbjarne** [comment]
Actually we'll need to turn off `TOKENLOOKUP` for all assemblies when the linker is executed, because the linker will re-save all assemblies, even those not linked (at least for XM, where I ran into this today).

**Comment by spouliot** [comment]
@rolfbjarne good point, it's not always (for XI) but there are cases where a save can be done. Maybe we could put all the `XXX_TOKEN` into a separate header ? That way we could be re-generate independently... I'll file another issue with this (low priority until more measurements are done), until then we can disable the feature for XI/XM.

**Comment by spouliot** [comment]
PR #292 was merged
