### ISSUE TITLE
[objc] packager install location

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#268]
Packager install in 
`/Library/Frameworks/Xamarin.Embeddinator-4000/`

and to be similar with our other packages it should be
`/Library/Frameworks/Xamarin.Embeddinator-4000.framework/`

**Comment by spouliot** [comment]
Note that current documentation will need to be updated to match...
OTOH all other directories under `/Library/Frameworks/` do end with `.framework`

**Comment by chamons** [comment]
My bad. Fixing

**Comment by chamons** [comment]
PR up: https://github.com/mono/Embeddinator-4000/pull/273

```ls /Library/Frameworks/Xamarin.Embeddinator-4000.framework/
Commands Versions
```

**Comment by chamons** [comment]
https://github.com/mono/Embeddinator-4000/pull/273 is landed
