### ISSUE TITLE
[Architectural] ImplementMethod should work on ProcessedMethod and GetSignatures should be moved into ProcessedMethodBase

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#276]
Right now ImplementMethod and GetSignatures are dumping grounds with a ton of arguments and more on the way.

The correct architectural involves the processor/post processor determining signatures and the generating accepting this information to generate code. That's the sane way to handle duplicates / attributes renaming things / etc.

**Comment by spouliot** [comment]
@chamons https://github.com/mono/Embeddinator-4000/pull/284 is a step in that direction
