### ISSUE TITLE
[Package] Add Library/Frameworks/Xamarin.Embeddinator-4000.framework/Commands to $PATH

### ISSUE THREAD

**Issue by VincentDondain** [mono/Embeddinator-4000#277]
See conversation in https://bugzilla.xamarin.com/show_bug.cgi?id=55930

Also, one internal fellow had “issues” after installing embeddinator thinking the install didn’t work because we don’t modify `$PATH`.

**Comment by dalexsoto** [comment]
➕ 1 got the same comment from another internal tester

**Comment by VincentDondain** [comment]
Fixed in https://github.com/mono/Embeddinator-4000/pull/280
