### ISSUE TITLE
Binding the managed assembly for iOS is giving errors

### ISSUE THREAD

**Issue by GouriKumari** [mono/Embeddinator-4000#279]
Steps to reproduce:
Install Xamarin.Embeddinator-4000-0.1.0.9.pkg
Create a hello-from-csharp project and build it as mentioned in https://mono.github.io/Embeddinator-4000/getting-started-objc-ios.html.
Bind managed assembly.

Actual Behaviour:
https://gist.github.com/GouriKumari/89719045703ead91b442e25b0b626472

Test Env:
https://gist.github.com/3a85edd26f87064100986beb9d819216

**Comment by spouliot** [comment]
@GouriKumari 

from your gist
> Version: 10.10.0.30 (Visual Studio Enterprise)

from the [guide](https://github.com/mono/Embeddinator-4000/blob/master/docs/getting-started-objc-ios.md#requirements)
* **Xamarin.iOS from our master branch.**
