### ISSUE TITLE
[objc] Passing arrays as refs

### ISSUE THREAD

**Issue by timrisi** [mono/Embeddinator-4000#314]
Found while attempting to bind mscorlib:

```error EM0009: The feature `Converting type System.Byte[] to mono code` is not currently supported by the tool```

Error occurs on the type ```System.Resources.ResourcesReader``` from the method 
 
```Void GetResourceData(System.String, System.String&, System.Byte[]&)```

**Comment by dalexsoto** [comment]
@timrisi fixed! Decimal is pending

**Comment by spouliot** [comment]
PR #321 was merged
