### ISSUE TITLE
TextTransform.exe invocation is not cross platform safe.

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#337]
https://github.com/mono/Embeddinator-4000/pull/335#issuecomment-301167726

**Comment by realvictorprm** [comment]
I did not encounter issues with this yet on windows, did I missed something?

Currently working on  #278, that's why I'm asking.

**Comment by spouliot** [comment]
Fixed in `objc` branch (PR #338 merged), removing milestone.
