### ISSUE TITLE
Typo in the Logo?

### ISSUE THREAD

**Issue by lukaskollmer** [mono/Embeddinator-4000#340]
I don't know if this is intentional, but I just noticed that, while the repo name spells "Embe**dd**inator" with two "d"s, the logo embedded at the top of the readme spells "Embe**d**inator" with just one "d".

![image](https://cloud.githubusercontent.com/assets/6547384/26026287/e3f91d3c-37f8-11e7-9b3e-e1755b7651a8.png)

---

![](https://raw.githubusercontent.com/mono/Embeddinator-4000/master/e4000-logo.png)

**Comment by tritao** [comment]
cc @migueldeicaza who added the logo

**Comment by migueldeicaza** [comment]
I struggle with this question.

I think it should be embeddinator, but I could use the help of a strong linguist to give me guidance here, before we go and try to update this logo.

**Comment by sandyarmstrong** [comment]
I don't know if I'm the strongest linguist, but I would suggest that a single "d" is more expected in English.

Would this necessitate a version bump from 4000 to 4001?

**Comment by iainx** [comment]
It's not the Termminator after all

**Comment by charlespetzold** [comment]
The consensus (more or less) among the Docs team is that the precedent set by the words "embedded" and "embedding" mandates two D's.

**Comment by sandyarmstrong** [comment]
I humbly submit to the opinion of the docs team.

**Comment by Phrohdoh** [comment]
I may be missing something here but that logo looks like it contains two D's to me.

**Comment by sandyarmstrong** [comment]
It was just fixed.
