### ISSUE TITLE
Property getters and generics.

### ISSUE THREAD

**Issue by sinkingsugar** [mono/Embeddinator-4000#345]
Not sure if it has been reported or it is a known issue but I have a stack-overflow in property visitor when a generic class has a `where T : type`.
The following code can reproduce the issue.
If I replace the property with a `GetListeners` method it works.

```C#
using System.Collections.Generic;

namespace Test
{
    public interface IEventListener
    {
    }
    
    public interface IEventListener<TEventType> : IEventListener where TEventType : Event
    {
        void ProcessEvent(TEventType inputEvent);
    }

    public class Event
    {
    }

    public class EventRouter<TEventType> where TEventType : Event
    {
        private readonly HashSet<IEventListener> listeners = new HashSet<IEventListener>();

        // This doesn't work
        //public HashSet<IEventListener> Listeners
        //{
        //    get { return listeners; }
        //}

        // This works
        public HashSet<IEventListener> GetListeners()
        {
            return listeners;
        }
    }
}
```

**Comment by realvictorprm** [comment]
Which generator?

**Comment by sinkingsugar** [comment]
c generator, was targeting iOS

**Comment by tritao** [comment]
I can repro the issue locally.

**Comment by realvictorprm** [comment]
@tritao Nah looks like bug fixes come first.

**Comment by sinkingsugar** [comment]
can repro with objc backend too it seems.

**Comment by tritao** [comment]
This is a general regression when processing the assembly added in https://github.com/mono/Embeddinator-4000/commit/3af3f6e6a1381a065354dc1aeffe594e6f1f2cdf.

I should have a fix soon.
