### ISSUE TITLE
[objc] We should warn/rename anything that overrides NSObject type/protocol

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#346]
E.g. one of our existing test expose `Class`, which means we override `class` and that's pretty bad.
E.g. `hash` is fine if it’s our `GetHashCode`, not if it’s something else

internal link: https://xamarinhq.slack.com/archives/C07K1594N/p1494936852477097

c.c. @chamons since the best place to do this is likely after (or part) of the dupe check

**Comment by chamons** [comment]
I believe https://github.com/mono/Embeddinator-4000/pull/363 covers class and hash. If there are additional cases we can create new issues.
