### ISSUE TITLE
Consider "frozen" ProcessedFoo types for processor/generator layer

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#371]
The signature caching is one area that is hilighting an architectural flaw in E4K. The ideal world has:

- Processor (ObjCProcessor) - Walks assembly and creates processedfoo types
- Post-processor - Walks the generated processedfoo types and marks them up with information needs to correctly generate code
- Generator - Walks the processed types and outputs could. Does not modify the data structures or make decisions

Right now the generator is very much making decisions and modifying the processed types.

We _could_ use "popsicle" immutability to flush these out.

- For every ProcessedFoo classes, make a corresponding Frozen variant which is read only.
- Once we are about to pass into the generator, we "freeze them" and pass in the immutable versions
- We'll determine rather quickly (compile time) where we are cheating.

**Comment by spouliot** [comment]
We should move the remaining code and then reduce visibility (prtotected) for all API that mutate state

**Comment by chamons** [comment]
We now freeze the cache at least. We could extend it to throw or return a new type in the future if we run into more pain.

**Comment by chamons** [comment]
We have a first pass (from last year), which is enough for this issue.
