### ISSUE TITLE
[Android] Error with glib.h

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#417]
I am attempting to run e4k on a dll, and I am running into an error in the generated file about the include of glib.h. I have run brew install glib and have version 2.52.3 installed. The verbose output of my execution is below:

> Parsing assemblies...
>     Parsed 'HIAAsAService.Lib.dll'
> Processing assemblies...
>     Pass 'MonoEmbeddinator4000.CheckReservedKeywords'
>     Pass 'MonoEmbeddinator4000.Passes.GenerateObjectTypesPass'
>     Pass 'MonoEmbeddinator4000.Passes.GenerateArrayTypes'
>     Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
>     Pass 'MonoEmbeddinator4000.Passes.FieldToGetterSetterPropertyPass'
>     Pass 'MonoEmbeddinator4000.Passes.FixMethodParametersPass'
>     Pass 'MonoEmbeddinator4000.Passes.RenameDuplicatedDeclsPass'
>         Renamed HIAAsAService_Lib_Interfaces_IServiceLibDigitalParameterAccess_SetParameterValue_1
>         Renamed HIAAsAService_Lib_Interfaces_IServiceLibDigitalParameterAccess_SetParameterValue_2
>         Renamed HIAAsAService_Lib_Interfaces_IServiceLibDigitalParameterAccess_SetParameterValue_3
>         Renamed HIAAsAService_Lib_Interfaces_IServiceLibDigitalParameterAccess_SetParameterValue_4
>         Renamed HIAAsAService_Lib_Interfaces_IServiceLibDigitalParameterAccess_SetParameterValue_5
>     Pass 'CppSharp.Passes.CheckDuplicatedNamesPass'
> Generating binding code...
>     Could not find directory with support API.
>     Generated: HIAAsAService.Lib.h
>     Generated: HIAAsAService.Lib.c
>     Generated: mscorlib.h
>     Generated: mscorlib.c
> Compiling binding code...
>     Found Android SDK. API levels: 15, 19, 20, 21, 22, 23, 24
>     Invoking: /Users/varghesp/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc --sysroot="/Users/varghesp/Library/Android/sdk/ndk-bundle/platforms/android-24/arch-arm" -DMONO_EMBEDDINATOR_DLL_EXPORT -I"/Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0" -L"/Library/Frameworks/Xamarin.Android.framework/Versions/Current/bin/../lib/xbuild/Xamarin/Android/lib/armeabi" -lmonosgen-2.0 generated/HIAAsAService.Lib.c generated/mscorlib.c --std=c99 -shared -o generated/android/jni/armeabi/libHIAAsAService.Lib.so
>         In file included from generated/HIAAsAService.Lib.c:7:0:
> generated/HIAAsAService.Lib.h:9:18: fatal error: glib.h: No such file or directory
>  #include "glib.h"
>                   ^
> compilation terminated.
> In file included from generated/mscorlib.c:7:0:
> generated/mscorlib.h:9:18: fatal error: glib.h: No such file or directory
>  #include "glib.h"
>                   ^
> compilation terminated.
> 
> Failed to compile generated code.

**Comment by tritao** [comment]
The clue is on the output you pasted: `Could not find directory with support API.`.

Did you copy the executable out of the build folder for instance? Right now the executable depends on finding the `support` folder on the repo to generate the needed support files (like `glib.h`).

**Comment by Zomb** [comment]
No, I have not copied the exe out of the folder, this is command I was running:

> mono ~/Git/Embeddinator-4000/build/lib/Debug/MonoEmbeddinator4000.exe HIAAsAService.Lib.dll --gen=Java --platform=Android -outdir=generated -c -v

Your comment did point me in the right direction though! I was not running the command from the root of the e4k project. Once I did the error disappeared. Hopefully this will help anyone who runs into the same issue.
