### ISSUE TITLE
[Android] condition 'vtable' not met

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#418]
The native app consuming the generated aar is crashing with (some of) the stacktrace shown below. I can't really figure out what might be causing the crash, is there any way for me to get more information on this crash?

```
> 07-01 18:48:24.922 1175-1230/? W/AppOps: Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
>                                          
>                                          [ 07-01 18:48:25.012  7074: 7074 F/         ]
>                                          * Assertion at /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mono/metadata/object.c:5223, condition `vtable' not met
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: Stacktrace:
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: /proc/self/maps:
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: 12c00000-12c9f000 rw-p 00000000 00:04 18926                              /dev/ashmem/dalvik-main space (deleted)
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: 12c9f000-12e9f000 rw-p 0009f000 00:04 18926                              /dev/ashmem/dalvik-main space (deleted)
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: 12e9f000-22c00000 ---p 0029f000 00:04 18926                              /dev/ashmem/dalvik-main space (deleted)
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: 32c00000-32c01000 rw-p 00000000 00:04 18927                              /dev/ashmem/dalvik-main space 1 (deleted)
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: 32c01000-42c00000 ---p 00001000 00:04 18927                              /dev/ashmem/dalvik-main space 1 (deleted)
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: 70a1b000-70cba000 rw-p 00000000 103:13 1155537                           /data/dalvik-cache/arm64/system@framework@boot.art
> 07-01 18:48:25.012 7074-7074/com.starkey.android.newlink.nativeandroid E/mono-rt: 70cba000-70e36000 rw-p 00000000 103:13 1155538                           /data/dalvik-cache/arm64/system@framework@boot-core-libart.art
> 
```

**Comment by tritao** [comment]
Can you provide the AAR file and/or a sample managed DLL that causes this?

**Comment by Zomb** [comment]
I can provide the AAR, but it contains internal code that I can't post on a public forum, an I don't seem to be able to create a private bug on here like I could in Bugzilla. Can I email you a link to your github address?

**Comment by tritao** [comment]
Sure.

**Comment by tritao** [comment]
OK I think I know what's going on here, the `HIALib.dll` assembly depends on other assemblies and we fail to package it correctly.

A console application referencing the DLL is enough to trigger an exception:

```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'HIAAsAService.Lib.HiaAsAServiceLib:_hearingAidController' (0)
```

If we list the `.aar` file contents:

```
Archive:  HIALib.aar
  Length     Date   Time    Name
 --------    ----   ----    ----
        0  07-01-17 16:39   META-INF/
       68  07-01-17 16:39   META-INF/MANIFEST.MF
      299  07-01-17 16:39   AndroidManifest.xml
        0  07-01-17 16:39   assets/
        0  07-01-17 16:39   assets/assemblies/
    36864  07-01-17 16:39   assets/assemblies/HIALib.dll
  3740160  05-24-17 12:45   assets/assemblies/mscorlib.dll
   998912  05-24-17 12:45   assets/assemblies/System.Core.dll
  1998848  05-24-17 12:45   assets/assemblies/System.dll
   760025  07-01-17 16:39   classes.jar
```

We can tell that is missing some extra assemblies. You can try opening the `.aar` file directly and adding the missing assemblies to the `assets/assemblies` folder and try again.

Meanwhile I'll see about fixing this one properly.

**Comment by Zomb** [comment]
Yes, you are right, none of the referenced assemblies have been copied over to the assemblies folder. I think (and I might be mistaken) that the issue is in Compilation.cs, where the assemblies are being copied into the assets directory. The path for all referenced assemblies appeared to be combined with MonoDroidSdk.FrameworkPath, which works fine for mscorlib, but not for the remaining referenced assemblies, resulting in none of the referenced assemblies being copied over.

**Comment by tritao** [comment]
We'll soon be merging a PR that re-works some of this compilation process for Android and should re-use the same assembly lookup logic as the Xamarin.Android build process, so hopefully this issue and some other open issues related to missing assemblies will be fixed.

**Comment by jonathanpeppers** [comment]
@Zomb can you try what we merged into master today?

There are quite a few changes, docs on it here: https://mono.github.io/Embeddinator-4000/getting-started-java-android.html

**Comment by Zomb** [comment]
I have made more progress with the new code! All the assemblies are getting packaged into the aar, but I now running into a new exception:

> java.lang.RuntimeException: Unable to get provider mono.embeddinator.AndroidRuntimeProvider: mono.embeddinator.RuntimeException: java.lang.ClassNotFoundException: HIALib_dll.Native_HIALib_dll


I am not sure what is causing this, but I will check further and see if I can find out!

**Comment by jonathanpeppers** [comment]
Can you look and see if this class exists in your output:
```
$(output)/HIALib_dll/NativeHIALib_dll.java
```

It might be that something is now lower case here. Our integration tests use `managed.dll`.

**Comment by Zomb** [comment]
What I have is 

> $(output)/hialib_dll/Native_HIALib_dll.java

The folder appears to be lowercase.

**Comment by jonathanpeppers** [comment]
I'll send a PR this afternoon, if you want to try yourself I think it would just be `support/java/android/AndroidRuntimeProvider.java`:
```java
String className = mainAssembly.toLowerCase() + "_dll.Native_" + mainAssembly + "_dll";
```

**Comment by Zomb** [comment]
Yup, that appears to have fixed the issue! I have more questions, but will file a separate issue. Thank you!
