### ISSUE TITLE
[Android] Support library exception

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#427]
Adding in the support library and using the LocalBroadcastManager results in the following exception:

> Compiling binding code...
>         testgenerated2/src/mono/android/support/v4/app/SharedElementCallback_OnSharedElementsReadyListenerImplementor.java:8: error: package android.support.v4.app.SharedElementCallback does not exist
> 		android.support.v4.app.SharedElementCallback.OnSharedElementsReadyListener
> 		                                            ^
> testgenerated2/src/mono/android/support/v4/content/Loader_OnLoadCanceledListenerImplementor.java:8: error: package android.support.v4.content.Loader does not exist
> 		android.support.v4.content.Loader.OnLoadCanceledListener
> 		                                 ^
> testgenerated2/src/mono/android/support/v4/content/Loader_OnLoadCanceledListenerImplementor.java:28: error: package android.support.v4.content does not exist
> 	public void onLoadCanceled (android.support.v4.content.Loader p0)
> 	                                                      ^
> testgenerated2/src/mono/android/support/v4/content/Loader_OnLoadCanceledListenerImplementor.java:33: error: package android.support.v4.content does not exist
> 	private native void n_onLoadCanceled (android.support.v4.content.Loader p0);
> 	                                                                ^
> testgenerated2/src/mono/android/support/v4/content/Loader_OnLoadCompleteListenerImplementor.java:8: error: package android.support.v4.content.Loader does not exist
> 		android.support.v4.content.Loader.OnLoadCompleteListener
> 

This was in an attempt to use intents to work around issue #421  

Steps to reproduce:
1. Create an Android Library class project
2. Add Xamarin.Android.Support.v4
3. Add LocalBroadcastManager.GetInstance(Application.Context); to a test method
4. Run e4k

**Comment by jonathanpeppers** [comment]
Hmm, so it looks like the Java code isn't compiling.

I'm guessing if you are embedding an assembly that references a Java binding project, E4K needs to add additional jar files to the classpath.

I'll take a look, thanks for reporting.

**Comment by jonathanpeppers** [comment]
@Zomb I got it to work: https://github.com/jonathanpeppers/Embeddinator-4000/tree/android-java-binding

A couple things I had to do to make your example work:
- TargetFrameworkVersion is now 7.0 - I think this makes more sense than 2.3
- mono.android.jar for 7.0 is Java 1.8 - 🤦‍♂️ 
- Setting up our test Android Studio project for Java 1.8 wasn't too bad

If you want to try my branch go for it, I need to test more tomorrow and update the docs about Java 1.8 before I can send a PR.

**Comment by Zomb** [comment]
I have a couple of others things I want to try, so I will probably check this out as soon as you merge it to master!

**Comment by jonathanpeppers** [comment]
@Zomb try it out and let me know. Feel free to reopen or post a new issue.

Thanks for the help!
