### ISSUE TITLE
[api] we must be able to override from where assemblies are loaded

### ISSUE THREAD

**Issue by spouliot** [mono/Embeddinator-4000#43]
The current code assume they will be with the executable. That's not gonna work for all scenarios, e.g. plugins.  PR#42 ran into this issue while adding Xcode-based unit tests. There's a band-aid API to move things forward but it should be revisited to cover more scenarios*

* creating a .framework will also require a different location, c.c. @rolfbjarne 

reference: https://github.com/mono/Embeddinator-4000/pull/42

**Comment by tritao** [comment]
We got APIs for this now in the runtime
