### ISSUE TITLE
[Android] Failed build clean clone

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#433]
I am running into an exception when I run the build on a clean clone of master. It looks like its a test project that is failing, and I hoping I can still use e4k even with this failure!

> WARNING : error : NameResolutionFailure [/Users/varghesp/Git/Embeddinator-4000/tests/managed/android/managed-android.csproj]
>   Installing 'Mono.TextTransform 1.0.0'.
>   Added file 'Mono.TextTemplating.dll' to folder '/Users/varghesp/Git/Embeddinator-4000/packages/Mono.TextTransform.1.0.0/tools'.
>   Added file 'TextTransform.exe' to folder '/Users/varghesp/Git/Embeddinator-4000/packages/Mono.TextTransform.1.0.0/tools'.
>   Added file 'Mono.TextTransform.1.0.0.nupkg' to folder 'Mono.TextTransform.1.0.0'.
> EXEC : warning : 'Mono.TextTransform.1.0.0/Mono.TextTransform.1.0.0.nupkg' already exists. Skipping... [/Users/varghesp/Git/Embeddinator-4000/tests/managed/android/managed-android.csproj]
>   Successfully installed 'Mono.TextTransform 1.0.0'.
> /Users/varghesp/Git/Embeddinator-4000/tests/managed/CustomBuildActions.targets(3,3): error MSB3073: The command "nuget install Mono.TextTransform -OutputDirectory ../../packages/" exited with code -1. [/Users/varghesp/Git/Embeddinator-4000/tests/managed/android/managed-android.csproj]

**Comment by jonathanpeppers** [comment]
Our PR builders do a clean clone. But they either run:
```
./build.sh -t AppVeyor
```
or
```
tests/RunTestsuite.sh
```

Is this happening in an IDE?

**Comment by Zomb** [comment]
No, this in in a Mac terminal. I am running this command from the command line:

> ./build.sh -t Generate-Android -v diagnostic

**Comment by jonathanpeppers** [comment]
Sorry, I read your error more closely. It looks like nuget is having DNS trouble.

If you do this, does it work:
```
nuget install Mono.TextTransform
```

You can also try the nuget we have in our repo:
```
mono .nuget/nuget.exe Mono.TextTransform
```

If the second one works, maybe it is better for us to never use the system-wide nuget.

**Comment by Zomb** [comment]
I seem to be having random behavior with Nuget. This first time I ran it I got this:

> WARNING: Error: NameResolutionFailure
> Installing 'Mono.TextTransform 1.0.0'.
> Added file 'Mono.TextTemplating.dll' to folder '/Users/varghesp/Git/Embeddinator-4000/Mono.TextTransform.1.0.0/tools'.
> Added file 'TextTransform.exe' to folder '/Users/varghesp/Git/Embeddinator-4000/Mono.TextTransform.1.0.0/tools'.
> Added file 'Mono.TextTransform.1.0.0.nupkg' to folder 'Mono.TextTransform.1.0.0'.
> WARNING: 'Mono.TextTransform.1.0.0/Mono.TextTransform.1.0.0.nupkg' already exists. Skipping...
> Successfully installed 'Mono.TextTransform 1.0.0'.
> 

I run it a second time, I get:

> WARNING: Error: NameResolutionFailure
> 'Mono.TextTransform 1.0.0' already installed.

Now I connect to my VPN (which should make no difference whatsoever) and the NameResolutionFailure goes away and everything works fine! I don't know what the issue is but hey, it works!
