### ISSUE TITLE
[Android] Error using Android Studio 3.0 Canary 7

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#448]
I am attempting to use Android Studio 3.0 because of the requirement for Java 1.8 and I am running into the following error:

> 
> 07-20 11:10:17.179 20983-20983/com.starkey.trulink.android E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                              Process: com.starkey.trulink.android, PID: 20983
>                                                                              java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.starkey.trulink.android-1/base.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.starkey.trulink.android-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.starkey.trulink.android-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libmonodroid.so"
>                                                                                  at java.lang.Runtime.loadLibrary0(Runtime.java:984)
>                                                                                  at java.lang.System.loadLibrary(System.java:1562)
>                                                                                  at mono.embeddinator.AndroidImpl.initialize(AndroidImpl.java:25)
>                                                                                  at mono.embeddinator.Runtime.initialize(Runtime.java:125)
>                                                                                  at mono.embeddinator.Runtime.loadLibrary(Runtime.java:151)
>                                                                                  at hialibandroid.Native_HIALibAndroid.<clinit>(Native_HIALibAndroid.java:17)

This might not be valid because 3.0 is not released yet, but I figured in would be a good test. I also have one Kotlin file in the Android Studio project. The app fails on deploy, it appears to build fine. I am not calling into the library, just have it as a dependent module.

**Comment by Zomb** [comment]
The next issue I am running into is that the new Kotlin plugin is not compatible with the Jack toolchain, but the Jack toolchain is required to use e4k in stable Android Studio. I will try and revert back to an older version of the plugin, or just not use Kotlin to work around this issue for now.

**Comment by Zomb** [comment]
Yup, with Android Studio 2.3.3 stable it works fine if you are not using Kotlin. The moment you install the Kotlin plugin, Kotlin complains because it is not compatible with the Jack toolchain. Android Studio 3.0 appears to be the only solution if you want to use Kotlin and Java 8. 

I have downgraded from Kotlin plugin from 1.1.3-2 to 1.1.1 which does support the Jack toolchain, and will report back if I run into any issues!

**Comment by jonathanpeppers** [comment]
@Zomb 

It says it on here under **Known Issues**: https://developer.android.com/studio/preview/features/new-android-plugin.html

```
While using this plugin with Android Studio, dependencies on local AAR files are not yet supported.
```
So... I guess we have to wait for them to fix this.

This guy talks about a workaround, but is pretty vague: https://stackoverflow.com/questions/44785068/android-gradle-plugin-3-0-0-alpha4-not-picking-so-libraries-from-local-aar 

I wasn't able to get the `flatDirs` option to work for me. I'd say we should revisit this when Android Studio 3.0 hits beta.

**Comment by Zomb** [comment]
Sounds good! Just as info for anyone else that wants to use Kotlin and runs into this thread, the best option right now is Android Studio 2.3.3 + Jack + Kotlin plugin version 1.1.1. Just the project gradle file Kotlin plugin version needs to be changed, Android Studio can stay on 1.1.3-2.

**Comment by Zomb** [comment]
Android Studio 3.0 is now in Beta, and e4k aars appear to work without a problem. It might be beneficial to update the documentation to point to 3.0 and not use the deprecated Jack toolchain anymore.

**Comment by jonathanpeppers** [comment]
Thanks, I'll try it out.
