### ISSUE TITLE
[Android] SQLite access failing from C# library

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#452]
Accessing sqlite from the library is causing a linker failure, seen below:

> 31545-31980/com.s.t.android E/linker: library "/system/lib64/libsqlite.so" ("/system/lib64/libsqlite.so") needed or dlopened by "/data/app/com.s.t.android-2/lib/arm64/libmonosgen-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.s.t.android-2/lib/arm64:/data/app/com.s.t.android-2/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.s.t.android"]
> 31545-31980/com.s.t.android I/mono-stdout: System.DllNotFoundException: /system/lib64/libsqlite.so
> 31545-31980/com.s.t.android I/mono-stdout:     at (wrapper managed-to-native) HIA2.C.DataAccess.SQLite.SQLite3Wrapper:Open (byte[],intptr&,int,intptr)

**Comment by jonathanpeppers** [comment]
Hi @Zomb ,

What C# class/library are you using here? Is is from `Mono.Data.Sqlite` or something on NuGet?

**Comment by Zomb** [comment]
The library appears to be using a standard sqlite3.dll to access the database. I can try different options if needed though!

**Comment by jonathanpeppers** [comment]
Oh could you just paste a C# snippet, is it using `[DllImport]` directly?

I have generally used this [one](https://www.nuget.org/packages/sqlite-net-pcl/) by Frank Krueger, but I have not tested it with Embeddinator.

**Comment by Zomb** [comment]
This is the import:

```
[DllImport("sqlite3", EntryPoint = "sqlite3_open_v2", CallingConvention = CallingConvention.Cdecl)]
public static extern Result Open(byte[] filename, out IntPtr db, int flags, IntPtr zvfs);
```

**Comment by jonathanpeppers** [comment]
Ok, do you know if this works in a normal Xamarin.Android app?

Android N made it where you can't use `sqlite3` directly from a `DllImport` anymore. Frank's sqlite-net sits on top of SQLitePCL.raw by Eric Sink, and he talks about how he had to work around Android N [here](https://github.com/ericsink/SQLitePCL.raw).

It sounds like you are working with existing code, so it might be tough to port to a different SQLite library.

**Comment by Zomb** [comment]
I do believe this works in a normal Xamarin.Android app, but I will cross check, I might have just not tested on an N phone using this library. There is [this](https://forums.xamarin.com/discussion/86762/dll-issue-with-sqlite-with-nougat-version-7-0) post on the Xamarin forums with the same error I have, will try some of the options out and see if I can work around the issue!

**Comment by Zomb** [comment]
The library appears to work in a standard Xamarin.Android app, I will see if I can figure out why!

**Comment by tritao** [comment]
Is it possible we're failing to bundle the needed native libraries in the AAR?

Can you please check and list the contents of the generated AAR?

**Comment by Zomb** [comment]
These are the bundled .so files in arm64-v8a:

> libHIALibAndroid.so	
> libjnidispatch.so	
> libmonodroid.so		
> libmonosgen-2.0.so

I am trying to create a sample project with a simple database dll that I can use both in a standard Xamarin.Android project and a e4k one. I will share my results once I have that working!

**Comment by Zomb** [comment]
I did not have much luck with the dllImport on Android N, so, I started experimenting with sqlite-net-pcl. This resulted in to the following exception:

> System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception. ---> System.DllNotFoundException: e_sqlite3
> at (wrapper managed-to-native) SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods:sqlite3_libversion_number ()
> at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number () [0x00000] in <333eb4a8d93048dda7cf513b2db01259>:0 
> at SQLitePCL.raw.SetProvider (SQLitePCL.ISQLite3Provider imp) [0x00008] in <57ac49ef645c4295bc1eec6d6048bdf5>:0 
> at SQLitePCL.Batteries_V2.Init () [0x00005] in <7ea61fe397ba4b9890da8f07af0f83af>:0 
> at SQLite.SQLiteConnection..cctor () [0x00000] in <9b4aaa86123841b8bec74a2ddde70f09>:0 
> 

I am not sure why e_sqlite3 is not being found.

**Comment by Zomb** [comment]
If its of any help, the SQL libraries included in the aar are:

> SQLite-net.dll				
> SQLitePCLRaw.batteries_v2.dll		
> SQLitePCLRaw.core.dll			
> SQLitePCLRaw.provider.e_sqlite3.dll

**Comment by jonathanpeppers** [comment]
I think there is a build action used here named AndroidNativeLibrary, I bet I need to do something to get it to work in Embeddinator.

Thanks @Zomb for letting us know.

**Comment by jonathanpeppers** [comment]
Yeah, we are not extracting and including these native libraries at all yet:
![screen shot 2017-07-24 at 8 13 04 am](https://user-images.githubusercontent.com/840039/28524918-0e1ce68e-7048-11e7-9056-b30dbfdb4bf2.png)

I've not seen this `__AndroidNativeLibraries__` zip file before looking at one of these. The other zip we are extracting, because it contains assets, resources, jar files, etc. Hopefully it is easy to add this second one.

One thing you could do manually (for now) is add the so files you need to the Android Studio project. These go in `src/main/java/jniLibs/[abiname]`.

**Comment by Zomb** [comment]
I can try. Can you tell me where I can find the right so files to include?

**Comment by jonathanpeppers** [comment]
If you do this:
```
monodis --mresources path/to/SQLitePCLRaw.lib.e_sqlite3.dll 
```

It will dump `__AndroidNativeLibraries__.zip` into your current directory. Then you can unzip to get the native libraries.

I've been looking at this and unfortunately Xamarin.Android seems like it moves native libraries directly from here into the final APK. That means there isn't an existing thing I can use to put them in our AAR file. For the other zip file, there was an MSBuild task I could use that extracted them.

**Comment by Zomb** [comment]
I have been able to confirm that this works. For the reference of anyone who stumbles on this thread, these are the steps I used:
- run monodis --mresources as mentioned above
- create folder jnilibs under src/main
- copy all the architecture folders generated (arm* for example) into jnilibs folder

**Comment by jonathanpeppers** [comment]
@Zomb try it out and let us know, I added test cases specifically checking `SQLitePCL.raw` works.

**Comment by Zomb** [comment]
@jonathanpeppers When I generate the aar, should I see sqlite3.so files in jni/arm* inside the aar? Or is it packaged elsewhere?

**Comment by Zomb** [comment]
@jonathanpeppers Nevermind, it looks like the linker was stripping it out. I looked at your test and added the Init calls into my code, and the so files got added in. It appears that the dependencies from other library dlls are not enough to keep the linker from stripping the so files out.

**Comment by jonathanpeppers** [comment]
Yeah in our test project it has:
```
adding: jni/arm64-v8a/libe_sqlite3.so(in = 1212320) (out= 579604)(deflated 52%)
adding: jni/armeabi/libe_sqlite3.so(in = 983712) (out= 609207)(deflated 38%)
adding: jni/armeabi-v7a/libe_sqlite3.so(in = 905896) (out= 566523)(deflated 37%)
adding: jni/x86/libe_sqlite3.so(in = 1335860) (out= 630440)(deflated 52%)
adding: jni/x86_64/libe_sqlite3.so(in = 1294544) (out= 641900)(deflated 50%)
```

The only issue I found was due to the linker, I had to add these:
```
//All these Init() ensure the linker doesn't strip assemblies we need
SQLitePCL.Batteries_V2.Init();
SQLitePCL.lib.embedded.Init();
```
Full file is here: https://github.com/mono/Embeddinator-4000/blob/master/tests/managed/android/android.cs#L281

I think Eric made these methods in SQLitePCL.raw for this reason.

**Comment by pacomaral** [comment]
I'm having the same problem described in the first post.

Extracting the native libraries manually from __AndroidNativeLibraries__.zip doesn't work for me because I am not using the .aar in Android Studio.

I think that adding these two lines for making the assemblies be inside the .aar would work for me, but I don't know where do I have to put them. I cloned the repository and opened the solution, and, as far as I know, I should make the modifications and build to get the .exe, but I don't see where that lines should go.
