### ISSUE TITLE
[Android] Resources with camel case names are not accessible

### ISSUE THREAD

**Issue by postromantic** [mono/Embeddinator-4000#453]
If resource name contains capital letters then e4k incorrectly generates stubs for it so those resources are not accessible in host app.

__Repro__

Resources/values/Strings.xml:
```xml
<resources>
    <string name="applicationName">app</string>
</resources>
```
Class1.cs:
```java
[Register("mono.embeddinator.android.Class1")]
public class Class1 : Java.Lang.Object
{
    [Export("getText")]
    public string GetText()
    {
        return Application.Context.Resources.GetString(R.String.applicationName);
    }
}
```
getText crashes host app:
`
System.TypeInitializationException: The type initializer for 'String' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Java.Lang.LinkageError: no "I" field "applicationname" in class "Lclasslibrary3/R$string;" or its superclasses
`

**Comment by jonathanpeppers** [comment]
Thanks, I'll take a look at this.

**Comment by jonathanpeppers** [comment]
@postromantic try it out and let us know if we fixed it. Thanks for testing this stuff out for us!

I don't think we have enough test cases in this area, so it's possible there might be another way to name a resource to break this.

**Comment by postromantic** [comment]
@jonathanpeppers  works like a charm now.
Thank you!
