### ISSUE TITLE
Trying to get nuget version working

### ISSUE THREAD

**Issue by lemonmojo** [mono/Embeddinator-4000#478]
Hi there!

Up until now, I used to compile e4k myself and it worked perfectly.
Today, I upgraded to the latest Alpha channel versions of Visual Studio for Mac, Xamarin.Mac, etc. and thought I might as well switch to the NuGet version of e4k while I'm at it.
Now the binding code for my Xamarin.Mac library is still created and looks good but when objcgen is compiling the code, it spits out an error, complaining about not being able to find mono's header files.

Here's the output from the compilation step:

```
Compiling binding code...
Found Mono 5.4.0.135 (between 5.0.0.18 and 5.2.99)
Found Xamarin.Mac 3.8.0.3 (between 3.5.0.144 and 3.5.0.144)
	xcode-select -p
	xcrun clang -O2 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.7 -I/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/include -DXAMARIN_MAC -DMONO_EMBEDDINATOR_DLL_EXPORT  -c /PATHTOXAMARINMACPROJECT/bin/Debug/glib.c -o /PATHTOXAMARINMACPROJECT/bin/Debug/x86_64/glib.o 
	xcrun clang -O2 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.7 -I/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/include -DXAMARIN_MAC -DMONO_EMBEDDINATOR_DLL_EXPORT  -c /PATHTOXAMARINMACPROJECT/bin/Debug/mono_embeddinator.c -o /PATHTOXAMARINMACPROJECT/bin/Debug/x86_64/mono_embeddinator.o 
In file included from /PATHTOXAMARINMACPROJECT/bin/Debug/mono_embeddinator.c:29:
In file included from /PATHTOXAMARINMACPROJECT/bin/Debug/mono_embeddinator.h:32:
/PATHTOXAMARINMACPROJECT/bin/Debug/mono-support.h:187:10: fatal error: 'mono/jit/jit.h' file not found
#include <mono/jit/jit.h>
         ^
1 error generated.
```

How can I get objcgen to recognize where my mono header files are located? Everything's installed in the default locations so the header file it's complaining about is in `/Library/Frameworks/Mono.framework/Versions/5.4.0/include/mono-2.0/mono/jit/jit.h`.

**Comment by tritao** [comment]
Hey @lemonmojo.

I think this is an issue with the iOS support in the Nuget version due to an incompatibility with some changes we did for the Android version. I have an idea what it is and will look into it.

**Comment by lemonmojo** [comment]
Hey @tritao!

Thx for getting back to me and for looking into the problem. Please note that I'm trying to compile a Xamarin.Mac project, not Xamarin.iOS if it makes any difference.

**Comment by zgramana** [comment]
I ran into the same issues as @lemonmojo but in my case I'm actually targeting iOS. Using nuget version `0.20.0.80`.

I moved the `#endif` from `mono-support.h` line 185 to the last line and was able to successfully complete:
```
xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c ../lib/mono_embeddinator.c -o ../lib/armv7/mono_embeddinator.o
```

**Comment by zgramana** [comment]
I applied the patch to master, rebuilt, and was able to run `objcgen` as expected. @lemonmojo  I submitted the change as a PR in case you want to try yourself.

**Comment by lemonmojo** [comment]
@zgramana Yes, applying the mentioned patch to master does indeed fix the issue.
