### ISSUE TITLE
libGLESv2.so not accessible (Android)

### ISSUE THREAD

**Issue by equinox2k** [mono/Embeddinator-4000#480]
Hi,

Ive written a library that has some OpenGL functionality using OpenTK package and all runs fine if using in an application. How ever if I use the embeddinator output into a native app I get the following error...

`
08-16 17:31:09.788 6928-7114/com.pnimedia.droidwrapper E/linker: library "/system/lib/libGLESv2.so" ("/system/lib/libGLESv2.so") needed or dlopened by "/data/app/com.pnimedia.droidwrapper-2/lib/arm64/libmonosgen-2.0.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.pnimedia.droidwrapper-2/lib/arm64:/data/app/com.pnimedia.droidwrapper-2/base.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_dependencies_apk.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_slice_0_apk.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_slice_1_apk.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_slice_2_apk.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_slice_3_apk.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_slice_4_apk.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_slice_5_apk.apk!/lib/arm64-v8a:/data/app/com.pnimedia.droidwrapper-2/split_lib_slice_6_apk.apk!/lib/arm64-v8a:/data/app
`

Any clues to how to fix?

**Comment by jonathanpeppers** [comment]
Hi @equinox2k 

Are you using Xamarin's version of `OpenTK` or `OpenTK-1.0` from the `Add Reference` menu? Or a NuGet package?

Could you post the contents of your AAR file? `zipinfo yourFile.aar` 

If there is an issue here, we probably need to add a test case for OpenTK.

**Comment by equinox2k** [comment]
Currently using OpenTK from nuget.org (V2.0.0) and was added using Visual Studio for Mac

Archive:  PNI.Mobile.Library.aar
Zip file size: 12623501 bytes, number of entries: 83
-rw----     2.0 fat        0 bX defN 17-Aug-16 12:56 META-INF/
-rw----     2.0 fat       69 bl defN 17-Aug-16 12:56 META-INF/MANIFEST.MF
-rw----     2.0 fat     6148 bl defN 17-Aug-16 07:14 .DS_Store
-rw----     2.0 fat      930 bl defN 17-Aug-16 12:56 AndroidManifest.xml
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:31 assets/
-rw----     1.0 fat        0 b- stor 17-Aug-16 12:56 assets/assemblies/
-rw----     2.0 fat    81920 bl defN 17-Aug-16 12:56 assets/assemblies/Java.Interop.dll
-rw----     2.0 fat   436736 bl defN 17-Aug-16 12:56 assets/assemblies/Microsoft.CSharp.dll
-rw----     2.0 fat   164356 bl defN 17-Aug-16 12:56 assets/assemblies/Microsoft.CSharp.pdb
-rw----     2.0 fat   864256 bl defN 17-Aug-16 12:56 assets/assemblies/Mono.Android.dll
-rw----     2.0 fat    69632 bl defN 17-Aug-02 19:41 assets/assemblies/Mono.Android.Export.dll
-rw----     2.0 fat    28908 bl defN 17-Aug-02 19:41 assets/assemblies/Mono.Android.Export.pdb
-rw----     2.0 fat   248960 bl defN 17-Aug-16 12:56 assets/assemblies/Mono.Android.pdb
-rw----     2.0 fat   173056 bl defN 17-Aug-16 12:56 assets/assemblies/Mono.Security.dll
-rw----     2.0 fat    77584 bl defN 17-Aug-16 12:56 assets/assemblies/Mono.Security.pdb
-rw----     2.0 fat  2062848 bl defN 17-Aug-16 12:56 assets/assemblies/mscorlib.dll
-rw----     2.0 fat   855184 bl defN 17-Aug-16 12:56 assets/assemblies/mscorlib.pdb
-rw----     2.0 fat   635904 bl defN 17-Aug-16 12:56 assets/assemblies/Newtonsoft.Json.dll
-rw----     2.0 fat    20480 bl defN 17-Aug-16 12:56 assets/assemblies/OpenTK-1.0.dll
-rw----     2.0 fat     2868 bl defN 17-Aug-16 12:56 assets/assemblies/OpenTK-1.0.pdb
-rw----     2.0 fat   184832 bl defN 17-Aug-16 12:56 assets/assemblies/PNI.Mobile.Library.dll
-rw----     2.0 fat    79788 bl defN 17-Aug-16 12:56 assets/assemblies/PNI.Mobile.Library.pdb
-rw----     2.0 fat     4096 bl defN 17-Aug-16 12:56 assets/assemblies/Resource.designer.dll
-rw----     2.0 fat   989184 bl defN 17-Aug-16 12:56 assets/assemblies/System.Core.dll
-rw----     2.0 fat   390232 bl defN 17-Aug-16 12:56 assets/assemblies/System.Core.pdb
-rw----     2.0 fat   699392 bl defN 17-Aug-16 12:56 assets/assemblies/System.dll
-rw----     2.0 fat    73216 bl defN 17-Aug-16 12:56 assets/assemblies/System.Net.Http.dll
-rw----     2.0 fat    27108 bl defN 17-Aug-16 12:56 assets/assemblies/System.Net.Http.pdb
-rw----     2.0 fat    33280 bl defN 17-Aug-16 12:56 assets/assemblies/System.Numerics.dll
-rw----     2.0 fat    18756 bl defN 17-Aug-16 12:56 assets/assemblies/System.Numerics.pdb
-rw----     2.0 fat   311792 bl defN 17-Aug-16 12:56 assets/assemblies/System.pdb
-rw----     2.0 fat     6144 bl defN 17-Aug-16 12:56 assets/assemblies/System.Runtime.Serialization.dll
-rw----     2.0 fat      964 bl defN 17-Aug-16 12:56 assets/assemblies/System.Runtime.Serialization.pdb
-rw----     2.0 fat   941568 bl defN 17-Aug-16 12:56 assets/assemblies/System.Xml.dll
-rw----     2.0 fat    57344 bl defN 17-Aug-16 12:56 assets/assemblies/System.Xml.Linq.dll
-rw----     2.0 fat    22244 bl defN 17-Aug-16 12:56 assets/assemblies/System.Xml.Linq.pdb
-rw----     2.0 fat   422076 bl defN 17-Aug-16 12:56 assets/assemblies/System.Xml.pdb
-rw----     2.0 fat  1091303 bl defN 17-Aug-16 12:56 classes.jar
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 jni/
-rw----     1.0 fat        0 b- stor 17-Aug-16 12:56 jni/arm64-v8a/
-rw----     2.0 fat   101976 bl defN 17-Aug-16 12:56 jni/arm64-v8a/libjnidispatch.so
-rw----     2.0 fat   153928 bl defN 17-Aug-02 19:40 jni/arm64-v8a/libmonodroid.so
-rw----     2.0 fat  3098600 bl defN 17-Aug-02 19:40 jni/arm64-v8a/libmonosgen-2.0.so
-rw----     2.0 fat   211616 bl defN 17-Aug-16 12:56 jni/arm64-v8a/libPNI.Mobile.Library.so
-rw----     1.0 fat        0 b- stor 17-Aug-16 12:56 jni/armeabi/
-rw----     2.0 fat   102080 bl defN 17-Aug-16 12:56 jni/armeabi/libjnidispatch.so
-rw----     2.0 fat   141048 bl defN 17-Aug-02 19:40 jni/armeabi/libmonodroid.so
-rw----     2.0 fat  3477484 bl defN 17-Aug-02 19:40 jni/armeabi/libmonosgen-2.0.so
-rw----     2.0 fat   228172 bl defN 17-Aug-16 12:56 jni/armeabi/libPNI.Mobile.Library.so
-rw----     1.0 fat        0 b- stor 17-Aug-16 12:56 jni/armeabi-v7a/
-rw----     2.0 fat   101596 bl defN 17-Aug-16 12:56 jni/armeabi-v7a/libjnidispatch.so
-rw----     2.0 fat   124668 bl defN 17-Aug-02 19:40 jni/armeabi-v7a/libmonodroid.so
-rw----     2.0 fat  3432440 bl defN 17-Aug-02 19:40 jni/armeabi-v7a/libmonosgen-2.0.so
-rw----     2.0 fat   228180 bl defN 17-Aug-16 12:56 jni/armeabi-v7a/libPNI.Mobile.Library.so
-rw----     1.0 fat        0 b- stor 17-Aug-16 12:56 jni/x86/
-rw----     2.0 fat    99392 bl defN 17-Aug-16 12:56 jni/x86/libjnidispatch.so
-rw----     2.0 fat   157376 bl defN 17-Aug-02 19:40 jni/x86/libmonodroid.so
-rw----     2.0 fat  3461060 bl defN 17-Aug-02 19:40 jni/x86/libmonosgen-2.0.so
-rw----     2.0 fat   201988 bl defN 17-Aug-16 12:56 jni/x86/libPNI.Mobile.Library.so
-rw----     1.0 fat        0 b- stor 17-Aug-16 12:56 jni/x86_64/
-rw----     2.0 fat    97688 bl defN 17-Aug-16 12:56 jni/x86_64/libjnidispatch.so
-rw----     2.0 fat   154200 bl defN 17-Aug-02 19:41 jni/x86_64/libmonodroid.so
-rw----     2.0 fat  3635672 bl defN 17-Aug-02 19:41 jni/x86_64/libmonosgen-2.0.so
-rw----     2.0 fat   214672 bl defN 17-Aug-16 12:56 jni/x86_64/libPNI.Mobile.Library.so
-rw----     2.0 fat      188 bl defN 17-Aug-16 12:56 R.txt
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/drawable/
-rw----     2.0 fat     2201 bl defN 17-Aug-15 17:21 res/drawable/icon.png
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/layout/
-rw----     2.0 fat      337 bl defN 17-Aug-15 17:21 res/layout/atombuilderlayout.xml
-rw----     2.0 fat      483 bl defN 17-Aug-15 17:21 res/layout/main.xml
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/mipmap-hdpi/
-rw----     2.0 fat     2201 bl defN 17-Aug-15 17:21 res/mipmap-hdpi/icon.png
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/mipmap-mdpi/
-rw----     2.0 fat     1410 bl defN 17-Aug-15 17:21 res/mipmap-mdpi/icon.png
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/mipmap-xhdpi/
-rw----     2.0 fat     3237 bl defN 17-Aug-15 17:21 res/mipmap-xhdpi/icon.png
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/mipmap-xxhdpi/
-rw----     2.0 fat     5414 bl defN 17-Aug-15 17:21 res/mipmap-xxhdpi/icon.png
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/mipmap-xxxhdpi/
-rw----     2.0 fat     7825 bl defN 17-Aug-15 17:21 res/mipmap-xxxhdpi/icon.png
-rw----     1.0 fat        0 b- stor 17-Aug-16 07:11 res/values/
-rw----     2.0 fat       23 bl defN 17-Aug-15 17:21 res/values/strings.xml
83 files, 30530313 bytes uncompressed, 12611627 bytes compressed:  58.7%

**Comment by equinox2k** [comment]
@jonathanpeppers just noticed even tho I have the OpenTK nuget package I also have a reference to OpenTK-1.0 so guess its using that rather than what I originally thought.

**Comment by jonathanpeppers** [comment]
Ok, I will look into this when I have a chance.

You might look and see if the `OpenTK.dll` you are using contains the native library it's looking for:
```
monodis -mresources OpenTK.dll
```

This should dump a `__AndroidNativeLibraries__.zip` file you can see if the missing `so` file is there or not.

When I have time, I'll try to make a test to repro this.

**Comment by equinox2k** [comment]
As mentioned it turns out I'm using OpenTK-1.0 from

/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v2.3/OpenTK-1.0.dll

I did monodis --mresources on it and created extracted zip

library_project_imports contained assets, bin, java, res folders all of which were empty

In my test app I can see gles1 is there however since I'm doing... 

SetEGLContextClientVersion(2);

The version 2 is not there, I guess similar problem would occur if I tried 3

I appreciate your help

**Comment by tritao** [comment]
This is actually looking for a system library `/system/lib/libGLESv2.so`, so it might be some Android permission issue going on.

**Comment by jonathanpeppers** [comment]
Hi @equinox2k I spent some time to try to repro this.

I did something like this in C#:
```csharp
[Register("mono.embeddinator.android.OpenGL")]
public class OpenGL : Java.Lang.Object
{
    [Export("androidGameView")]
    public static View AndroidGameView()
    {
        return new OpenTK.Platform.Android.AndroidGameView(Application.Context);
    }
}
```

Then I can get a Java unit test to pass with:
```java
@Test
public void openGL() {
    Looper.myLooper().prepare();
    View view = OpenGL.androidGameView();
    assertNotNull(view);
}
```

Do you have a small C# example that causes the problem? Thanks.

**Comment by equinox2k** [comment]
I have created a demo app where you can see the error... (sorry its not a small)

Download from [https://www.dropbox.com/s/qw2r61v3c748mk8/PNI.Mobile.XamarinTest.zip?dl=0](https://www.dropbox.com/s/qw2r61v3c748mk8/PNI.Mobile.XamarinTest.zip?dl=0)

Open solution and compile (part of compilation does the embeddinator process and copies result to the droid wrapper folder). If you were to run the solution and look at log cat you will see no errors.

However if you open the Droid wrapper app and run on device you will see error mentioned above.

**Comment by jonathanpeppers** [comment]
@equinox2k I think it worked for me, it is a magenta screen, right?

The Xamarin one had a button first, but the Java one launched the activity immediately.

Here is the full log for Java/Android Studio on x86 emulator, seems like the normal noisy Android log:
```
08-21 19:18:08.290 4259-4259/? I/art: Not late-enabling -Xcheck:jni (already on)
08-21 19:18:08.290 4259-4259/? W/art: Unexpected CPU variant for X86 using defaults: x86
08-21 19:18:08.709 4259-4259/com.pnimedia.droidwrapper W/monodroid: Trying to load sgen from: /data/app/com.pnimedia.droidwrapper-1/lib/x86/libmonosgen-2.0.so
08-21 19:18:08.731 4259-4259/com.pnimedia.droidwrapper W/monodroid-gc: GREF GC Threshold: 46080
08-21 19:18:08.735 4259-4259/com.pnimedia.droidwrapper W/monodroid: Calling into managed runtime init
08-21 19:18:08.993 4259-4259/com.pnimedia.droidwrapper I/InstantRun: starting instant run server: is main process
08-21 19:18:09.030 4259-4259/com.pnimedia.droidwrapper W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-21 19:18:09.296 4259-4259/com.pnimedia.droidwrapper W/art: JNI RegisterNativeMethods: attempt to register 0 native methods for pni.mobile.library.AtomSurfaceView
08-21 19:18:09.390 4259-4259/com.pnimedia.droidwrapper W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
                                                              
                                                              [ 08-21 19:18:09.412  4259: 4277 D/         ]
                                                              HostConnection::get() New Host Connection established 0xa9f293c0, tid 4277
                                                              
                                                              
                                                              [ 08-21 19:18:09.464  4259: 4277 W/         ]
                                                              Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
08-21 19:18:09.467 4259-4277/com.pnimedia.droidwrapper I/OpenGLRenderer: Initialized EGL, version 1.4
08-21 19:18:09.467 4259-4277/com.pnimedia.droidwrapper D/OpenGLRenderer: Swap behavior 1
08-21 19:18:09.467 4259-4277/com.pnimedia.droidwrapper W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
08-21 19:18:09.467 4259-4277/com.pnimedia.droidwrapper D/OpenGLRenderer: Swap behavior 0
                                                                         
                                                                         [ 08-21 19:18:09.467  4259: 4278 D/         ]
                                                                         HostConnection::get() New Host Connection established 0xa9f29f40, tid 4278
08-21 19:18:09.470 4259-4277/com.pnimedia.droidwrapper D/EGL_emulation: eglCreateContext: 0xa9f85060: maj 2 min 0 rcv 2
08-21 19:18:09.471 4259-4277/com.pnimedia.droidwrapper D/EGL_emulation: eglMakeCurrent: 0xa9f85060: ver 2 0 (tinfo 0xa9f83320)
                                                                        
                                                                        [ 08-21 19:18:09.518  4259: 4278 W/         ]
                                                                        Unrecognized GLES max version string in extensions: ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 
08-21 19:18:09.522 4259-4278/com.pnimedia.droidwrapper D/EGL_emulation: eglCreateContext: 0xa9e54840: maj 2 min 0 rcv 2
08-21 19:18:09.566 4259-4278/com.pnimedia.droidwrapper D/EGL_emulation: eglMakeCurrent: 0xa9e54840: ver 2 0 (tinfo 0x98a8ae80)
08-21 19:18:09.568 4259-4278/com.pnimedia.droidwrapper E/libc: Access denied finding property "ro.opengles.version"
08-21 19:18:09.559 4259-4259/com.pnimedia.droidwrapper W/com.pnimedia.droidwrapper: type=1400 audit(0.0:15): avc: denied { read } for comm=474C54687265616420323333 name="u:object_r:opengles_prop:s0" dev="tmpfs" ino=1070 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opengles_prop:s0 tclass=file permissive=0
08-21 19:18:09.630 4259-4277/com.pnimedia.droidwrapper D/EGL_emulation: eglMakeCurrent: 0xa9f85060: ver 2 0 (tinfo 0xa9f83320)
```
