### ISSUE TITLE
[objc] Enable method/property name customization via ExportAttribute

### ISSUE THREAD

**Issue by lemonmojo** [mono/Embeddinator-4000#483]
https://github.com/mono/Embeddinator-4000/pull/482 enables customization of class names surfaced to ObjC by re-using the `[Register]` attribute.
The same would be useful for method and property names. In Xamarin.iOS/Mac we already have `[Export]` which could potentially be re-used for this.

**Comment by chamons** [comment]
Centralizing with https://github.com/mono/Embeddinator-4000/issues/481
