### ISSUE TITLE
[objc] Exception Handling

### ISSUE THREAD

**Issue by lemonmojo** [mono/Embeddinator-4000#484]
I'm currently experimenting with exception handling in E4k because the current implementation is lacking for all but the most basic needs.

I was able to come up with a block (or Swift closure)-based solution that, while not perfect is IMHO a vast improvement over the current implementation. It does require some adjustments on the generator side and some helper code that relies on Xamarin.Mac/iOS.

First, it's required to prevent E4k from handling exceptions by passing `NULL` to the `mono_runtime_invoke` call as the last parameter instead of `&__exception` in https://github.com/mono/Embeddinator-4000/blob/master/objcgen/methodhelper.cs#L108.
The full line then looks like this:
`implementation.WriteLine ($"mono_runtime_invoke ({method}, {instance}, {args}, NULL);");`

Next, we need a wrapper for the `Exception` class that we can expose to the ObjC runtime (You put this somewhere in the library you want to generate bindings for):

```
using System;
using Foundation;

namespace LemonMojo
{
    [Register]
    public class NativeObjCException : NSObject
	{
        internal Exception Exception { get; private set; }

        [Export(nameof(TypeName))]
        public string TypeName
        {
            get {
                return Exception.GetType().Name;
            }
        }

        [Export(nameof(Message))]
        public string Message
        {
            get {
                return Exception.Message;
            }
        }

        [Export(nameof(Source))]
        public string Source
        {
            get {
                return Exception.Source;
            }
        }

        [Export(nameof(StackTrace))]
        public string StackTrace
        {
            get {
                return Exception.StackTrace;
            }
        }

        [Export(nameof(HelpLink))]
        public string HelpLink
        {
            get {
                return Exception.HelpLink;
            }
        }

        [Export(nameof(HResult))]
        public int HResult
        {
            get {
                return Exception.HResult;
            }
        }

        [Export("description")]
        public override string Description
        {
            get {
                return Exception.ToString();
            }
        }

		public NativeObjCException() { }

		internal NativeObjCException(Exception ex)
		{
            Exception = ex;
		}

		public static implicit operator NativeObjCException(Exception ex)
		{
			if (ex == null) {
				return null;
			}

			return new NativeObjCException(ex);
		}

        public static implicit operator NativeObjCException(ObjCException ex)
		{
			if (ex == null) {
				return null;
			}

            return new NativeObjCException(ex.Exception);
		}
	}
}
```

Still on the managed side, we also need a Try/Catch/Finally API that we can expose to the ObjC runtime:

```
using System;
using System.Runtime.InteropServices;

using ObjCRuntime;
using Foundation;

namespace LemonMojo
{
	[Register]
	public class NativeObjCExceptionHandler : NSObject
	{
		#region Try Catch Finally
        // TODO: Need to adjust Embeddinator code to not handle exceptions in methodhelper.cs line 108 (pass NULL to exception parameter)
		
        // TODO: Need to manually adjust binding code (in registrar-x86_64.h) to call this from Swift:
		// +(void) try:(void (^)())tryBlock catch:(void (^)(LemonMojo_NativeObjCException*))catchBlock finally:(void (^)())finallyBlock;
		[Export("try:catch:finally:")]
		public static void TryCatchFinally(
            [BlockProxy(typeof(TryFinallyBlockProxy))] Action tryBlock,
            [BlockProxy(typeof(CatchBlockProxy))] Action<NativeObjCException> catchBlock,
            [BlockProxy(typeof(TryFinallyBlockProxy))] Action finallyBlock)
		{
			try {
				tryBlock();
			} catch (Exception ex) {
                catchBlock?.Invoke(ex);
            } finally {
                finallyBlock?.Invoke();
            }
		}

		private static class BlockHelpers
		{
			private const string LIBOBJC = "/usr/lib/libobjc.dylib";

			[DllImport(LIBOBJC)]
			public static extern IntPtr _Block_copy(IntPtr ptr);

			[DllImport(LIBOBJC)]
			public static extern void _Block_release(IntPtr ptr);
		}

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void TryFinallyBlock(IntPtr block);

		private class TryFinallyBlockProxy
		{
			private IntPtr m_blockPtr;
			private TryFinallyBlock m_invoker;

			[Preserve(Conditional = true)]
			public unsafe TryFinallyBlockProxy(BlockLiteral* block)
			{
				m_blockPtr = BlockHelpers._Block_copy((IntPtr)block);
				m_invoker = block->GetDelegateForBlock<TryFinallyBlock>();
			}

			[Preserve(Conditional = true)]
			~TryFinallyBlockProxy()
			{
				BlockHelpers._Block_release(m_blockPtr);
			}

			[Preserve(Conditional = true)]
			public unsafe static Action Create(IntPtr block)
			{
				return new TryFinallyBlockProxy((BlockLiteral*)block).Invoke;
			}

			[Preserve(Conditional = true)]
			unsafe void Invoke()
			{
				m_invoker(m_blockPtr);
			}
		}

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void CatchBlock(IntPtr block, IntPtr error);

		private class CatchBlockProxy
		{
			private IntPtr m_blockPtr;
			private CatchBlock m_invoker;

			[Preserve(Conditional = true)]
			public unsafe CatchBlockProxy(BlockLiteral* block)
			{
				m_blockPtr = BlockHelpers._Block_copy((IntPtr)block);
				m_invoker = block->GetDelegateForBlock<CatchBlock>();
			}

			[Preserve(Conditional = true)]
			~CatchBlockProxy()
			{
				BlockHelpers._Block_release(m_blockPtr);
			}

			[Preserve(Conditional = true)]
			public unsafe static Action<NativeObjCException> Create(IntPtr block)
			{
				return new CatchBlockProxy((BlockLiteral*)block).Invoke;
			}

			[Preserve(Conditional = true)]
			unsafe void Invoke(NativeObjCException error)
			{
				m_invoker(m_blockPtr, error == null ? IntPtr.Zero : error.Handle);
			}
		}
		#endregion Try Catch Finally
	}

	public class NativeObjCExceptionHandlerTestClass
	{
		public static void CallThisToLogSomethingToTheConsole()
		{
			Console.WriteLine("NO Exception thrown here");
		}

		public static void CallThisToThrowAManagedException()
		{
			throw new Exception("Exception thrown from Mono");
		}
	}
}
```

Now this can be passed to E4k for compilation and the result is almost(!) useable from ObjC or Swift.

Unfortunately, the generator for `NSObject` subclasses in Xamarin.Mac/iOS is not intelligent enough to generate proper signatures for blocks so we need to do some adjustments to the `registrar-x86_64.h` file.

The generated header for the `NativeObjCExceptionHandler` class looks like this:

```
@interface LemonMojo_NativeObjCExceptionHandler : NSObject {
}
	-(void) release;
	-(id) retain;
	-(int) xamarinGetGCHandle;
	-(void) xamarinSetGCHandle: (int) gchandle;
	+(void) try:(id)p0 catch:(id)p1 finally:(id)p2;
	-(BOOL) conformsToProtocol:(void *)p0;
	-(id) init;
@end
```

At least for Swift (haven't try to call it directly from ObjC) the signature for `the try:catch:finally:` selector is not sufficient.
So we need to adjust this line to looks like this:
`+(void) try:(void (^)())tryBlock catch:(void (^)(LemonMojo_NativeObjCException*))catchBlock finally:(void (^)())finallyBlock;`

After this final adjustment we're ready to handle managed exceptions from Swift (ObjC should work equally well). Here's an example:

```
LemonMojo_NativeObjCExceptionHandler.try({
    NSLog("Inside Try, going to call a managed method that DOESN'T throw an exception")
    LemonMojo_NativeObjCExceptionHandlerTestClass.callThisToLogSomethingToTheConsole()
    
    NSLog("Inside Try, going to call a managed method that DOES throw an exception")
    LemonMojo_NativeObjCExceptionHandlerTestClass.callThisToThrowAManagedException()
    
    NSLog("Inside Try, after calling a managed method that throws. We should never end up here!!!")
}, catch: { (ex) in
    NSLog("Inside Catch")
    NSLog("Exception: %@", ex?.description ?? "N/A")
}, finally: {
    NSLog("Inside Finally")
})
```

I think handling exceptions this way is a vast improvement on the existing global exception handler in E4k. It doesn't allow to handle specific types of exceptions but it does allow to use existing managed libraries that throw exceptions as part of their implementation without modifying the managed code just for E4k.

Also, the modifications required to make this work are very moderate. Basically, there would need to be a way to tell E4k to not handle exceptions at all. Additionally, binding code for blocks needs to be adjusted since it just emits `id` parameters instead of proper block signatures.

What do you think? Is this something that could be integrated into E4k? For me, exception handling, along with missing support for events/delegates currently are currently the two most painful limitations of E4k.

Eagerly awaiting feedback!

**Comment by tritao** [comment]
Hey @lemonmojo.

Nice!  This seems like a very interesting approach for exception handling.

Seems like it gets us to a useful point without too much complexity.

@rolfbjarne what do you think?

**Comment by rolfbjarne** [comment]
A simpler implementation would be to:

* Execute mtouch/mmp with `--marshal-managed-exceptions=throwobjectivecexception`
* Change [mono_embeddinator_throw_exception](https://github.com/mono/Embeddinator-4000/blob/a7a3e1b98cb75f0667a40e56241a46c243fe08bd/support/mono_embeddinator.c#L290) to call [xamarin_process_managed_exception](https://github.com/xamarin/xamarin-macios/blob/fbe5a6c510b33f205200bc3ed6461e0e7a02d36d/runtime/runtime.m#L2075)

And that will convert all managed exceptions into Objective-C exceptions, and you can catch them using Objective-C exception handling (I have no idea how that ends up in Swift though, but I assume it's possible to catch Objectice-C exceptions from Swift).

**Comment by lemonmojo** [comment]
@rolfbjarne There's currently no native Swift exception handling support and Swift 4 won't change that. There are workarounds that use blocks/closures to wrap Objective-C exceptions to NSErrors like [this](https://github.com/Weebly/Try) or [that](https://stackoverflow.com/questions/32758811/catching-nsexception-in-swift). So assuming your suggestion works, Swift users would have to go the extra mile of using one of those wrappers. Anything is better than a global exception handler though. ;)

**Comment by lemonmojo** [comment]
@tritao Any news about exception handling in Embeddinator?

**Comment by chamons** [comment]
So it sounds like @rolfbjarne 's approach would be a reasonable feature request. There isn't any current news as no one has worked at implementing it yet.

**Comment by equinox2k** [comment]
@rolfbjarne ive implemented your feedback and seems to work great, I've created the pull request...

https://github.com/mono/Embeddinator-4000/pull/629

**Comment by chamons** [comment]
🎉 https://github.com/mono/Embeddinator-4000/pull/629 is in. 

This should be fixed in master now, please test and reopen if you run into issues.
