### ISSUE TITLE
C Tests don't pass on Mono 4.8.0

### ISSUE THREAD

**Issue by realvictorprm** [mono/Embeddinator-4000#493]
Hello,

the C-Tests didn't pass on my windows machine with Mono version 4.8.0 installed.
Updating to the latest stable mono version for windows solved my problem.

### Additional Information:
```
Mono JIT compiler version 4.8.0 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  x86
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

The generated managed.c file:
[managed.zip](https://github.com/mono/Embeddinator-4000/files/1256767/managed.zip)

This is just for tracking possible incompatibility with "old" Mono versions.

**Comment by tritao** [comment]
Closing, we're not supporting these old Mono versions, just upgrade to latest ones.

**Comment by realvictorprm** [comment]
Thanks, it's fine as long as we know now that it definitely isn't supported.
