### ISSUE TITLE
Travis CI unbelievable slow

### ISSUE THREAD

**Issue by realvictorprm** [mono/Embeddinator-4000#498]
Hello fellows,

sorry for posting this but the Travis CI takes way too much time for waking up and for running the tests.
Is there _anything_ we can do about this?

**Comment by tritao** [comment]
It's the macOS builds that take up too much time... We could add Linux builds to it which should give us much faster results.

**Comment by realvictorprm** [comment]
Linking relevant PR #499.

Thanks @tritao for doing this!

**Comment by tritao** [comment]
We now have Linux CI, builds take ~3 minutes and start right away.

So now its possible to have fast feedback, but unfortunately macOS CI builds are now taking longer than ever. I'll need to investigate a solution to it in the future.
