### ISSUE TITLE
Linux support? 

### ISSUE THREAD

**Issue by MihaMarkic** [mono/Embeddinator-4000#5]
I don't see explicit Linux support, the closest is Android.
So,what's the state of Linux platform?

**Comment by tritao** [comment]
Not supported as of yet,.

Should not be too hard, just a matter of testing and adding explicit support for GCC as a compiler.

The current Clang compilation code might already work with some small fixes.

If you want to help I can guide you through it, if not, I hope to at least add initial support for it in the next few weeks.

**Comment by MihaMarkic** [comment]
I would like to help but my Linux gcc experience (and C level in general) isn't much to brag about it.
We might try and give up if it wouldn't go anywhere.

**Comment by bt-003** [comment]
Tritao - 
I'd like to help, though very new at this. I've had experience with GCC (and some C). Any guidance would be greatly appreciated.

**Comment by tritao** [comment]
Great to hear. Were you able to successfully compile the project in Linux?

**Comment by bt-003** [comment]
No, haven't attempted yet. Let me work on it in the next day or two - I'll keep you posted.

**Comment by bt-003** [comment]
Still working on compiling in Linux.
Attempted to compile in the *support* file. Received error message "unable
to locate mono/jit/jit.h". This was resolved by redirecting paths in
various .h files.
Now, receiving many undefined references from
mono_embeddinator.c:mono_m2n_init function.  I'll have to investigate where
the references are located, and
redirect to their location.

**Comment by tritao** [comment]
Not sure about the redirecting of paths. What did you do?

I think you need to change the code in `Compilation.cs` to: 1) invoke pkg-config to get the correct Mono paths on the system and 2) pass those include and library paths to the system compiler.

**Comment by bt-003** [comment]
Ok, let me try that. Thanks for your patience.

**Comment by realvictorprm** [comment]
@bt-003 What's the state of this?

**Comment by bt-003** [comment]
I'm still in the trial stage of finding a solution. I'll let you know in 1wk if still unable to compile.

**Comment by realvictorprm** [comment]
If there are any problems just tell them us :)

**Comment by bt-003** [comment]
Thanks, I really appreciate it. This type of formatting / compiling is new
for me. Rather than invoking pkg-config to get correct Mono paths and
passing to the system compiler,  I'm used to compiling by creating object
files (from .c files) in order to compile/make.
I've also completed an app to Google Summer of Code, so can devote more
time to this.

**Comment by tritao** [comment]
Done
