### ISSUE TITLE
Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified

### ISSUE THREAD

**Issue by emysa341** [mono/Embeddinator-4000#501]
Hello, I have integrated Embeddinator-4000 for android class library project.
1) Mono 5.0 installed
2) Xamarin.Android 7.4.99 or later (build from Jenkins) installed
3) Java version 1.8
4) Post build command line
5) My working environment is Visual studio 2017 in windows.
```
set E4K_OUTPUT="$(SolutionDir)output"
if exist %E4K_OUTPUT% rmdir /S /Q %E4K_OUTPUT%
"$(SolutionDir)packages\embeddinator-4000\0.2.0.79\tools\Embeddinator-4000.exe" "$(TargetPath)" --target=shared --gen=Java --platform=Android --outdir=%E4K_OUTPUT% -c -v
```

I have no clue, how to get rid of following exception, please save my day

```
 Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
1>     at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>     at System.Diagnostics.Process.Start()
1>     at MonoEmbeddinator4000.Helpers.Invoke(String program, String arguments, Dictionary`2 envVars)
1>     at MonoEmbeddinator4000.Driver.MSBuild(String project)
1>     at MonoEmbeddinator4000.Driver.WriteFiles()
1>     at MonoEmbeddinator4000.Driver.Run()
1>     at MonoEmbeddinator4000.CLI.Main(String[] args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5019,5): error MSB3073: The command "set E4K_OUTPUT="C:\Users\khan\source\repos\TestAndroidSolution\output"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5019,5): error MSB3073: if exist %E4K_OUTPUT% rmdir /S /Q %E4K_OUTPUT%
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5019,5): error MSB3073: "C:\Users\khan\source\repos\TestAndroidSolution\packages\Embeddinator-4000.0.2.0.80\tools\Embeddinator-4000.exe" "C:\Users\khan\source\repos\TestAndroidSolution\TestAndroid\bin\Debug\TestAndroid.dll" --gen=Java --platform=Android --outdir=%E4K_OUTPUT% -c -v" exited with code -532462766.

```

**Comment by jonathanpeppers** [comment]
Hi @emysa341,

It looks like it is not finding MSBuild, can you add the appropriate directory on your machine to your PATH:

`[ProgramFiles]/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin`

I fixed this on master a few weeks ago, but I don't think there is a release on NuGet for that yet. You could also try building Embeddinator on master and using that.

**Comment by emysa341** [comment]
Hi @jonathanpeppers,

The file is already there [ProgramFiles]/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin. But still same issue. I have also downloaded the project from Master branch. Still there are process starting errors. I have tried resolving 2 or more errors. But one leads to another

C:\\hello-from-csharp\output\GenerateJavaStubs.proj(10,3): 
error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\lib\xbuild\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by jonathanpeppers** [comment]
@emysa341 you didn't mention if `MSBuild.exe` is in your `PATH` environment variable or not.

To check this, open Command Prompt and run:
```
msbuild /version
```
It should print 15.3 if you have the latest Visual Studio 2017. [Here](https://www.java.com/en/download/help/path.xml) is an example of setting environment variables in Windows. I think you  just need to add `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin` in your case (put it in front). You will also need to restart your command prompt to test it.

On your new issue, I don't think you actually _need_ to install a master build of Xamarin.Android anymore. So do the following:

1. Uninstall Xamarin (if you followed one of the options [here](https://github.com/xamarin/xamarin-android/blob/master/Documentation/UsingJenkinsBuildArtifacts.md))
2. Reinstall Xamarin (to just get stable version)
3. If you are using Embeddinator from NuGet, it has an `external/Xamarin.Android` directory that contains a minimal install of Xamarin.Android for Embeddinator. It will use this without you doing anything.
4. If you want to use Embeddinator from source, the build script will download a copy of Xamarin.Android to `external/Xamarin.Android`. It will use this without you doing anything.

Hope this helps,

**Comment by emysa341** [comment]
@jonathanpeppers Thank you for the detailed explanation, I followed the steps you mentioned. The issue is resolved. Thanks again.
