### ISSUE TITLE
Logic for custom dll search paths is ugly

### ISSUE THREAD

**Issue by realvictorprm** [mono/Embeddinator-4000#502]
Hello fellows,

the default dll search system didn't work for my case and so I was pushed to set the search path on my own. However the custom search path method doesn't contain any information about how multiple paths could be used. Therefor I suggest to either remove [this](https://github.com/mono/Embeddinator-4000/blob/master/support/mono_embeddinator.c#L109) line to keep the default search paths for the mono runtime and use the custom search path only for the internal assembly search of Embeddinator or to add an additional method which allows adding more search paths. Obviously the 1th option is the easiest because it requires only a single line remove. But this needs to be discussed..

cc @tritao

**Comment by realvictorprm** [comment]
Btw, the 1th Option solved the problems I had. I really see no point in removing the standard directories. It's already difficult enough to retrieve such information in C/C++ cross-platform.

Also my thinking of the search path was that it only affects _Embeddinator_ and not the Mono CLR.

**Comment by jonathanpeppers** [comment]
@realvictorprm it would probably be helpful to mention the platform and some details about your problem (maybe you put it somewhere else). Like `I am on Windows and it tried to load X assembly from Y directory`.

Removing that line in `mono_embeddinator.c`, looks like it would break Java on desktop platforms: https://github.com/mono/Embeddinator-4000/blob/master/support/java/DesktopImpl.java

There might be something wrong here that needs fixed, we just need to make sure we test Obj-C, and Java on OS X and Windows.

**Comment by realvictorprm** [comment]
Thanks @jonathanpeppers, I agree. Yes I'm working on windows, Embeddinator or rather the CLR failed to load the base assemblies (in this case mscorelib.dll!). So far I understood the single line is changing the global search path of the CLR which results here in worse failures.

**Comment by realvictorprm** [comment]
Also, according my description above the line change should only _fix_ the bug but keeps the logic for Embeddinator.

**Comment by tritao** [comment]
I haven't taken action on the PR yet because I'd first like to understand the issue first. Lets discuss your original problem and then figure out what to do.

**Comment by realvictorprm** [comment]
fixed and closed via #503
