### ISSUE TITLE
Check if Mono SDK is not installed and improve path lookup

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#505]
When I use the e4k nuget package in vs2017, I am getting the following error:

```
In file included from F:\git\PV\library\HS\output\mono_embeddinator.h:32:0,
                   from F:\git\PV\library\HS\output\HIALibAndroid.h:10,
                   from F:\git\PV\library\HS\output\HIALibAndroid.c:7:
  F:\git\PV\library\HS\output\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
   #include <mono/jit/jit.h>
                            ^
  compilation terminated.
```

I saw a separate issue with this error, related to iOS. I attempted to run e4k from source but ran into the following error:

```
Unhandled Exception: System.IO.FileNotFoundException: Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in F:\git\e4k\Embeddinator-4000\external\ikvm\reflect\Universe.cs:line 756
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRefImpl(Record& rec) in F:\git\e4k\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 594
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRef(Int32 index) in F:\git\e4k\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 577
   at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context) in F:\git\e4k\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 460
   at IKVM.Reflection.Reader.TypeDefImpl.get_BaseType() in F:\git\e4k\Embeddinator-4000\external\ikvm\reflect\Reader\TypeDefImpl.cs:line 59
   at IKVM.Reflection.Type.get_IsEnum() in F:\git\e4k\Embeddinator-4000\external\ikvm\reflect\Type.cs:line 1335
   at Embeddinator.Generators.ASTGenerator.Visit(TypeInfo typeInfo) in F:\git\e4k\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 105
   at Embeddinator.Generators.ASTGenerator.Visit(Assembly assembly) in F:\git\e4k\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 68
   at Embeddinator.Driver.Process() in F:\git\e4k\Embeddinator-4000\binder\Driver.cs:line 80
   at Embeddinator.Driver.Run() in F:\git\e4k\Embeddinator-4000\binder\Driver.cs:line 236
   at Embeddinator.CLI.Main(String[] args) in F:\git\e4k\Embeddinator-4000\binder\CLI.cs:line 215
```

Any thing I can try to get this to work?

**Comment by tritao** [comment]
Could you try using the version from master? There's a bunch of Windows fixes that are not in the Nuget yet.

And please post the command line arguments when posting these errors so we can have an idea which modes you're trying to use.

Can you explain the second error, I didn't understand if it's related to iOS or Android, and on which platforms. Is this still on Windows?

**Comment by Zomb** [comment]
These are the steps I followed for the second error:

1. Cloned master and sub-modules with 
`git clone https://github.com/mono/Embeddinator-4000.git --recursive`
2. Opened the solution in VS2017 and built the Embeddinator-4000 project
3. From the debug directory ran the following command:
`Embeddinator-4000.exe f:\git\pv\library\HS\HIALib.Android\bin\Debug\HIALibAndroid.dll --gen=Java --platform=Android --outdir=generated -c`

Hope this makes it a little clearer!

**Comment by tritao** [comment]
I see.

Can you try running `./build.ps1 -t Download-Xamarin-Android` from Powershell?

**Comment by Zomb** [comment]
New steps:

1. Fresh Clone of the repository
2. Ran the command above in PowerShell
3. Open solution in VS2017 and build
4. Running the command above in both PowerShell and CMD resulted in the same exception

```
F:\git\e4k2\Embeddinator-4000>build\lib\Debug\Embeddinator-4000.exe f:\git\pv\library\HS\HIALib.Android\bin\Debug\HIALibAndroid.dll --gen=Java --platform=Android --outdir=generated -c
Parsing assemblies...
    Parsed 'HIALibAndroid.dll'
Processing assemblies...

Unhandled Exception: System.IO.FileNotFoundException: Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
   at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in F:\git\e4k2\Embeddinator-4000\external\ikvm\reflect\Universe.cs:line 756
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRefImpl(Record& rec) in F:\git\e4k2\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 594
   at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRef(Int32 index) in F:\git\e4k2\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 577
   at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context) in F:\git\e4k2\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 460
   at IKVM.Reflection.Reader.TypeDefImpl.get_BaseType() in F:\git\e4k2\Embeddinator-4000\external\ikvm\reflect\Reader\TypeDefImpl.cs:line 59
   at IKVM.Reflection.Type.get_IsEnum() in F:\git\e4k2\Embeddinator-4000\external\ikvm\reflect\Type.cs:line 1335
   at Embeddinator.Generators.ASTGenerator.Visit(TypeInfo typeInfo) in F:\git\e4k2\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 105
   at Embeddinator.Generators.ASTGenerator.Visit(Assembly assembly) in F:\git\e4k2\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 68
   at Embeddinator.Driver.Process() in F:\git\e4k2\Embeddinator-4000\binder\Driver.cs:line 80
   at Embeddinator.Driver.Run() in F:\git\e4k2\Embeddinator-4000\binder\Driver.cs:line 236
   at Embeddinator.CLI.Main(String[] args) in F:\git\e4k2\Embeddinator-4000\binder\CLI.cs:line 215
```

**Comment by tritao** [comment]
Hmm, do you have Xamarin.Android installed on your VS 2017 instance?

**Comment by tritao** [comment]
If you have this under VS, then it would be nice if you can help debug the issue.

We setup the `Mono.Android.dll` directory to the parser here: https://github.com/mono/Embeddinator-4000/blob/master/binder/Driver.cs#L62

Can you put a breakpoint in there and try to check the values returned by `XamarinAndroid.TargetFrameworkDirectories`?

**Comment by Zomb** [comment]
I see a couple of things that appear to be happening:

1. In e4k external I don't have a Xamarin.Android, so the very first check fails.

2. Next in GetMonoDroidPath we check for the lib folder:
```
if (File.Exists(Combine(binPath, "lib")))
                return GetFullPath(MonoDroidSdk.BinPath);
```
This check always fails, because its checking for a File, but lib is a directory.

3. The Path from here is used to create targetFrameworks, which is looking for a folder called "xbuild-frameworks" which I can't find anywhere in my Xamarin install. 

These are the versions of Xamarin and its components I have installed:

> Xamarin   4.6.0.299 (b63523e27)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android SDK   7.4.0.21 (2851083)
> Xamarin.Android Reference Assemblies and MSBuild support.
> 
> Xamarin.iOS and Xamarin.Mac SDK   10.12.0.20 (80b8487)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by Zomb** [comment]
FWIW, here is the output when I use the 0.3.0 nuget package.

> "F:\git\PV\library\HS\packages\Embeddinator-4000.0.3.0\tools\Embeddinator-4000.exe" "F:\git\PV\library\HS\HIALib.Android\bin\Debug\HIALibAndroid.dll" --gen=Java --platform=Android --outdir=%E4K_OUTPUT% -c
> 1>  Parsing assemblies...
> 1>      Parsed 'HIALibAndroid.dll'
> 1>  Processing assemblies...
> 1>  Generating binding code...
> 1>      Generated: HIALibAndroid.h
> 1>      Generated: HIALibAndroid.c
> 1>      Generated: Mono.Android.h
> 1>      Generated: Mono.Android.c
> 1>      Generated: Java.Interop.h
> 1>      Generated: Java.Interop.c
> 1>      Generated: mscorlib.h
> 1>      Generated: mscorlib.c
> 1>      Generated: c-support.c
> 1>      Generated: c-support.h
> 1>      Generated: embeddinator.h
> 1>      Generated: glib.c
> 1>      Generated: glib.h
> 1>      Generated: mono-support.c
> 1>      Generated: mono-support.h
> 1>      Generated: mono_embeddinator.c
> 1>      Generated: mono_embeddinator.h
> 1>  Compiling binding code...
> 1>          In file included from F:\git\PV\library\HS\output\mono_embeddinator.h:32:0,
> 1>                   from F:\git\PV\library\HS\output\HIALibAndroid.h:10,
> 1>                   from F:\git\PV\library\HS\output\HIALibAndroid.c:7:
> 1>  F:\git\PV\library\HS\output\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
> 1>   #include <mono/jit/jit.h>
> 1>                            ^
> 1>  compilation terminated.

**Comment by tritao** [comment]
Can you paste the output with `-verbose` flag?

**Comment by Zomb** [comment]
> 1>  "F:\git\PV\library\HS\packages\Embeddinator-4000.0.3.0\tools\Embeddinator-4000.exe" "F:\git\PV\library\HS\HIALib.Android\bin\Debug\HIALibAndroid.dll" --gen=Java --platform=Android --outdir=%E4K_OUTPUT% -c -verbose
> 1>  Parsing assemblies...
> 1>        Key HKCU\SOFTWARE\Novell\Mono for Android\AndroidSdkDirectory found:
> 1>      Path contains adb in \platform-tools (F:\Android).
> 1>        Key HKCU\SOFTWARE\Novell\Mono for Android\AndroidNdkDirectory found:
> 1>      Path contains ndk-stack in \. (C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r10e\).
> 1>        Key HKCU\SOFTWARE\Novell\Mono for Android\JavaSdkDirectory found:
> 1>      Path contains jarsigner.exe in \bin (C:\Program Files\Java\jdk1.8.0_112).
> 1>      Found Android SDK. API levels: 21
> 1>      Parsed 'HIALibAndroid.dll'
> 1>  Processing assemblies...
> 1>      Pass 'Embeddinator.CheckReservedKeywords'
> 1>      Pass 'Embeddinator.Passes.GenerateObjectTypesPass'
> 1>      Pass 'Embeddinator.Passes.GenerateArrayTypes'
> 1>      Pass 'CppSharp.Passes.CheckIgnoredDeclsPass'
> 1>          Function 'new' was ignored due to ignored return decl
> 1>          Function 'CreateHearAidController' was ignored due to ignored param
> 1>          Function 'new' was ignored due to ignored return decl
> 1>          Function 'Java.Interop.IJavaObjectEx.get_KeyHandle' was ignored due to ignored return decl
> 1>          Function 'Java.Interop.IJavaObjectEx.set_KeyHandle' was ignored due to ignored param
> 1>          Function 'Java.Interop.IJavaObjectEx.set_IsProxy' was ignored due to ignored param
> 1>          Function 'Java.Interop.IJavaObjectEx.set_NeedsActivation' was ignored due to ignored param
> 1>          Function 'Java.Interop.IJavaObjectEx.ToLocalJniHandle' was ignored due to ignored return decl
> 1>          Function 'get_PeerReference' was ignored due to ignored return decl
> 1>          Function 'get_JniPeerMembers' was ignored due to ignored return decl
> 1>          Function 'get_Handle' was ignored due to ignored return decl
> 1>          Function 'Java.Interop.IJavaPeerable.get_JniManagedPeerState' was ignored due to ignored return decl
> 1>          Function 'Java.Interop.IJavaPeerable.SetJniIdentityHashCode' was ignored due to ignored param
> 1>          Function 'Java.Interop.IJavaPeerable.SetJniManagedPeerState' was ignored due to ignored param
> 1>          Function 'Java.Interop.IJavaPeerable.SetPeerReference' was ignored due to ignored param
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Implicit' was ignored due to ignored return decl
> 1>          Function 'op_Explicit' was ignored due to ignored return decl
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'op_Explicit' was ignored due to ignored param
> 1>          Function 'get_Class' was ignored due to ignored return decl
> 1>          Function 'Equals' was ignored due to ignored param
> 1>          Function 'Wait' was ignored due to ignored param
> 1>          Function 'Wait' was ignored due to ignored param
> 1>          Function 'get_Handle' was ignored due to ignored return decl
> 1>          Property 'Handle' was ignored due to ignored decl
> 1>          Function 'get_KeyHandle' was ignored due to ignored return decl
> 1>          Function 'set_KeyHandle' was ignored due to ignored param
> 1>          Function 'set_IsProxy' was ignored due to ignored param
> 1>          Function 'set_NeedsActivation' was ignored due to ignored param
> 1>          Function 'ToLocalJniHandle' was ignored due to ignored return decl
> 1>          Property 'KeyHandle' was ignored due to ignored decl
> 1>          Property 'IsProxy' was ignored due to ignored decl
> 1>          Property 'NeedsActivation' was ignored due to ignored decl
> 1>          Function 'SetJniIdentityHashCode' was ignored due to ignored param
> 1>          Function 'get_PeerReference' was ignored due to ignored return decl
> 1>          Function 'SetPeerReference' was ignored due to ignored param
> 1>          Function 'get_JniPeerMembers' was ignored due to ignored return decl
> 1>          Function 'get_JniManagedPeerState' was ignored due to ignored return decl
> 1>          Function 'SetJniManagedPeerState' was ignored due to ignored param
> 1>          Property 'JniIdentityHashCode' was ignored due to ignored decl
> 1>          Property 'PeerReference' was ignored due to ignored decl
> 1>          Property 'JniPeerMembers' was ignored due to ignored decl
> 1>          Property 'JniManagedPeerState' was ignored due to ignored decl
> 1>          Property 'Java.Interop.IJavaObjectEx.KeyHandle' was ignored due to ignored decl
> 1>          Property 'Java.Interop.IJavaObjectEx.IsProxy' was ignored due to ignored decl
> 1>          Property 'Java.Interop.IJavaObjectEx.NeedsActivation' was ignored due to ignored decl
> 1>          Property 'JniIdentityHashCode' was ignored due to ignored decl
> 1>          Property 'PeerReference' was ignored due to ignored decl
> 1>          Property 'JniPeerMembers' was ignored due to ignored decl
> 1>          Property 'Handle' was ignored due to ignored decl
> 1>          Property 'ThresholdClass' was ignored due to ignored decl
> 1>          Property 'ThresholdType' was ignored due to ignored decl
> 1>          Property 'Java.Interop.IJavaPeerable.JniManagedPeerState' was ignored due to ignored decl
> 1>          Property 'class_ref' was ignored due to ignored decl
> 1>          Property 'Class' was ignored due to ignored decl
> 1>      Pass 'Embeddinator.Passes.RenameDuplicatedDeclsPass'
> 1>          Renamed method Java_Lang_Object_op_Implicit_1
> 1>          Renamed method Java_Lang_Object_op_Implicit_2
> 1>          Renamed method Java_Lang_Object_op_Implicit_3
> 1>          Renamed method Java_Lang_Object_op_Implicit_4
> 1>          Renamed method Java_Lang_Object_op_Implicit_5
> 1>          Renamed method Java_Lang_Object_op_Implicit_6
> 1>          Renamed method Java_Lang_Object_op_Implicit_7
> 1>          Renamed method Java_Lang_Object_op_Implicit_8
> 1>          Renamed method Java_Lang_Object_op_Implicit_9
> 1>          Renamed method Java_Lang_Object_op_Implicit_10
> 1>          Renamed method Java_Lang_Object_op_Implicit_11
> 1>          Renamed method Java_Lang_Object_op_Implicit_12
> 1>          Renamed method Java_Lang_Object_op_Implicit_13
> 1>          Renamed method Java_Lang_Object_op_Implicit_14
> 1>          Renamed method Java_Lang_Object_op_Implicit_15
> 1>          Renamed method Java_Lang_Object_op_Implicit_16
> 1>          Renamed method Java_Lang_Object_op_Explicit_1
> 1>          Renamed method Java_Lang_Object_op_Explicit_2
> 1>          Renamed method Java_Lang_Object_op_Explicit_3
> 1>          Renamed method Java_Lang_Object_op_Explicit_4
> 1>          Renamed method Java_Lang_Object_op_Explicit_5
> 1>          Renamed method Java_Lang_Object_op_Explicit_6
> 1>          Renamed method Java_Lang_Object_op_Explicit_7
> 1>          Renamed method Java_Lang_Object_op_Explicit_8
> 1>          Renamed method Java_Lang_Object_op_Explicit_9
> 1>          Renamed method Java_Lang_Object_op_Explicit_10
> 1>          Renamed method Java_Lang_Object_op_Explicit_11
> 1>          Renamed method Java_Lang_Object_op_Explicit_12
> 1>          Renamed method Java_Lang_Object_op_Explicit_13
> 1>          Renamed method Java_Lang_Object_op_Explicit_14
> 1>          Renamed method Java_Lang_Object_op_Explicit_15
> 1>          Renamed method Java_Lang_Object_op_Explicit_16
> 1>          Renamed method Java_Lang_Object_Wait_1
> 1>          Renamed method Java_Lang_Object_Wait_2
> 1>      Pass 'CppSharp.Passes.CheckDuplicatedNamesPass'
> 1>      Pass 'Embeddinator.Passes.FieldToGetterSetterPropertyPass'
> 1>          Getter/setter property created from field HIALibAndroid_String_ApplicationName
> 1>          Getter/setter property created from field HIALibAndroid_String_Hello
> 1>      Pass 'Embeddinator.Passes.FixMethodParametersPass'
> 1>      Pass 'Embeddinator.CheckReservedKeywords'
> 1>  Generating binding code...
> 1>      Generated: HIALibAndroid.h
> 1>      Generated: HIALibAndroid.c
> 1>      Generated: Mono.Android.h
> 1>      Generated: Mono.Android.c
> 1>      Generated: Java.Interop.h
> 1>      Generated: Java.Interop.c
> 1>      Generated: mscorlib.h
> 1>      Generated: mscorlib.c
> 1>      Generated: c-support.c
> 1>      Generated: c-support.h
> 1>      Generated: embeddinator.h
> 1>      Generated: glib.c
> 1>      Generated: glib.h
> 1>      Generated: mono-support.c
> 1>      Generated: mono-support.h
> 1>      Generated: mono_embeddinator.c
> 1>      Generated: mono_embeddinator.h
> 1>  Compiling binding code...
> 1>      Invoking: C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r10e\toolchains\arm-linux-androideabi-4.8\prebuilt\windows\bin\arm-linux-androideabi-gcc.exe --sysroot="C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r10e\platforms\android-21\arch-arm" -fdiagnostics-color -DMONO_EMBEDDINATOR_DLL_EXPORT -I"C:\Program Files (x86)\Mono\include\mono-2.0" -L"F:\git\PV\library\HS\packages\Embeddinator-4000.0.3.0\external\Xamarin.Android\lib\xbuild\Xamarin\Android\lib\armeabi" -lmonosgen-2.0 -lmono-android.release F:\git\PV\library\HS\output\HIALibAndroid.c F:\git\PV\library\HS\output\Mono.Android.c F:\git\PV\library\HS\output\Java.Interop.c F:\git\PV\library\HS\output\mscorlib.c F:\git\PV\library\HS\output\c-support.c F:\git\PV\library\HS\output\glib.c F:\git\PV\library\HS\output\mono-support.c F:\git\PV\library\HS\output\mono_embeddinator.c --std=c99 -shared -o F:\git\PV\library\HS\output\android\jni\armeabi\libHIALibAndroid.so
> 1>          In file included from F:\git\PV\library\HS\output\mono_embeddinator.h:32:0,
> 1>                   from F:\git\PV\library\HS\output\HIALibAndroid.h:10,
> 1>                   from F:\git\PV\library\HS\output\HIALibAndroid.c:7:
> 1>  F:\git\PV\library\HS\output\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
> 1>   #include <mono/jit/jit.h>
> 1>                            ^
> 1>  compilation terminated.

**Comment by tritao** [comment]
Do you have this folder `C:\Program Files (x86)\Mono\include\mono-2.0`?

If not, you might need to install the Mono SDK for Windows

**Comment by Zomb** [comment]
I don't have it, I assume I have to install the 32-bit version?

**Comment by jonathanpeppers** [comment]
Yeah 32 bit, I tried to see if there was a way to get by without installing Mono, but Xamarin.Android doesn't ship the Mono headers (b/c they don't need them).

**Comment by Zomb** [comment]
Yup, that fixed it! Could we add it to the documentation perhaps? Thank you!

**Comment by jonathanpeppers** [comment]
It does say it at the top here: https://mono.github.io/Embeddinator-4000/getting-started-java

But there isn't anything saying: if you get error X do Y.

Maybe a _Troubleshooting Guide_ is in order?

**Comment by Zomb** [comment]
Maybe! I tend to assume mono components are the same as Xamarin, which I really should not be doing, especially when you called out Xamarin.Android later on the page.

**Comment by tritao** [comment]
I'll improve this in the driver next week so we issue a proper error for this

**Comment by tritao** [comment]
Will be fixed with https://github.com/mono/Embeddinator-4000/pull/506
