### ISSUE TITLE
[objc] Enable "-sim" builds to not force symbols to be undefined

### ISSUE THREAD

**Issue by zgramana** [mono/Embeddinator-4000#521]
## Scenario
I have a static fat lib linked against a Xamarin.iOS managed lib. Run `objcgen` against it.

## Observed
`objcgen` successfully outputs a `.framework` linked against the `iPhoneOS` SDK. Fails to build a `.framework` against `iPhoneSimulator` on the final link step when it forces external symbols to be undefined (not done during the `iPhoneOS` final link step).

## Expected
`objcgen` to successfully output frameworks for both SDK's.

## Notes
This seems like nominally an issue with `mtouch`, as [the `mtouch` arguments passed in](https://github.com/mono/Embeddinator-4000/blob/d372f3e0af24569fcffae195c9fa8da841328393/objcgen/driver.cs#L798) by `objcgen` are nearly identical in both cases. I notice in [these](https://github.com/xamarin/xamarin-macios/commit/2d104f32d9f9f33a37dc0a310af15f8a6e56a5dc) [commits](https://github.com/xamarin/xamarin-macios/commit/d17cb6556a4cb4ae9fec59e5687518f4ac3dc460#diff-656045af32acf6dda51d8e5dd079d5e2R547) that whether or not `mtouch` passes `-u symbol` for symbols referenced in P/Invoke calls can be determined indirectly of the parameters pass to `mtouch`.

I'm hoping that there is a perhaps one or more arguments to be passed to `mtouch` to suppress this for `iPhoneSimulator` builds as well (at least until #520 is resolved).

**Comment by rolfbjarne** [comment]
I think you're right, this can be solved with adding an argument somewhere.

But first I'd need to fully understand what's happening, and for that I'd need at least a complete build log, and if possible also a test project.

**Comment by dalexsoto** [comment]
Hello @zgramana, we have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
