### ISSUE TITLE
FeatureRequest: Native side call back on UnhandledException

### ISSUE THREAD

**Issue by equinox2k** [mono/Embeddinator-4000#522]
Was thinking would be good to have a feature where on Native side when a UnhandledException C# Exception occurs you can invoke a native side callback. 

Thus you can integrate error logging easily with existing apps such as Crashlytics

**Comment by tritao** [comment]
Good idea, I'll take a look into adding this.

**Comment by equinox2k** [comment]
@tritao that would be great. Without it, its a blocker for us deploying application as currently unable to see user crashes.

**Comment by equinox2k** [comment]
@tritao any updates on this as planning to go to production soon on one of our apps.

**Comment by tritao** [comment]
Hey, I've started working on this feature.

**Comment by lemonmojo** [comment]
@tritao Any news on this?

**Comment by chamons** [comment]
I believe this was completed with: https://github.com/mono/Embeddinator-4000/issues/484 and not closed.

Please re-open if that does not cover this use case.
