### ISSUE TITLE
Powershell script failing when building from source

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#524]
I am using the ./build.ps1 script to build e4k from source. Its currently failing on clean build, with the error

> Could not find Cake.exe at F:\temp\Embeddinator-4000\.cake\Cake\Cake.exe
> At F:\temp\Embeddinator-4000\build.ps1:184 char:5
> +     Throw "Could not find Cake.exe at $CAKE_EXE"
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Could not find ...e\Cake\Cake.exe:String) [], RuntimeException
>     + FullyQualifiedErrorId : Could not find Cake.exe at F:\temp\Embeddinator-4000\.cake\Cake\Cake.exe
> 

I believe the issue is because the cake nuget package in .cake is set to 'Cake.0.22.0-alpha0095' which doesn't appear to exist any more. I updated this to 0.23.0 and was able to proceed, with the download. I would submit this as a pull request except that once the whole download is complete, it looks like its trying to build and crashing, with the command window closing so fast that I can't actually tell what's wrong, so I am not sure if there are separate issues with 0.23.0 cake package.

**Comment by tritao** [comment]
Can you try building it from a command line to check see the build output?

I've issued a new build on our Windows CI bot meanwhile.

**Comment by Zomb** [comment]
If I run msbuild Embeddinator-4000 or a clean copy of the repo, it fails on the test projects. If I open the solution in VS 2017 and just build the e4k project, it build fine, but it fails when I run it, with the exception (seen below) that it can't find Mono.Android, which I assumed was because it was missing the component that the powershell script normally downloads.

> System.IO.FileNotFoundException occurred
>   HResult=0x80070002
>   Message=Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
>   Source=IKVM.Reflection
>   StackTrace:
>    at IKVM.Reflection.Universe.Load(String refname, Module requestingModule, Boolean throwOnError) in F:\temp\Embeddinator-4000\external\ikvm\reflect\Universe.cs:line 756
>    at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRefImpl(Record& rec) in F:\temp\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 594
>    at IKVM.Reflection.Reader.ModuleReader.ResolveAssemblyRef(Int32 index) in F:\temp\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 577
>    at IKVM.Reflection.Reader.ModuleReader.ResolveType(Int32 metadataToken, IGenericContext context) in F:\temp\Embeddinator-4000\external\ikvm\reflect\Reader\ModuleReader.cs:line 460
>    at IKVM.Reflection.Reader.TypeDefImpl.get_BaseType() in F:\temp\Embeddinator-4000\external\ikvm\reflect\Reader\TypeDefImpl.cs:line 59
>    at IKVM.Reflection.Type.get_IsEnum() in F:\temp\Embeddinator-4000\external\ikvm\reflect\Type.cs:line 1335
>    at Embeddinator.Generators.ASTGenerator.Visit(TypeInfo typeInfo) in F:\temp\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 105
>    at Embeddinator.Generators.ASTGenerator.Visit(Assembly assembly) in F:\temp\Embeddinator-4000\binder\Generators\AstGenerator.cs:line 68
>    at Embeddinator.Driver.Process() in F:\temp\Embeddinator-4000\binder\Driver.cs:line 80
>    at Embeddinator.Driver.Run() in F:\temp\Embeddinator-4000\binder\Driver.cs:line 236
>    at Embeddinator.CLI.Main(String[] args) in F:\temp\Embeddinator-4000\binder\CLI.cs:line 215
>

**Comment by tritao** [comment]
Could you try again? Not sure what to do here, since it works for me and on the CI server.
