### ISSUE TITLE
[Android] Embeddinator build fails while generating Java stubs

### ISSUE THREAD

**Issue by kaserdan** [mono/Embeddinator-4000#530]
I have a project set as an android library. Using this project for android application in Xamarin.Android works just fine and everything builds successfully. But I can't get the .aar file using E4k build from master branch. I am getting the following error while generating Java stubs:

`
/Users/UserName/Projects/projectName/output/GenerateJavaStubs.proj(18,5): error MSB4044: The "ResolveLibraryProjectImports" task was not given a value for the required parameter "AssemblyIdentityMapFile".
`

**Comment by tritao** [comment]
@jonathanpeppers Any idea about this one?

@kaserdan Do you get the same issue if you use the 0.3 release?

**Comment by tritao** [comment]
Also what is your installed Xamarin.Android version?

**Comment by jonathanpeppers** [comment]
So if Embeddinator is trying to use your system-installed Xamarin.Android, there are some versions where MSBuild tasks have changed. (I'm looking into a way to replace some tasks or mitigate this)

After you checked out Embeddinator's source, did you run?
```
./build.sh -t Generate-Android
```
It should install a version of Xamarin.Android in  `external/Xamarin.Android` that will work, otherwise it falls back to your system's Xamarin.Android.

**Comment by kaserdan** [comment]
With  0.3.0 release I got to the point beyond generating Java stubs. Now it seems that I have some kind of problem with MvvmCross, so it's probably not related to E4K. I will try to stick to version 0.3.0.

**Comment by jonathanpeppers** [comment]
@kaserdan does it look like you have a copy of Xamarin.Android downloaded to `external/Xamarin.Android`, or do you think it was using your system one?

**Comment by kaserdan** [comment]
The system one. I will givie it another try with the build command you suggested.

**Comment by kaserdan** [comment]
I go the same error as for version 0.3.0:

`
/Users/userName/Projects/ProjectName/output/src/md56fff8ae98a57a2dfbbadfff8b162d778/MvxAndroidApplication.java:28: error: cannot find symbol
mono.MonoPackageManager.setContext (this);
^
symbol: method setContext(MvxAndroidApplication)
location: class MonoPackageManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
88 warnings
Failed to compile generated code
`

But it really seems to be an issue with MvvmCross.

**Comment by jonathanpeppers** [comment]
Ok, I see.

I guess MvvmCross calls this method?

```
	public static void setContext (Context context)
	{
		// Ignore; vestigial
	}
```

https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Resources/MonoPackageManager.java#L73

E4K has its own MonoPackageManager: https://github.com/mono/Embeddinator-4000/blob/master/support/java/android/MonoPackageManager.java

If you are building from source, add this method to your copy of E4K. I will send a PR (or feel free if you want to). I think we need to add a test, though.

**Comment by kaserdan** [comment]
That actually worked, thank you :-) 

But I still didn't get successfull build:

`
    Invoking: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/jar cf /Users/nikolajpognerebko/Projects/Microwork/output/Microwork.Droid.jar -C /Users/nikolajpognerebko/Projects/Microwork/output/classes .
    Linking assemblies...
    Invoking: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /nologo /verbosity:minimal /Users/nikolajpognerebko/Projects/Microwork/output/Package.proj
        /Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.App.Job.JobServiceEngine' (defined in assembly 'Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.App.Job.JobServiceEngine
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType (Mono.Cecil.TypeReference reference) [0x00006] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00023] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00000] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00056] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00000] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00063] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00000] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.InitializeType (Mono.Cecil.TypeDefinition type) [0x0004d] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.InitializeType (Mono.Cecil.TypeDefinition type) [0x0001e] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.InitializeType (Mono.Cecil.TypeDefinition type) [0x0001e] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.InitializeAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x00022] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Initialize () [0x00014] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x00007] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x00020] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.LinkContext& context) [0x00070] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x002c8] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:    --- End of inner exception stack trace ---
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Java.Interop.Tools.Diagnostics.Diagnostic.Error (System.Int32 code, System.Exception innerException, System.String message, System.Object[] args) [0x00009] in <38fcf3d2e33c47298fb2b400d1ee9785>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x0046e] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute () [0x00205] in <c576eadddeee4746ac7444221e5ac0e2>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in <76dd0031e0df4aa99d9befb4c4585c69>:0 
/Users/nikolajpognerebko/Projects/Microwork/output/Package.proj(17,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder+<ExecuteInstantiatedTask>d__26.MoveNext () [0x0022d] in <76dd0031e0df4aa99d9befb4c4585c69>:0 
Failed to compile generated code.
`

**Comment by jonathanpeppers** [comment]
Ok, looking at your new issue now.

@kaserdan can you post a copy of your `package.config`, maybe I can try using the same packages in our test projects? A sample project would be even better.

**Comment by kaserdan** [comment]
[Microwork.zip](https://github.com/mono/Embeddinator-4000/files/1427775/Microwork.zip)
 It's the project `Microwork.Droid`

**Comment by jonathanpeppers** [comment]
Ok, so it looks like the issue here is you are using the Support Libraries v26 and TargetFrameworkVersion v8.0.

The bundled version of Xamarin.Android only goes up to TargetFrameworkVersion v7.1, it was prior to API O support. You can try using v7.0 or v7.1, and see if that gets you going. You will have to downgrade the support libraries to 25.x.

I think some changes have to be made to get your project working:
- Embeddinator should just rely on Xamarin.Android 8.0.0 (or higher) and not use the bundled Xamarin.Android in the NuGet package anymore
- This way your system Xamarin.Android can be used, and you can get things like newer API levels without new versions of Embeddinator

There is one big issue I haven't solved yet: several MSBuild tasks have changed, need to figure out if some can be dropped/replaced. I need to fix these in a way to prevent breakage in the future.

**Comment by kaserdan** [comment]
Thank you, I finally got .aar package successfully, so I would consider this issue as solved.

But 50% of builds will still fail for some reason. It has something to do with android resources:

```
    Invoking: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/jar cf /Users/nikolaj/Projects/microwork/output/Microwork.Droid.jar -C /Users/nikolaj/Projects/microwork/output/classes .
    Linking assemblies...
    Invoking: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /nologo /verbosity:minimal /Users/userName/Projects/microwork/output/Package.proj
        /values/styles.xml(2): error APT0000:  Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Light.NoActionBar'. [/Users/nikolaj/Projects/microwork/output/Package.proj]
/values/styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'colorAccent'. [/Users/nikolaj/Projects/microwork/output/Package.proj]
/values/styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'titleTextColor'. [/Users/nikolaj/Projects/microwork/output/Package.proj]
/values/styles.xml(2): error APT0000:  Error retrieving parent for item: No resource found that matches the given name '@style/ThemeOverlay.AppCompat.ActionBar'. [/Users/nikolaj/Projects/microwork/output/Package.proj]
/values/styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'subtitleTextColor'. [/Users/nikolaj/Projects/microwork/output/Package.proj]
/values/styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'titleTextColor'. [/Users/nikolaj/Projects/microwork/output/Package.proj]
```

It's not really deterministic.

**Comment by jasin755** [comment]
I have a some problem but change of successful build is 5% not 50% :(

**Comment by jonathanpeppers** [comment]
@kaserdan one thing you can try here is to run `msbuild` again when you've hit the error.

```
msbuild /Users/userName/Projects/microwork/output/Package.proj /bl
```

It should give you a `msbuild.binlog` file you can post here. You can view it on Windows with the [MSBuild log viewer](http://msbuildlog.com/). It might be helpful to compare one that works, versus not.

The original project you send above I wasn't able to build. Fody was not finding the PropertyChanged weaver, and I didn't go much further when I saw Android 8.0 stuff in use.

**Comment by jonathanpeppers** [comment]
@kaserdan feel free to reopen if you have more info. I believe the problem was related to using Android 8.0 (TargetFrameworkVersion), since the bundled Xamarin.Android only supported 7.0.
