### ISSUE TITLE
[ObjC] Using embedded framework in MacOS app causes image not found error...

### ISSUE THREAD

**Issue by equinox2k** [mono/Embeddinator-4000#535]
Getting the error...

```
dyld: Library not loaded: @loader_path/../Frameworks/PNIPhotoLibraryEmbedded.framework/PNIPhotoLibraryEmbedded
  Referenced from: /Users/petertribe/Library/Developer/Xcode/DerivedData/MacWrapper-emxlbyczdznyigevgjtzyvdjalwm/Build/Products/Debug/PNIPhotoLibrarySDK.framework/Versions/A/PNIPhotoLibrarySDK
  Reason: image not found
```

However I have ensured I have embedded framework using copy rule. I did a quick experiment and changed "@loader_path/../Frameworks" to "@loader_path/Frameworks" using install_name_tool and error went away however dll's needed by app could not be found.

I wondering if the output from doing the following works..?

objcgen.exe --debug --platform=macosmodern --abi=x86_64 --target=framework --outdir=output --compile mydll.dll

I tried to do a shared library as per your documentation e.g.

`objcgen.exe --debug --outdir=output --compile mydll.dll`

however I got the error..

```
Creating output directory `/Users/petertribe/Documents/Git/PNI.Mobile.Xamarin.Research/PNI.Photo.Library.Embedded/PNI.Photo.Library.Embedded.Mac/output`
Parsing assemblies...
	Parsed '/Users/petertribe/Documents/Git/PNI.Mobile.Xamarin.Research/PNI.Photo.Library.Embedded/PNI.Photo.Library.Embedded.Mac/bin/Debug/PNIPhotoLibraryEmbedded.dll'
Processing assemblies...
error EM0013: Can't find the assembly 'Xamarin.Mac, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065', referenced by 'PNIMobileLibrary, Version=1.0.6515.18092, Culture=neutral, PublicKeyToken=null'.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

UPDATE: 

Ok I got things working by doing the following command...

`install_name_tool -id "@executable_path/../Frameworks/PNIPhotoLibraryEmbedded.framework/PNIPhotoLibraryEmbedded" PNIPhotoLibraryEmbedded`

This changed from the default @loader_path to @executable_path

**Comment by chamons** [comment]
I just tested this using the correct framework steps in Xcode listed here:

https://mono.github.io/Embeddinator-4000/getting-started-objc-ios.html

which are not listed for XM yet due to this issue:

https://github.com/mono/Embeddinator-4000/issues/393

and it worked correctly for me. Did you add the framework to your Xcode project _and_ set it as an "Embedded Binary".

If so, I'll need a project showing your configuration.

**Comment by dalexsoto** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
