### ISSUE TITLE
[c] No ArgumentNullException from GenerateArrayTypes.CheckArrayType

### ISSUE THREAD

**Issue by chambm** [mono/Embeddinator-4000#545]
Running with latest master, `1c69e02fc092c246e919ddb8bc658fb55ec20202`, I reduced it to the simplest case:
```
namespace LibTest
{
    public class ObjectFactory<T> where T: class
    {
    }

    public class ObjectFactoryCollection<T> where T : class
    {
        public void AddRange(ObjectFactory<T>[] itemArray) { }
    }
}
```

The command I ran:
**Embeddinator-4000.exe --gen=c --out=managed_c --platform=windows --compile --vs=2015 LibTest.dll**
> 
> 
> Parsing assemblies...
>     Parsed 'LibTest.dll'
> Processing assemblies...
> 
> Unhandled Exception: System.ArgumentNullException: Value cannot be null.
> Parameter name: key
>    at System.Collections.Generic.Dictionary\`2.FindEntry(TKey key)
>    at Embeddinator.Passes.GenerateArrayTypes.CheckArrayType(ArrayType array, Declaration decl, QualifiedType& type) in binder\Passes\GenerateArrayTypes.cs:line 76
>    at Embeddinator.Passes.GenerateArrayTypes.CheckType(Type type, Declaration decl, QualifiedType& newType) in binder\Passes\GenerateArrayTypes.cs:line 99
>    at Embeddinator.Passes.GenerateArrayTypes.VisitFunctionDecl(Function function) in binder\Passes\GenerateArrayTypes.cs:line 115
>    at CppSharp.AST.AstVisitor.VisitMethodDecl(Method method) in external\CppSharp\src\AST\ASTVisitor.cs:line 410
>    at CppSharp.AST.Method.Visit[T](IDeclVisitor\`1 visitor) in external\CppSharp\src\AST\Method.cs:line 183
>    at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context) in external\CppSharp\src\AST\ASTVisitor.cs:line 560
>    at CppSharp.AST.AstVisitor.VisitClassDecl(Class class) in external\CppSharp\src\AST\ASTVisitor.cs:line 319
>    at CppSharp.AST.Class.Visit[T](IDeclVisitor\`1 visitor) in external\CppSharp\src\AST\Class.cs:line 312
>    at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context) in external\CppSharp\src\AST\ASTVisitor.cs:line 557
>    at CppSharp.AST.AstVisitor.VisitNamespace(Namespace namespace) in external\CppSharp\src\AST\ASTVisitor.cs:line 548
>    at CppSharp.AST.Namespace.Visit[T](IDeclVisitor\`1 visitor) in external\CppSharp\src\AST\Namespace.cs:line 452
>    at CppSharp.AST.AstVisitor.VisitDeclarationContext(DeclarationContext context) in external\CppSharp\src\AST\ASTVisitor.cs:line 583
>    at CppSharp.Passes.TranslationUnitPass.VisitTranslationUnit(TranslationUnit unit) in external\CppSharp\src\Generator\Passes\Pass.cs:line 37
>    at Embeddinator.Passes.GenerateArrayTypes.VisitTranslationUnit(TranslationUnit unit) in binder\Passes\GenerateArrayTypes.cs:line 33
>    at CppSharp.Passes.TranslationUnitPass.VisitASTContext(ASTContext context) in external\CppSharp\src\Generator\Passes\Pass.cs:line 24
>    at CppSharp.Generators.BindingContext.<RunPasses>b__33_0(TranslationUnitPass pass) in external\CppSharp\src\Generator\BindingContext.cs:line 41
>    at CppSharp.PassBuilder\`1.RunPasses(Action`1 action) in external\CppSharp\src\Generator\Passes\PassBuilder.cs:line 49
>    at CppSharp.Generators.BindingContext.RunPasses() in external\CppSharp\src\Generator\BindingContext.cs:line 36
>    at Embeddinator.Driver.Process() in binder\Driver.cs:line 96
>    at Embeddinator.Driver.Run() in binder\Driver.cs:line 240
>    at Embeddinator.CLI.Main(String[] args) in binder\CLI.cs:line 220

**Comment by tritao** [comment]
Thanks for the reduced test case, I'll check this.
