### ISSUE TITLE
[Android] Activity class removed from created .aar file

### ISSUE THREAD

**Issue by simontocknell** [mono/Embeddinator-4000#546]
When I have a property, or a method using the Activity type, and create a .aar file from this. The properties and methods just don't exist in the created .aar file.

```csharp
public static string Endpoint { get; set; }

public static bool IsSharing { get; set; }

public static Activity Activity { get; set; }
```

So getters and setters would be created for Endpoint and IsSharing, but Activity doesn't exist.

**Comment by simontocknell** [comment]
This also happens if there is a method that accepts Activity as a parameter. It just doesn't create the method at all.

**Comment by tritao** [comment]
I think this is because we ignore any type from `Mono.Android.dll` in regular classes. Can you try the same but with a class that inherits from `java.lang.Object`?

**Comment by simontocknell** [comment]
Made a 'Test' class inheriting from Java.Lang.Object and a property using the class and a method using the class were both not created in the .aar file.

**Comment by jonathanpeppers** [comment]
@simontocknell it worked for me when I added a test: https://github.com/jonathanpeppers/Embeddinator-4000/commit/ce8f6d604686c09501cd2f1623a444f3dfb39123

Are you missing the `[Export]` and/or `[Register]` attributes? 

Example here:
https://developer.xamarin.com/guides/cross-platform/dotnet-embedding/getting-started/java/android/#Current_Limitations_on_Android

**Comment by tritao** [comment]
@jonathanpeppers added a test for this, re-open if still an issue.

**Comment by roceh** [comment]
I'm having the same issue with both activity and a object inherited from java.lang.object, in verbose mode i get the following:

 Function 'ShowPickerDialog' was ignored due to ignored param

I note that when creating a test object inheriting from java.lang.object a java file is created for it and is compiled into the aar, but the function referencing it is not exported.

This was done with the current master on osx.

**Comment by jonathanpeppers** [comment]
@roceh can you open a separate issue and provide some more details?

Such as:
- A snippet/example of your C# code
- The Java you that is getting generated
- Maybe copy/paste the exact error from Android Studio? Or maybe you have it above already.
