### ISSUE TITLE
Android|Java -c compile error

### ISSUE THREAD

**Issue by ysmoradi** [mono/Embeddinator-4000#554]
After running mono Embeddinator-4000.exe "path to some xamarin forms based dll" -gen=Java -p=Android -o="some folder" -c
I receive following exceptions:

 **Failed to read .. dll with debugging symbols. Retrying to load it without it.**

warning: unknown enum constant Scope.LIBRARY_GROUP
  reason: class file for android.support.annotation.RestrictTo$Scope not found

**src\mono\android\support\v7\widget\ShareActionProvider_OnShareTargetSelectedListenerImplementor.java:28: error: cannot find symbol
        public boolean onShareTargetSelected (android.support.v7.widget.ShareActionProvider p0, android.content.Intent p1)**

src\mono\android\support\v4\view\ViewPager_OnPageChangeListenerImplementor.java:8: error: package android.support.v4.view.ViewPager does not exist
                android.support.v4.view.ViewPager.OnPageChangeListener

**Comment by jonathanpeppers** [comment]
Hi @ysmoradi,

A couple questions to help figure this out:
* Are you using NuGet or building Embeddinator from source?
* Can you share your `packages.config` or your project?

One thing to check is that you aren't using anything API 26+ (such as support libraries v26.x). The current release on NuGet does not support those.

**Comment by ysmoradi** [comment]
I've downloaded Embeddinator's nuget package, then I ran command in "embeddinator-4000.0.3.0/tools" folder.

My projects is a xamarin android library which contains "xamarin forms content page" which has simple controls such as stack layout, entry, button and label. In my xamarin.android app, I'm converting that content page to fragment. It's working fine.

I'd like to use my fragment in Java-Android app.

https://github.com/ysmoradi/XamComponent

**Comment by ysmoradi** [comment]
I know such a simple codes relies on multiple assemblies with deep technical concepts. But could you please tell me how much you think it will increases the apk size of my java app? Thanks in advance.

**Comment by jonathanpeppers** [comment]
Yeah, you have API 26 stuff in here, which is why you have the failure. I think we are due for a new release on NuGet, but I don't know when it will be yet.

You can either:
1. use `TargetFrameworkVersion` 7.1 and make sure all the support libraries are 25.x
1. add a submodule for Embeddinator in your repo, and build it from source. This will get you API 26 support that we have on master.

It will increase the size of your app by:
- (number of Android abis) x (size of mono ~3.4MB) - you can turn off some of these in gradle, if you only need x86 / armv7, for example
- size of all .NET assemblies

**Comment by ysmoradi** [comment]
Thanks so much. :) Does it link unused IL from assemblies?

**Comment by jonathanpeppers** [comment]
Right now it will do the same thing as `Link SDK assemblies only`, just like a Xamarin.Android app.

**Comment by tritao** [comment]
@ysmoradi We should be releasing a new version on Nuget soon, in case you don't want to go through the trouble of compiling master yourself.

**Comment by ysmoradi** [comment]
Thanks so much. I'm waiting for the next release :)
