### ISSUE TITLE
[ObjC] ld: framework not found Carbon

### ISSUE THREAD

**Issue by nunosantosgit** [mono/Embeddinator-4000#557]
**Embeddinating for objectiveC with command:** objcgen bin/debug/Nativo.PhotoBookSDK.iOS.dll --target=framework --platform=iOS --outdir=output --abi=arm64 -c -v --debug

(This dll references other dlls)

**Error:**
ld: framework not found Carbon
clang: error: linker command failed with exit code 1 (use -v to see invocation)

error MT5216: Native linking failed for '/Projects/PhotoBook/PhotoBookSDK.iOS/output/iPhoneOS/build-cache/arm64/PhotoBookSDK.iOS'. Please file a bug report at http://bugzilla.xamarin.com

(Don't know what Carbon is)

**Comment by chamons** [comment]
Carbon is a native C library from Apple.

For the to be actionable, we need to at minimum see the build log. A project showing it would be extremely helpful as well.

**Comment by dalexsoto** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
