### ISSUE TITLE
[ObjC] Warnings on System.DateTime not generated in Embeddinator version 0.4.

### ISSUE THREAD

**Issue by emysa341** [mono/Embeddinator-4000#560]
- In Embeddinator version 0.4, the **Objcgen** logs warnings that it cannot generate native counter parts, while the same behaviour works in version [0.2.0.79](https://dl.xamarin.com/embeddinator/Xamarin.Embeddinator-4000-0.2.0.79.pkg). Followings shows the warnings:

<img width="992" alt="1" src="https://user-images.githubusercontent.com/5163679/34404450-e48d614a-ebad-11e7-91fe-eb314e188ddb.png">

- If you use Objcgen version 0.2.0.79, then the same project has no warnings and counter part is generated:
<img width="1151" alt="2" src="https://user-images.githubusercontent.com/5163679/34404474-1c25b634-ebae-11e7-8fa9-690f5f2d4e56.png">

- Following is the bindings header file with version 0.2.0.79:
<img width="938" alt="3" src="https://user-images.githubusercontent.com/5163679/34404484-2701c124-ebae-11e7-9d91-bc9977eb5764.png">

- Following is sample project, please use both version Objcgen to see the difference: 
[CSharp.zip](https://github.com/mono/Embeddinator-4000/files/1590750/CSharp.zip)

**Comment by spouliot** [comment]
`NSDate` support still works on in `objc` branch
I'm not sure why it broke in 0.4 (released from `master`) but there were some other merge issues that are being fixed.

**Comment by chamons** [comment]
objc has been merged into master, so this should be fixed in master (and the next release). 

I was able to build your sample with master and NSDate's were in the generated header.
