### ISSUE TITLE
Java: properties easily generate conflicts with methods, even in mscorlib types

### ISSUE THREAD

**Issue by atsushieno** [mono/Embeddinator-4000#580]
e4k generates properties with "get" prefix, unlike C# internal do ("get_"). This API design easily results in name conflicts in the class libraries.

For example, in mscorlib.dll there is [System.Runtime.Remoting.Metadata.W3cXsd2001.SoapId](https://msdn.microsoft.com/en-us/library/system.runtime.remoting.metadata.w3cxsd2001.soapid_members%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
) has XsdType static property and GetXsdType() method. They are both generated as getXsdType(). This happens everywhere in this namespace.

**Comment by tritao** [comment]
We used to generate with `get_` too but this was improved recently to better match Java conventions but looks like some edge cases were missed.
