### ISSUE TITLE
Java: mscorlib types result in duplicates if target assembly is mscorlib.dll

### ISSUE THREAD

**Issue by atsushieno** [mono/Embeddinator-4000#582]
Maybe it is because e4k has to specialize some types in mscorlib.dll, but if I try to bind mscorlib.dll (with a handful of local fixes) it results in the errors below:

		Linking assemblies...
		Error: warning CS1685: The predefined type `System.Object' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueType' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Attribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Int32' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.UInt32' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Int64' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.UInt64' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Single' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Double' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Char' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Int16' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Decimal' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Boolean' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.SByte' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Byte' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.UInt16' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.String' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Enum' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Delegate' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.MulticastDelegate' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Array' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Type' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Collections.IEnumerator' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Collections.IEnumerable' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.IDisposable' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.IntPtr' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.UIntPtr' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.RuntimeFieldHandle' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.RuntimeTypeHandle' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Exception' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ParamArrayAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.OutAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ObsoleteAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.DllImportAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.MethodImplAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.MarshalAsAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.InAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.IndexerNameAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Diagnostics.ConditionalAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.CLSCompliantAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Security.Permissions.SecurityAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.RequiredAttributeAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.GuidAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyCultureAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyVersionAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyAlgorithmIdAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyFlagsAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyFileVersionAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyInformationalVersionAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.ComImportAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.CoClassAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.AttributeUsageAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.OptionalAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Security.UnverifiableCodeAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.DefaultCharSetAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.TypeForwardedToAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.FixedBufferAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.CompilerGeneratedAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.InternalsVisibleToAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.RuntimeCompatibilityAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Diagnostics.DebuggerHiddenAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.UnsafeValueTypeAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.UnmanagedFunctionPointerAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Diagnostics.DebuggerBrowsableAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Diagnostics.DebuggerStepThroughAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Diagnostics.DebuggableAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Security.Permissions.HostProtectionAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.ExtensionAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.AsyncStateMachineAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.TupleElementNamesAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.IsReadOnlyAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.IsByRefLikeAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.DefaultMemberAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.DecimalConstantAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.StructLayoutAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.InteropServices.FieldOffsetAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyProductAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyCompanyAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyCopyrightAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Reflection.AssemblyTrademarkAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.CallerMemberNameAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.CallerLineNumberAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Runtime.CompilerServices.CallerFilePathAttribute' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.TypedReference' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ArgIterator' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Collections.Generic.IEnumerable' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Collections.Generic.IList' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Collections.Generic.IReadOnlyList' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Collections.Generic.ICollection' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Collections.Generic.IReadOnlyCollection' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Nullable' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Threading.Tasks.Task' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.Threading.Tasks.Task' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.IFormattable' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.FormattableString' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: warning CS1685: The predefined type `System.ValueTuple' is defined multiple times. Using definition from `mscorlib.dll'
		Error: /tmp/x94te73t.0.cs(21,24) : error CS0433: The imported type `System.Int32' is defined multiple times
		Error: /tmp/x94te73t.0.cs(21,43) : error CS0433: The imported type `System.IntPtr' is defined multiple times
		Error: /tmp/x94te73t.0.cs(21,53) : error CS0433: The imported type `System.String' is defined multiple times

	Unhandled Exception:
	System.Exception: Resource.designer.dll compilation failed! See e4k/android/Resource.designer.cs for details.
	  at Embeddinator.Driver.CreateAar () [0x00587] in /sources/Embeddinator-4000/binder/Compilation.cs:494 
	  at Embeddinator.Driver.CompileCode () [0x00167] in /sources/Embeddinator-4000/binder/Compilation.cs:68 
	  at Embeddinator.Driver.Run () [0x000d4] in /sources/Embeddinator-4000/binder/Driver.cs:253 
	  at Embeddinator.CLI.Main (System.String[] args) [0x000a6] in /sources/Embeddinator-4000/binder/CLI.cs:220 
	[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Resource.designer.dll compilation failed! See e4k/android/Resource.designer.cs for details.
	  at Embeddinator.Driver.CreateAar () [0x00587] in /sources/Embeddinator-4000/binder/Compilation.cs:494 
	  at Embeddinator.Driver.CompileCode () [0x00167] in /sources/Embeddinator-4000/binder/Compilation.cs:68 
	  at Embeddinator.Driver.Run () [0x000d4] in /sources/Embeddinator-4000/binder/Driver.cs:253 
	  at Embeddinator.CLI.Main (System.String[] args) [0x000a6] in /sources/Embeddinator-4000/binder/CLI.cs:220 

On the other hand, I could successfully bind System.dll (to the point that "System.aar" is generated), so this issue is specific to mscorlib.dll as the target.

**Comment by atsushieno** [comment]
For reference, patch is here: https://gist.github.com/atsushieno/4f22286aeec2a2093fccd43fb3888341

**Comment by jonathanpeppers** [comment]
@atsushieno is the patch meant for #581 ?

I wrote some code for fixing up resources, that generates a `Resource.designer.dll` unique for e4k, but comparable to `Resources.designer.cs` in Xamarin.Android. 

Can you post the contents of `e4k/android/Resource.designer.cs`?

**Comment by atsushieno** [comment]
The patch includes multiple fixes, and yes one is for #581.

Resource.designer.cs is is here: https://gist.github.com/atsushieno/aecbc89e7dbc7c960d2400cbc85fd33f

**Comment by jonathanpeppers** [comment]
Ok, I see the problem.

`Int32` and `String` should probably use the lowercase "blue" keywords and they would work fine.

**Comment by atsushieno** [comment]
I'm not sure what you are writing about. Here is my command line to reproduce the issue:

    mono --debug /sources/Embeddinator-4000/build/lib/Debug/Embeddinator-4000.exe -gen Java -p Android -c -d -o e4k/android /sources/xamarin-android/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/mscorlib.dll
