### ISSUE TITLE
question - how is embeddinator working when compared with unmanaged export (dllexport)?

### ISSUE THREAD

**Issue by denfromufa** [mono/Embeddinator-4000#589]
On Windows I'm using Unmanaged Exports project with .NET Framework and this works by doing reverse pinvoke of annotated .NET methods. But this approach has not been extended for other platforms and runtimes.

How is embeddinator different from this approach? 

Is it essentially AOT compilation of IL code into native code?

Does embeddinator work on all 3 major .NET runtimes?

**Comment by denfromufa** [comment]
Ok, I see now that .NET Core is currently NOT supported and Mono runtime is embedded:

https://github.com/mono/Embeddinator-4000/issues/10

**Comment by tritao** [comment]
Hey @denfromufa, as you found out we presently use Mono as the .NET runtime. In theory it should be possible to also support .NET Core, but it's not in our near plans to do.

**Comment by denfromufa** [comment]
@tritao maybe this should be stated clearly in some docs? at present it is not obvious that this depends on Mono, especially when the docs call this ".NET embedding".
