### ISSUE TITLE
[Objc] Mac tests failure due to assembly missing.

### ISSUE THREAD

**Issue by mandel-macaque** [mono/Embeddinator-4000#596]
In the Objc branch the tests on the mac fail due to possible some API changes with XM’s runtime:

Failure examples: https://jenkins.mono-project.com/job/embeddinator-4000/492/

**Comment by chamons** [comment]
Fixed with https://github.com/mono/Embeddinator-4000/commit/f7f9b267d3c4a0041377684ba25968f8b866d015
