### ISSUE TITLE
Android error error MSB4064: The "AssemblyIdentityMapFile" parameter is not supported by the "ResolveLibraryProjectImports" task. Verify the parameter exists on the task, and it is a settable public instance property

### ISSUE THREAD

**Issue by jmmortega** [mono/Embeddinator-4000#598]
Hi!

I received this error when trying use Embeddinator for Android in Mac.

Users/jmmontero.ortegagmail.com/Projects/SampleEmbedding/aoutput/GenerateJavaStubs.proj(18,74): error MSB4064: The "AssemblyIdentityMapFile" parameter is not supported by the "ResolveLibraryProjectImports" task. Verify the parameter exists on the task, and it is a settable public instance property.
/Users/jmmontero.ortegagmail.com/Projects/SampleEmbedding/aoutput/GenerateJavaStubs.proj(18,5): error MSB4063: The "ResolveLibraryProjectImports" task could not be initialized with its input parameters.

I received this error, when built Embeddinator myself.

Also generate Android External and working several flavours for Android SDK and Targets Framework.

Any idea?

**Comment by jonathanpeppers** [comment]
Hi @jmmortega ,

Did you run the cake task as mentioned here: https://github.com/mono/Embeddinator-4000/blob/master/docs/Contributing.md#cake

It should download a specific version of Xamarin.Android that will work.

**Comment by jmmortega** [comment]
@jonathanpeppers I build that propose and receive the same error.

**Comment by jonathanpeppers** [comment]
So does it look like files where downloaded to `external/Xamarin.Android` where you checked out the repo?

It still sounds like it hasn't and its trying to use your system's Xamarin.Android.

**Comment by jmmortega** [comment]
@jonathanpeppers I checked last week, so I think it's really recently.

**Comment by jmmortega** [comment]
@jonathanpeppers I think I solve that, rebuild again all embeddinator. But now I have a new error...

        /Users/jmmontero.ortegagmail.com/Projects/HelloShareUI/embeddinator-hellosharedui/HelloSharedUI/output/GenerateJavaStubs.proj(17,5): warning : Failed to read '/Users/jmmontero.ortegagmail.com/Projects/HelloShareUI/embeddinator-hellosharedui/HelloSharedUI/HelloSharedUI.Droid/bin/Release/Xamarin.Forms.Platform.Android.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
/Users/jmmontero.ortegagmail.com/Projects/HelloShareUI/embeddinator-hellosharedui/HelloSharedUI/output/GenerateJavaStubs.proj(17,5): warning : System.TypeLoadException: Could not find symbol provider type Mono.Cecil.Pdb.NativePdbReaderProvider

Not generate .aar file

**Comment by jmmortega** [comment]
OK, solved!!!! 

Fine, I think, only required replace the tools folder for Embedinnator folder. However require too, copy the support folder and external to have the same files that compiled version.
