### ISSUE TITLE
Missing path in AndroidSdkWindows

### ISSUE THREAD

**Issue by Zomb** [mono/Embeddinator-4000#599]
I am attempting to build e4k on a fresh installation of Windows and running into a missing Android SDK exception.
In AndroidSdkWindows.cs under external\Xamarin.Android.Tools, there are a number of locations listed that are used to search for the Android SDK. The problem is that a clean install of Visual Studio does not create any of those registry entries listed. The closest I can find is
`var android_default = Path.Combine (OS.ProgramFilesX86, "Android", "android-sdk-windows")`
but the path VS uses is "android-sdk" not "android-sdk-windows".

Since this is under external, I am not sure what the rules are to fix this. Removing the windows part of the string does let the build complete. I don't see any Environment Variables in that class that I can set to point to the right SDK, and I don't really want to create a registry entry following one of the paths in the file to find the SDK, but I will do that if its the recommended fix!

**Comment by tritao** [comment]
Looks like we are already on the latest version of https://github.com/xamarin/xamarin-android-tools/blob/master/src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs so this seems like a bug in Xamarin.Android.Tools.

@Zomb I think the way forward might be to send a PR to Xamarin.Android.Tools repo and add a check for "android-sdk" in addition to "android-sdk-windows".

cc'ing @dellis1972 from Android team. Does that approach sound ok?

**Comment by SeshagiriSriram** [comment]
There are a number of persons who also depend on the nugent package to run embeddinator. Would this fix also go in for the nugent package (Pardon me I am asking this in the wrong area :)
