### ISSUE TITLE
Mono import missing

### ISSUE THREAD

**Issue by miloradtrninic** [mono/Embeddinator-4000#607]
Hello,

I've generated Java classes from my C# dll and it requires mono import (mono.embeddinator) I can't find it anywhere so it seams like I am missing something. can someone point me to the direction where can I find this import?

Regards

**Comment by tritao** [comment]
Java support code is in https://github.com/mono/Embeddinator-4000/tree/master/support/java

If you use the `-compile` option you will get a self-contained JAR file ready to go.

**Comment by miloradtrninic** [comment]
Thanks for quick replay. When I use the compile flag I get an error with unsigned int class which says that my integer 2420314209 is too large?

**Comment by tritao** [comment]
I believe that bug should already be fixed on the master version.
