### ISSUE TITLE
Add ability to customize ObjC bindings names via attributes or xml

### ISSUE THREAD

**Issue by chamons** [mono/Embeddinator-4000#612]
An initial stab was taken here:

https://github.com/mono/Embeddinator-4000/pull/366

**Comment by spouliot** [comment]
let's make an RFC and consider all platforms and languages

**Comment by chamons** [comment]
Agreed. I was just closing the ancient PR and made the issue to not forget the work.

**Comment by chamons** [comment]
#481 is an older duplicate
