### ISSUE TITLE
.aar file not created on windows

### ISSUE THREAD

**Issue by renjithtkm** [mono/Embeddinator-4000#614]
Followed the steps given in https://developer.xamarin.com/guides/android/advanced_topics/embedding-net-in-java/

1.Create a C# Android Library project app1.
2.Install Embeddinator-4000 via NuGet
3.Run Embeddinator on the Android library assembly using
       in the postbuild event commandline in windows is given as

C:\Users\source\repos\App1\packages\Embeddinator-4000.0.3.0\tools\embeddinator-4000.exe -gen=java -out=foo -p=Android C:\Users\source\repos\App1\App1\bin\Debug\app1.dll

I am using vs 2017 and Android 7.

Results of the build is given below.

------ Rebuild All started: Project: App1, Configuration: Debug Any CPU ------
1>  App1 -> c:\users\sd1070316\source\repos\App1\App1\bin\Debug\App1.dll
1>  Parsing assemblies...
1>      Parsed 'app1.dll'
1>  Processing assemblies...
1>  Generating binding code...
1>      Generated: app1.h
1>      Generated: app1.c
1>      Generated: Mono.Android.h
1>      Generated: Mono.Android.c
1>      Generated: Java.Interop.h
1>      Generated: Java.Interop.c
1>      Generated: mscorlib.h
1>      Generated: mscorlib.c
1>      Generated: c-support.c
1>      Generated: c-support.h
1>      Generated: embeddinator.h
1>      Generated: glib.c
1>      Generated: glib.h
1>      Generated: mono-support.c
1>      Generated: mono-support.h
1>      Generated: mono_embeddinator.c
1>      Generated: mono_embeddinator.h
1>  Parsing assemblies...
1>      Parsed 'app1.dll'
1>      Parsed 'app1.dll'
1>  Processing assemblies...
1>  Generating binding code...
1>      Generated: app1\app1\Resource.java
1>      Generated: app1\app1\Attribute.java
1>      Generated: app1\app1\Layout.java
1>      Generated: app1\app1\String.java
1>      Generated: app1\Native_app1.java
1>      Generated: mscorlib\system\IDisposableImpl.java
1>      Generated: mscorlib\system\IDisposable.java
1>      Generated: mscorlib\Native_mscorlib.java
1>      Generating Java stubs...
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : Failed to read 'C:\Users\SD1070316\source\repos\App1\App1\bin\Debug\app1.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : System.TypeLoadException: Could not find symbol provider type Mono.Cecil.Pdb.NativePdbReaderProvider
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : at Mono.Cecil.Cil.SymbolProvider.GetReaderProvider(SymbolKind kind)
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
1>c:\users\sd1070316\source\repos\App1\App1\bin\Debug\foo\GenerateJavaStubs.proj(17,5): warning : at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
1>  
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

As seen generating javastubs is giving error and .aar file is not created,output directory foo is created.

can any one please give the solution why .aar file is not created?

**Comment by jonathanpeppers** [comment]
Hi @renjithtkm I think you need the `--compile` or `-c` option.

**Comment by renjithtkm** [comment]
Thank you.
But when I gave -c option I got the following
>  
1>  Unhandled Exception: System.InvalidOperationException: Platform header files for target Arm and API Level 24 was not found. Expected path is "C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r10e\platforms\android-24\arch-arm"
1>     at Xamarin.Android.Tasks.NdkUtil.GetNdkPlatformIncludePath(String androidNdkPath, AndroidTargetArch arch, Int32 level)
1>     at Embeddinator.Driver.CompileNDK(IEnumerable`1 files)
1>     at Embeddinator.Driver.CompileNativeCode(IEnumerable`1 files)
1>     at Embeddinator.Driver.CompileCode()
1>     at Embeddinator.Driver.Run()
1>     at Embeddinator.CLI.Main(String[] args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5088,5): error MSB3073: The command "C:\Users\SD1070316\source\repos\App1\packages\Embeddinator-4000.0.3.0\tools\embeddinator-4000.exe -gen=java -out=foo -p=Android C:\Users\SD1070316\source\repos\App1\App1\bin\Debug\app1.dll -c" exited with code -532462766.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

My android ndk location is C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r10e\

can you give a solution?

**Comment by jonathanpeppers** [comment]
If you look in the directory it's looking for, what do you see in `C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r10e\platforms\android-24\`?

Your Android NDK looks like it might be a bit old, mine is `C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r13b`, can you upgrade?

**Comment by renjithtkm** [comment]
yes ,I can upgrade,Thank you

**Comment by renjithtkm** [comment]
Hi Jonathanpeppers, 

On upgrading to android-ndk-r13b the following errors are thrown,

1>      Generated: mono_embeddinator.h
1>  Compiling binding code...
1>          In file included from foo\mono_embeddinator.h:32:0,
1>                   from foo\app1.h:10,
1>                   from foo\app1.c:7:
1>  foo\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
1>   #include <mono/jit/jit.h>
1>                            ^
1>  compilation terminated.
1>  In file included from foo\mono_embeddinator.h:32:0,
1>                   from foo\Mono.Android.h:10,
1>                   from foo\Mono.Android.c:7:
1>  foo\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
1>   #include <mono/jit/jit.h>
1>                            ^
1>  compilation terminated.
1>  In file included from foo\mono_embeddinator.h:32:0,
1>                   from foo\Java.Interop.h:10,
1>                   from foo\Java.Interop.c:7:
1>  foo\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
1>   #include <mono/jit/jit.h>
1>                            ^
1>  compilation terminated.
1>  In file included from foo\mono_embeddinator.h:32:0,
1>                   from foo\mscorlib.h:10,
1>                   from foo\mscorlib.c:7:
1>  foo\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
1>   #include <mono/jit/jit.h>
1>                            ^
1>  compilation terminated.
1>  In file included from foo\c-support.h:30:0,
1>                   from foo\c-support.c:26:
1>  foo\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
1>   #include <mono/jit/jit.h>
1>                            ^
1>  compilation terminated.
1>  In file included from foo\mono-support.c:26:0:
1>  foo\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
1>   #include <mono/jit/jit.h>
1>                            ^
1>  compilation terminated.
1>  In file included from foo\mono_embeddinator.h:32:0,
1>                   from foo\mono_embeddinator.c:29:
1>  foo\mono-support.h:187:26: fatal error: mono/jit/jit.h: No such file or directory
1>   #include <mono/jit/jit.h>
1>                            ^
1>  compilation terminated.
1>  
1>  Failed to compile generated code.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5088,5): error MSB3073: The command "C:\Users\SD1070316\source\repos\App1\packages\Embeddinator-4000.0.3.0\tools\embeddinator-4000.exe -gen=java -out=foo -p=Android C:\Users\SD1070316\source\repos\App1\App1\bin\Debug\app1.dll -c" exited with code -1.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

Can you please give your solution to the issue?

**Comment by jonathanpeppers** [comment]
@renjithtkm I believe you need to install Mono, you are getting closer though!

Get the 32 bit version for Windows [here](http://www.mono-project.com/download/stable/).

**Comment by renjithtkm** [comment]
Thanks.

After installing Mono, the result is given below

I am using the command in powershell 

Although I have given path of ndk as C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r13b

in compile it is shown as 

 c:/programdata/microsoft/androidndk/android-ndk-r10e

Can you specify why is that ,Do I have to do anything?

The code is failing.can you gave a solution?

PS D:\repos\Embeddinator-4000\build\lib\release> .\embeddinator-4000 -gen=java -p=Android -out=d:/foo c:\users\sd1070316
\source\repos\app1\app1\bin\debug\app1.dll -c -vs=2017
Parsing assemblies...
    Parsed 'app1.dll'
Processing assemblies...
Generating binding code...
    Generated: app1.h
    Generated: app1.c
    Generated: Mono.Android.h
    Generated: Mono.Android.c
    Generated: mscorlib.h
    Generated: mscorlib.c
    Generated: Java.Interop.h
    Generated: Java.Interop.c
    Generated: c-support.c
    Generated: c-support.h
    Generated: embeddinator.h
    Generated: glib.c
    Generated: glib.h
    Generated: mono-support.c
    Generated: mono-support.h
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...
        c:/programdata/microsoft/androidndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/windows/bin/.
./lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.exe: error: cannot find -lmonosgen-2.0
c:/programdata/microsoft/androidndk/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/windows/bin/../lib/gc
c/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld.exe: error: cannot find -lmono-android.release
collect2.exe: error: ld returned 1 exit status

Failed to compile generated code.

**Comment by jonathanpeppers** [comment]
Ok, it looks like the way we are finding the Android NDK (from Xamarin.Android.Tools), it is finding the first one.

It looks like you have two installed side-by-side, can you remove the older one?

In the mean time, I'll see if it would be reasonable to grab them in reverse order (newest first).

**Comment by SeshagiriSriram** [comment]
@jonathanpeppers Thank you for the feedback. Same results as @renjithtkm were obtained by me - but partially, I had working around that  by changing the order on a local build  (Note on clean installs - no issues are there 👍 There are possibly 2 workarounds: I would possibly do that in reverse order (as you suggested) or possibly pull the location from a user defined env variable to take 1st precedence. The other way which worked for me was to create links between VS2015/VS2017 Android Directories (before installing VS1017) but I found it a messy solution.

**Comment by renjithtkm** [comment]
@jonathanpeppers Thank you for the feedback.

After removing the older version of ndk I am getting following errors

Android ndk location is set in xamarin as C:\ProgramData\Microsoft\AndroidNDK\android-ndk-r13b

PS D:\repos\Embeddinator-4000\build\lib\release> .\embeddinator-4000 -gen=java -p=Android -out=d:/foo c:\users\sd1070316
\source\repos\app1\app1\bin\debug\app1.dll -c -vs=2017
Parsing assemblies...
    Parsed 'app1.dll'
Processing assemblies...
Generating binding code...
    Generated: app1.h
    Generated: app1.c
    Generated: Mono.Android.h
    Generated: Mono.Android.c
    Generated: mscorlib.h
    Generated: mscorlib.c
    Generated: Java.Interop.h
    Generated: Java.Interop.c
    Generated: c-support.c
    Generated: c-support.h
    Generated: embeddinator.h
    Generated: glib.c
    Generated: glib.h
    Generated: mono-support.c
    Generated: mono-support.h
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Embeddinator.Driver.CompileNDK(IEnumerable`1 files) in D:\repos\Embeddinator-4000\binder\Compilation.cs:line 718
   at Embeddinator.Driver.CompileNativeCode(IEnumerable`1 files) in D:\repos\Embeddinator-4000\binder\Compilation.cs:lin
e 752
   at Embeddinator.Driver.CompileCode() in D:\repos\Embeddinator-4000\binder\Compilation.cs:line 54
   at Embeddinator.Driver.Run() in D:\repos\Embeddinator-4000\binder\Driver.cs:line 253
   at Embeddinator.CLI.Main(String[] args) in D:\repos\Embeddinator-4000\binder\CLI.cs:line 220

I think it is not taking android ndk compile location.

I hardcoded the android location in compilation.cs and tried running locally the above script,but the same error results.Can you give a solution to the issue?

**Comment by renjithtkm** [comment]
Ignore my previous comments

Latest result I am getting is given below.

PS D:\repos\Embeddinator-4000\build\lib\Release> .\embeddinator-4000 -gen=java -p=Android -out=d:/foo c:\users\sd1070316
\source\repos\app1\app1\bin\debug\app1.dll -c -vs=2017
Parsing assemblies...
    Parsed 'app1.dll'
Processing assemblies...
Generating binding code...
    Generated: app1.h
    Generated: app1.c
    Generated: Mono.Android.h
    Generated: Mono.Android.c
    Generated: mscorlib.h
    Generated: mscorlib.c
    Generated: Java.Interop.h
    Generated: Java.Interop.c
    Generated: c-support.c
    Generated: c-support.h
    Generated: embeddinator.h
    Generated: glib.c
    Generated: glib.h
    Generated: mono-support.c
    Generated: mono-support.h
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...
        c:/programdata/microsoft/androidndk/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_6
4/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.exe: error: cannot find -lmonosgen
-2.0
c:/programdata/microsoft/androidndk/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/..
/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.exe: error: cannot find -lmono-android.rel
ease
collect2.exe: error: ld returned 1 exit status

Failed to compile generated code.

It can not find lmonosgen -2.0.I checked the files in my system ,there is no file named like this in my system in Mono path.

Can you please clarify on this and give a solution?

**Comment by jonathanpeppers** [comment]
`libmonosgen-2.0.so` is part of Xamarin.Android.

It should be found along with the NuGet of Embeddinator-4000, such as: `Embeddinator-4000.0.3.0\external\Xamarin.Android\lib\xbuild\Xamarin\Android\lib`

There is a version of one per Android-abi.

**Comment by renjithtkm** [comment]
Thanks for your feedback @jonathanpeppers .

Now we are getting the following error while executing the command given below.

PS C:\Embeddinator-4000\build\lib\Release> .\Embeddinator-4000 -gen=java -out=foo -p=Android app1.dll -c -vs=2017
assembly=app1.dll
Parsing assemblies...
    Parsed 'app1.dll'
Processing assemblies...
Generating binding code...
    Generated: app1.h
    Generated: app1.c
    Generated: Mono.Android.h
    Generated: Mono.Android.c
    Generated: mscorlib.h
    Generated: mscorlib.c
    Generated: Java.Interop.h
    Generated: Java.Interop.c
    Generated: c-support.c
    Generated: c-support.h
    Generated: embeddinator.h
    Generated: glib.c
    Generated: glib.h
    Generated: mono-support.c
    Generated: mono-support.h
    Generated: mono_embeddinator.c
    Generated: mono_embeddinator.h
Compiling binding code...
assembly=app1.dll
Parsing assemblies...
    Parsed 'app1.dll'
    Parsed 'app1.dll'
Processing assemblies...
Generating binding code...
    Generated: app1\app1\Resource.java
    Generated: app1\app1\Attribute.java
    Generated: app1\app1\Layout.java
    Generated: app1\app1\String.java
    Generated: app1\Native_app1.java
    Generated: mscorlib\system\IDisposableImpl.java
    Generated: mscorlib\system\IDisposable.java
    Generated: mscorlib\Native_mscorlib.java
    Generating Java stubs...
        C:\Embeddinator-4000\build\lib\Release\foo\GenerateJavaStubs.proj(18,74): error MSB4064: The "AssemblyIdentityMapFile" parameter is not supported by the "ResolveLibraryProjectImports" task. Verify the parameter exists on the task, and it is a settable public instance property.
C:\Embeddinator-4000\build\lib\Release\foo\GenerateJavaStubs.proj(18,5): error MSB4063: The "ResolveLibraryProjectImports" task could not be initialized with its input parameters.

Can you please give your valuable feedback.

The error file GenerateJavaStubs.proj is attached.

[GenerateJavaStubs.zip](https://github.com/mono/Embeddinator-4000/files/1815322/GenerateJavaStubs.zip)

**Comment by jonathanpeppers** [comment]
Ok, this looks like you've built it from source now.

Can you run `build.ps1 -t Download-Xamarin-Android`? it will get the right version of Xamarin.Android that matches the `ResolveLibraryProjectImports` task used.

**Comment by renjithtkm** [comment]
@jonathanpeppers Thank you for your continuous support,

The issues are resolved now and .aar file is created.

**Comment by lkhore** [comment]
Could you reopen agin.
