### ISSUE TITLE
Failure Loading Library on API < 18

### ISSUE THREAD

**Issue by tombly** [mono/Embeddinator-4000#615]
Hello!

If you build an Android library with 0.4.0 and add the `aar` to a native Android app via Android Studio, and run the app on a device with API level less than 18, then the app will crash on launch with an exception like:

```
java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1967]: 180 could not load needed library ‘libmonosgen-2.0.so’ for ‘lib.so’ (load_library[1109]: Library ‘libmonosgen-2.0.so’ not found)
```

This is because in API < 18 libraries have to be loaded in reverse-dependent order as [explained here](https://groups.google.com/forum/#!msg/android-ndk/J3lzK4X--bM/4YaijymZy_AJ).

The fix is to just manually load the `monosgen-2.0` library along with the `monodroid` library in `AndroidImpl.initialize()` at line 26 like so:

```
System.loadLibrary("monodroid");
System.loadLibrary("monosgen-2.0");     // <-- add this line
System.loadLibrary(library);
```

This way the monosgen library is loaded prior to the .NET library and everything works on older OS versions.

-Tom B.

**Comment by jonathanpeppers** [comment]
Hey @tombly! Send a PR, it sounds like you already did the work to figure this out.

We can test your change, and you’ll get your name and face on the commit history.

**Comment by tombly** [comment]
Hi @jonathanpeppers, the PR is up. It should be easy to reproduce the crash and test the fix since you can just use an API 10 emulator.

On a related note - any unexpected exception in the AndroidImpl.initialize() method will result in the app crashing on launch (since the ContentProvider is created early in the launch process). This is a pretty heavy price to pay, especially if the intended audience of the E4K is apps that are mostly native with a little .NET mixed in. Perhaps that method could catch all exceptions to be a little more forgiving. I can see the reasoning either way, just a thought.
