### ISSUE TITLE
Export attribute seems to be ignored embeddinating a Mac dll

### ISSUE THREAD

**Issue by equinox2k** [mono/Embeddinator-4000#626]
Export attribute seems to be ignored embeddinating a Mac dll (Using embeddinator 0.3.0)

e.g. the following 

[Export("setProjectModeString:")]
public void SetProjectModeString(string projectType)
{
}

generates a method called

setProjectModeStringProjectType rather than the expected setProjectModeString

**Comment by chamons** [comment]
So a few things:

- .3 was from master, not the objc branch, so it missed a number of changes we had there.
- It appears by default we ignore all NSObject derived classes when binding, as the static registrar handles them.
- Could you attach a project or such showing your setup.

**Comment by dalexsoto** [comment]
We have not received the requested information. If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button. Thanks!
