### ISSUE TITLE
.aar file created could not be run from Android Studio

### ISSUE THREAD

**Issue by renjithtkm** [mono/Embeddinator-4000#637]
### Steps to Reproduce

1. We created a xamarin android sample app in visual studio 2017 to read blood pressure and built the app and it is working successfully. It is using BLE libraries for reading pressure.
2. We followed the steps below 
•Created a C# Android blank app project
•Install Embeddinator-4000 via NuGet
•Run Embeddinator on the Android library assembly
•Use the generated AAR file in a Java project in Android Studio
In Android Studio, we followed below steps to integrate .aar file,
1. Create a new module in a project and add the .aar file to that module.
2. Add this module to app's build.gradle file.
3. Then import the files from .aar file.
4. After including the generated .aar file in Android Studio and running the app
We are getting errors shown in actual behaviour below.
app6 is the sample application name created using xamarin studio.

### Expected Behavior
Show the screen with connect button 
### Actual Behavior
03-26 12:19:59.364 27529-27529/? A/monodroid-assembly: Could not load assembly 'app6' during startup registration.
03-26 12:19:59.364 27529-27529/? A/monodroid-assembly: This might be due to an invalid debug installation.
03-26 12:19:59.364 27529-27529/? A/monodroid-assembly: A common cause is to 'adb install' the app directly instead of doing from the IDE.
### Environment
android studio - android version 7.0
ndk version - android-ndk-r13b

@jonathanpeppers can any please look in to the issue and give a solution?

**Comment by wcoder** [comment]
Hi
> •Created a C# Android blank app project

Try to use Android class library.

**Comment by jonathanpeppers** [comment]
@renjithtkm try @wcoder's suggestion, you can just change `<AndroidApplication>True</AndroidApplication>` to `False` in your `csproj` (I think).

Another thing you didn't mention is if you disabled compression for `dll` files in Android Studio: https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/java/android#assembly-compression-important

**Comment by renjithtkm** [comment]
@wcoder ,With the uasage of c# class library project ,The issue is resolved.
Thanks for the reply @wcoder  and @jonathanpeppers
