### ISSUE TITLE
Is there a way to tear down embeddinated code in memory after use...

### ISSUE THREAD

**Issue by equinox2k** [mono/Embeddinator-4000#650]
I have a Mac alextension library containing a embeddinated library. At a given point the embeddinated ode is loaded. When the user completes I would like to tear down mono before exiting extension.

At moment since extension stays in memory resources remain. I’m forcing an abort() to kill everything but would be nice to have some kind of dispose once embeddinated library loaded.

**Comment by spouliot** [comment]
Since E4K _just_ automatically generates code to ease embedding mono then you still have (manual) control over things - including [shutting down the runtime](http://www.mono-project.com/docs/advanced/embedding/#shutting-down-the-runtime).

However the same limitations would apply

> Note that for current versions of Mono, the mono runtime can’t be reloaded into the same process, so call mono_jit_cleanup() only if you’re never going to initialize it again.
