### ISSUE TITLE
Getting-started-java-android.html FileNotFound

### ISSUE THREAD

**Issue by vitalim4** [mono/Embeddinator-4000#660]
### Steps to Reproduce

1. I 've created an .aar file in order to import it into android studio.
While trying to add it, Getting-started-java-android.html is getting me file not found.
Where can I find instruction?

**Comment by jonathanpeppers** [comment]
@vitalim4 the docs are now on `docs.microsoft.com`, is this what you are looking for?

https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/java/android

**Comment by vitalim4** [comment]
Yes. Thank you
