### ISSUE TITLE
Can't build the solution

### ISSUE THREAD

**Issue by vitalim4** [mono/Embeddinator-4000#661]
### Steps to Reproduce

1. Clone this repository
2. Initialize/update submodules: git submodule update --recursive --init
3. Open the solution file Embeddinator-4000.sln with Visual Studio or Visual Studio For Mac
4. Build

It must create Embeddinator.exe

I can't build it. Visual Studio gives me a lot of errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	managed-macos-system			
Error		One or more errors occurred.	managed-macos-modern			
Error		The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.	managed-macos-full			
Error		The command "./generate-version.sh" exited with code 9009.	objcgen	C:\Users\Desktop\embeddinator\Embeddinator-4000\objcgen\objcgen.csproj	123	
Error	CS0006	Metadata file 'C:\Users\Desktop\embeddinator\Embeddinator-4000\objcgen\bin\Release\objcgen.exe' could not be found	objcgentest	C:\Users\Desktop\embeddinator\Embeddinator-4000\tests\objcgentest\CSC	1	Active

**Comment by chamons** [comment]
It sounds like you are running into an issue with the bits you have installed?

``` Error The reference assemblies for framework ".NETFramework,Version=v4.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. managed-macos-full```

In any case, issues are not the best way to handle this. I would ask in https://gitter.im/managed-interop/Lobby
