### ISSUE TITLE
Unable to find an installed API level!

### ISSUE THREAD

**Issue by fallenstardust** [mono/Embeddinator-4000#672]
what happened it cannot find an installed API level, i use Android API 25 and already installed it.
but it shows me as below:

1>  未经处理的异常:  System.Exception: Unable to find an installed API level!
1>     在 Embeddinator.XamarinAndroid.<>c.<.cctor>b__32_2()
1>     在 System.Lazy`1.CreateValue()
1>     在 System.Lazy`1.LazyInitValue()
1>     在 System.Lazy`1.get_Value()
1>     在 Embeddinator.Driver.CompileNDK(IEnumerable`1 files)
1>     在 Embeddinator.Driver.CompileNativeCode(IEnumerable`1 files)
1>     在 Embeddinator.Driver.CompileCode()
1>     在 Embeddinator.Driver.Run()
1>     在 Embeddinator.CLI.Main(String[] args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5143,5): error MSB3073: 命令“set E4K_OUTPUT="E:\windbotAndroidplan\libWindbot\output"
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5143,5): error MSB3073: if exist %E4K_OUTPUT% rmdir /S /Q %E4K_OUTPUT%
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5143,5): error MSB3073: "C:\Users\Administrator\.nuget\packages\embeddinator-4000\0.4.0\tools\Embeddinator-4000.exe" "E:\windbotAndroidplan\libWindbot\libWindbot\bin\Release\libWindbot.dll" --gen=Java --platform=Android --outdir=%E4K_OUTPUT% -c -v
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5143,5): error MSB3073: ”已退出，代码为 -532462766。

**Comment by michaelpearson** [comment]
d5fed874566cd8c37e896505c30661507a5c8196 bumps the maximum android SDK version to 26. However, it doesn't seem to have been released to NuGet yet. I was able to solve this problem by installing the Android 24 build tools.

**Comment by fallenstardust** [comment]
yes Android 24 build tools arent released on Nuget.

**Comment by michaelpearson** [comment]
Strange. The only thing I can suggest is to check in Visual Studio that your Android SDK path is set correctly and that the the correct platforms are installed in the path specified.

To check the SDK installation path you can open visual studio and goto Tools->Options->Xamarin->Android Settings->Android SDK Location

To check the correct platform tools are installed, navigate to the SDK installation path (for me it is "C:\Program Files (x86)\Android\android-sdk") and check the folder "platforms\android-24" exists. For me the full path is "C:\Program Files (x86)\Android\android-sdk\platforms\android-24".

When this folder exists it solves the "Unable to find an installed API level!" problem for me.

**Comment by fallenstardust** [comment]
OK，thanks for your kindly suggesting! i built it successfully. now i implemented the aar and try to onCreate it through Android but while i run it on my Android mobile and it cannot onCreate successfully and shows me a log：

Detected problems with app native libraries
(please consult log for detail):
libmonosgen-2.0.so: unauthorized access to "/system/lib/libsqlite.so"

do you know how to fix it?

**Comment by michaelpearson** [comment]
That's good that you got it working.

I'm not sure what the new problem is and whether it is related to Embeddinator. I would suggest closing this issue as the original problem has been solved.
