### ISSUE TITLE
[Android] Runtime Crash - Hello World - Xamarin.Forms/SharedUI

### ISSUE THREAD

**Issue by ahoefling** [mono/Embeddinator-4000#678]
### Steps to Reproduce

(sample project below)

1. Download sample project [https://github.com/jamesmontemagno/embeddinator-hellosharedui](https://github.com/jamesmontemagno/embeddinator-hellosharedui)
2. Update NuGet references to use 0.4.0 (or build the latest master, both have the same outcome for me)
3. Run the build and make sure the embeddinator command executes
    `mono '$(SolutionDir)/packages/Embeddinator-4000.0.4.0/tools/embeddinator-4000.exe' '$(TargetPath}' --gen=Java --platform=Android --outdir='$(SolutionDir}/androidoutput' -c 'bin/Debug/FormsViewGroup.dll'`
    This completes without error and properly generates the `.aar` file
4. Take the `.aar` file and add it to the Android Studio project
5. Make Project
6. Run or Debug Project
7. Execute Embedded Code by clicking the button at the bottom of the screen

### Expected Behavior

* Xamarin.Forms Page is to render correctly as shown at the MSFT Connect 2017 demo using the same code base

### Actual Behavior

android code snippet
```Java
UIHelpers helpers = new UIHelpers();
Fragment frag = helpers.getMyPageFragment(MainActivity.this);
FragmentManager manager = getSupportFragmentManager();
manager.beginTransaction().replace(R.id.fragment, frag, "main").commit();
```

* Line1: the UIHelpers call executes correctly! This is a great sign because that is C# code that is properly embedded
* Line2: The application crashes as it attempts to generate the `Fragment` which is being built by a Xamarin.Forms `ContentPage`
    * the crash complains of ClassNotFoundException for the following Xamarin.Forms classes:
        * `PageRenderer`
        * `VisualElementRenderer`
        * `FormsViewGroup`
    * I have checked the .dex files and those classes are properly included

### Environment
NDK: android-ndk-r15c
Mono: 5.10.1.47
OS: Windows/Mac (same behavior seen on both)
Does AAR Generate: Yes

Version: NuGet 0.4.0 or the latest commit from master `d697cdfca5060c07e95063c30f4864bd0a36b0ca`

### Build Logs

[embeddinator-crash.log](https://github.com/mono/Embeddinator-4000/files/2056730/embeddinator-crash.log)

### Example Project (If Possible)

Android Project with built aar file: [Android Example Project](https://drive.google.com/file/d/1cnt99rijKZDbTRpfgJtrzG_xfYzDeLjV/view?usp=sharing)

Xamarin Project: [https://github.com/jamesmontemagno/embeddinator-hellosharedui](https://github.com/jamesmontemagno/embeddinator-hellosharedui)

### Additional Information

This error appears as if the classes are getting linked out but they do appear in the dex files which confuses me

I have looked through most a lot of the related issues and was able to keep pushing forward until I got stuck with this problem. I am linking related issues, because some of them were closed and left answered as 

* "Use the latest NuGet"
* "Compile master"
* "Don't user windows it works better on Mac"

Related: #504 #604

**Comment by ahoefling** [comment]
I was able to resolve this by including the FormsViewGroup.jar in my Android project. There are some other situations that I ran into but as far as this issue is concerned it is a non-issue. 

I am hoping to put together some documentation on real world example of using Xamarin.Forms with the Embeddinator

**Comment by gonz01d** [comment]
> I was able to resolve this by including the FormsViewGroup.jar in my Android project. There are some other situations that I ran into but as far as this issue is concerned it is a non-issue.
> 
> I am hoping to put together some documentation on real world example of using Xamarin.Forms with the Embeddinator

@ahoefling Did you put together any detail on using Embedded XF in the end?
