### ISSUE TITLE
Issue with Asynchronous Calls 

### ISSUE THREAD

**Issue by andreispark** [mono/Embeddinator-4000#690]
### Steps to Reproduce

1.  I have a C# library which utilizes synchronous and asynchronous calls. When I run the application by itself on C# I can utilize the synchronous and asynchronous functions properly, and the everything works to perfection.
2. I created an Objective-C Coco application that implements the C# library I have created. 
3. When I run the Objective-C application and utilize only the synchronous calls of my C# library, everything works correctly. But I can't seem to get it to work with asynchronous functions. It appears to be an issue with the communication in between the Objective-C and C# library when I utilize asynchronous calls.

### Expected Behavior
If a sample C# application that implements the C# library can fully utilize the synchronous and asynchronous calls, I expect to be able to do the same from the Objective-C application that implements the same library. I want to be able to use the asynchronous calls for the obvious benefits it provides.

### Actual Behavior

Right now I can only get my Objective-C application to function appropriately through the Embeddinator-4000 with the C# library if I utilize synchronous functions, which is not what I want.

### Environment

Embeddinator-4000 0.4.0
Mono 5.10.1.57
Xamarin.Mac 4.2.1.28
macOS 10.13.5

### Sample Code
Can't provide sample code

**Comment by VincentDondain** [comment]
We have not received the requested information.

If you are still experiencing this issue please provide all the requested information then click the Reopen Issue button.

Thanks!
