### ISSUE TITLE
[Android] ArgumentNullException in System.IO.Path.Combine

### ISSUE THREAD

**Issue by pacomaral** [mono/Embeddinator-4000#693]
### Steps to Reproduce

1.  Build a Xamarin Android Library
2. Run embeddinator-4000 to get the .aar library.

### Expected Behavior
Generate the library in the output directory

### Actual Behavior
I'm getting the following error:

```
  System.ArgumentNullException: The value cannot be null.
Nombre del parámetro: path1
   in System.IO.Path.Combine(String path1, String path2)
   in Embeddinator.Driver.CompileNDK(IEnumerable`1 files)
   in Embeddinator.Driver.CompileNativeCode(IEnumerable`1 files)
   in Embeddinator.Driver.CompileCode()
   in Embeddinator.Driver.Run()
   in Embeddinator.CLI.Main(String[] args)
```

### Environment
VS 15.8.1
Xamarin.Android 9.0
Windows 10

### Comments
After researching for a while I read that I had to install the NDK, but after installing i still getting the same error.

I've run the command with the '-verbose' parameter and I found this errors, it looks like the sdk/ndk weren't found at all.

```
Compiling binding code...
      Key HKCU\SOFTWARE\Novell\Mono for Android\AndroidSdkDirectory not found.
      Key HKCU\SOFTWARE\Novell\Mono for Android\AndroidNdkDirectory not found.
      Key HKCU\SOFTWARE\Novell\Mono for Android\JavaSdkDirectory not found.
    Looking for Android SDK...
      Key HKCU\SOFTWARE\Novell\Mono for Android\AndroidSdkDirectory not found.
      Key HKLM\SOFTWARE\Novell\Mono for Android\AndroidSdkDirectory not found.
      Key HKCU\SOFTWARE\Xamarin\MonoAndroid\PrivateAndroidSdkPath not found.
      Key HKCU\SOFTWARE\Android SDK Tools\Path not found.
      Key HKLM\SOFTWARE\Android SDK Tools\Path not found.
    Looking for Android NDK...
      Key HKCU\SOFTWARE\Novell\Mono for Android\AndroidNdkDirectory not found.
      Key HKLM\SOFTWARE\Novell\Mono for Android\AndroidNdkDirectory not found.
      Key HKCU\SOFTWARE\Novell\Mono for Android\JavaSdkDirectory not found.
      Key HKLM\SOFTWARE\Novell\Mono for Android\JavaSdkDirectory not found.
    Looking for Java 6 SDK...
      Key HKLM\SOFTWARE\JavaSoft\Java Development Kit\CurrentVersion found.
      Key HKLM\SOFTWARE\JavaSoft\Java Development Kit\1.8\JavaHome found:
    Path contains jarsigner.exe in \bin (C:\Program Files (x86)\Java\jdk1.8.0_181).
```

My android sdk directory is in C:\Program Files (x86)\Android\android-sdk (Visual Studio default), and I have put the ndk directory in the Visual Studio settings.

I'm not sure if I am doing something wrong but since SDK isn't found even when being in the Visual Studio default directory it makes me think that could be a problem of the nuget.

**Comment by mandel-macaque** [comment]
@pacomaral thanks for the issue report, I will add the correct tags for the right eng to take a look.

**Comment by pacomaral** [comment]
I have solved this issue. I was getting the NDK from the SDK manager and for some reason it wasn't found correctly.

I solved by downloading it from [here](https://developer.android.com/ndk/downloads/revision_history). And it has to be the version 15c, the last one did not work for me.

**Comment by rolfbjarne** [comment]
This looks like a duplicate of #663.

**Comment by BadMiscuit** [comment]
I've downloaded the Android NDK 15c and changed the path in Visual Studio > Xamarin settings but it doesn't change anything
