### ISSUE TITLE
error MM0073 when generating a Xamarin.Mac class library

### ISSUE THREAD

**Issue by rocktyt** [mono/Embeddinator-4000#732]
### Steps to Reproduce

1. following [Getting started with macOS](https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/objective-c/macos), create a new Xamarin.Mac Class Library project.
2. import Embeddinator-4000 nuget package
3. install mono (5.18.1)
4. build the class library
5. call objcgen to generate framework

### Expected Behavior
framework is successfully generated.
### Actual Behavior
getting

> error MM0073: Xamarin.Mac 5.10.0 does not support a deployment target of 10.7 for macOS (the minimum is 10.9). Please select a newer deployment target in your project's Info.plist.

### Environment

/Library/Frameworks/Xamarin.Embeddinator-4000.framework/ no exists.
```
moyueyundeiMac:~ moyueyun$ /Users/moyueyun/Projects/hello-from-csharp/packages/Embeddinator-4000.0.4.0/tools/objcgen -version
Symbol file /Users/moyueyun/Projects/hello-from-csharp/packages/Embeddinator-4000.0.4.0/tools/IKVM.Reflection.pdb doesn't match image /Users/moyueyun/Projects/hello-from-csharp/packages/Embeddinator-4000.0.4.0/tools/IKVM.Reflection.dll
Embeddinator-4000 v0.1 (0.4: 7664197)
```

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.1.5 (build 9)
Installation UUID: c50dda4c-284c-461d-8d43-39d02cf8782e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Professional)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Professional)
Commit: HEAD/9f6426ab2
Android SDK: /Users/moyueyun/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 27.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/moyueyun/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 12.8.0.0 (Visual Studio Professional)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Build Information ===

Release ID: 801050009
Git revision: bd0ab28ba941b19b39322247db020dcd0fb305d0
Build date: 2019-07-03 17:15:21+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64


```

### Build Logs

> moyueyundeiMac:~ moyueyun$ /Users/moyueyun/Projects/hello-from-csharp/packages/Embeddinator-4000.0.4.0/tools/objcgen /Users/moyueyun/Projects/hello-from-csharp/hello-from-csharp/bin/Debug/hello-from-csharp.dll --target=framework --platform=macOS-modern --abi=x86_64 --outdir=output -c --debug
Symbol file /Users/moyueyun/Projects/hello-from-csharp/packages/Embeddinator-4000.0.4.0/tools/IKVM.Reflection.pdb doesn't match image /Users/moyueyun/Projects/hello-from-csharp/packages/Embeddinator-4000.0.4.0/tools/IKVM.Reflection.dll
Creating output directory `/Users/moyueyun/output`
Parsing assemblies...
	Parsed '/Users/moyueyun/Projects/hello-from-csharp/hello-from-csharp/bin/Debug/hello-from-csharp.dll'
Processing assemblies...
	0 types found
Generating binding code...
	Generated: output/bindings.h
	Generated: output/bindings-private.h
	Generated: output/bindings.m
	Generated: output/bindings.xml
	Generated: output/embeddinator.h
	Generated: output/glib.h
	Generated: output/mono_embeddinator.h
	Generated: output/mono-support.h
	Generated: output/objc-support.h
	Generated: output/glib.c
	Generated: output/mono_embeddinator.c
	Generated: output/objc-support.m
	Generated: output/Make.config
Compiling binding code...
Found Mono 5.18.1.28 (between 5.4.1.7 and 5.4.1.7)
Found Xamarin.Mac 5.10.0.157 (between 4.0.0.215 and 4.0.0.215)
	xcode-select -p
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode10.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.7 -I/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/include -DXAMARIN_MAC -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/x86_64/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode10.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.7 -I/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/include -DXAMARIN_MAC -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/x86_64/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode10.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.7 -I/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/include -DXAMARIN_MAC -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/x86_64/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode10.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=10.7 -I/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/include -DXAMARIN_MAC -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/x86_64/bindings.o 
	xcrun ar cru output/x86_64/hello-from-csharp.a output/x86_64/glib.o output/x86_64/mono_embeddinator.o output/x86_64/objc-support.o output/x86_64/bindings.o 
	xcrun --show-sdk-version --sdk macosx
	/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/bin/mmp --output=/Users/moyueyun/output/MacOSX/hello-from-csharp --arch=x86_64 --sdkroot /Applications/Xcode10.1.app --minos 10.7 --embeddinator /Users/moyueyun/Projects/hello-from-csharp/hello-from-csharp/bin/Debug/hello-from-csharp.dll -a:/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/Xamarin.Mac/Xamarin.Mac.dll --sdk 10.14 --linksdkonly --xml=output/bindings.xml --registrar:static --cache /Users/moyueyun/output/MacOSX/build-cache --debug -p --target-framework Xamarin.Mac,Version=v2.0,Profile=Mobile "--link_flags=-force_load /Users/moyueyun/output/MacOSX/hello-from-csharp.a" 
warning MM0079: The recommended Xcode version for Xamarin.Mac 5.10.0 is Xcode 10.2 or later. The current Xcode version (found in /Applications/Xcode10.1.app) is 10.1.
error MM0073: Xamarin.Mac 5.10.0 does not support a deployment target of 10.7 for macOS (the minimum is 10.9). Please select a newer deployment target in your project's Info.plist.

Done

### Example Project (If Possible)

just followed [Getting started with macOS](https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/objective-c/macos), a simple library with only 1 class. 

### Comment
error tells me to select target in my project's Info.plist, but a class library doesn't have an Info.plist. I also tried to add one, but no effects.
what's wrong?

**Comment by chamons** [comment]
``` error MM0073: Xamarin.Mac 5.10.0 does not support a deployment target of 10.7 for macOS (the minimum is 10.9). Please select a newer deployment target in your project's Info.plist.```

Can you try rebuilding with

https://github.com/mono/Embeddinator-4000/blob/master/objcgen/embedder.cs#L356

set to 10.9?

**Comment by rocktyt** [comment]
> ` error MM0073: Xamarin.Mac 5.10.0 does not support a deployment target of 10.7 for macOS (the minimum is 10.9). Please select a newer deployment target in your project's Info.plist.`
> 
> Can you try rebuilding with
> 
> https://github.com/mono/Embeddinator-4000/blob/master/objcgen/embedder.cs#L356
> 
> set to 10.9?
I tried this and now objcgen converts my dll to framework without any errors. Thank you!

**Comment by rocktyt** [comment]
@chamons I tried to create a pull request. Is this OK? https://github.com/mono/Embeddinator-4000/pull/733

**Comment by chamons** [comment]
Perfect ❤️

**Comment by chamons** [comment]
Do you need an official nuget build or is a local one good enough?

**Comment by rocktyt** [comment]
@chamons 
It's better if an offcial nuget package is provided.

**Comment by chamons** [comment]
I'll try to get you something later this week.

**Comment by chamons** [comment]
Turns out our build went stale, so I had to fix this first:

https://github.com/mono/Embeddinator-4000/pull/735

I'll link a package here when fixed.

**Comment by chamons** [comment]
@rocktyt - Our on bot builds are giving me grief but https://dl.xamarin.com/uploads/nhj1coiq5gg/Embeddinator-4000.0.5.0.nupkg
