### ISSUE TITLE
Support for iOS resources in class library

### ISSUE THREAD

**Issue by krishnaxamarin** [mono/Embeddinator-4000#736]
Hi,  I am trying to convert a xamarin based project to native and our project structure have pcl, native ios and android class libraries. These class libraries contain resources such as images, xib. 

I was able to convert the ios part to native and generate a framework. But the generated framework doesnt contain any resources which are part of the class library. 

Is there a way we can add these resources to framework while converting the ios project to native while using the embeddinator tool ?.

**Comment by rolfbjarne** [comment]
Right now the embeddinator does not support adding resources to a generated framework.

But you can easily copy files yourself into the framework if you wish.
