### ISSUE TITLE
No corresponding member object or method can be called after compilation

### ISSUE THREAD

**Issue by ezraShenglei** [mono/Embeddinator-4000#753]
### Steps to Reproduce

1.My code
```
public class MyUIView : UITextView
{
    public string testValue;
    public MyUIView()
    {
        Text = "Hello from C# 15:05";
    }
    public void test() {
        Text = "test run";
    }
    public string getTestValue(){
        return testValue;
    }
}
```

2.objcgen /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/bin/Debug/hello_from_csharp.dll --target=framework --platform=iOS --outdir=output -c --debug
### Expected Behavior
Can use MyUIView member objects and methods in ViewController.m file in Xcode
### Actual Behavior
TestValue and test functions not found
### Environment
OSX 10.14.6
embeddinator-4000 0.40
Visual Studio for Mac 8.4 build 2653

```
```

**Comment by chamons** [comment]
Can you please post the full build log, preferably with the project zipped up as well.

**Comment by ezraShenglei** [comment]
> Can you please post the full build log, preferably with the project zipped up as well.

Symbol file /Users/wushenglei/.nuget/packages/embeddinator-4000/0.4.0/tools/IKVM.Reflection.pdb doesn't match image /Users/wushenglei/.nuget/packages/embeddinator-4000/0.4.0/tools/IKVM.Reflection.dll
Creating output directory `/Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/output`
Parsing assemblies...
	Parsed '/Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/bin/Debug/hello_from_csharp.dll'
Processing assemblies...
	1 types found
Generating binding code...
	Generated: output/bindings.h
	Generated: output/bindings-private.h
	Generated: output/bindings.m
	Generated: output/bindings.xml
	Generated: output/embeddinator.h
	Generated: output/glib.h
	Generated: output/mono_embeddinator.h
	Generated: output/mono-support.h
	Generated: output/objc-support.h
	Generated: output/glib.c
	Generated: output/mono_embeddinator.c
	Generated: output/objc-support.m
	Generated: output/Make.config
Compiling binding code...
Found Mono 6.6.0.155 (between 5.4.1.7 and 5.4.1.7)
Found Xamarin.iOS 13.8.3.0 (between 11.6.1.3 and 11.6.1.3)
	xcode-select -p
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/armv7/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/armv7/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/armv7/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/armv7/bindings.o 
	xcrun ar cru output/armv7/hello_from_csharp.a output/armv7/glib.o output/armv7/mono_embeddinator.o output/armv7/objc-support.o output/armv7/bindings.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/armv7s/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/armv7s/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/armv7s/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch armv7s -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/armv7s/bindings.o 
	xcrun ar cru output/armv7s/hello_from_csharp.a output/armv7s/glib.o output/armv7s/mono_embeddinator.o output/armv7s/objc-support.o output/armv7s/bindings.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/arm64/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/arm64/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/arm64/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -miphoneos-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphoneos.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/arm64/bindings.o 
	xcrun ar cru output/arm64/hello_from_csharp.a output/arm64/glib.o output/arm64/mono_embeddinator.o output/arm64/objc-support.o output/arm64/bindings.o 
	xcrun lipo output/armv7/hello_from_csharp.a output/armv7s/hello_from_csharp.a output/arm64/hello_from_csharp.a -create -output output/iPhoneOS/hello_from_csharp.a
	xcrun --show-sdk-version --sdk iphoneos
	/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch --dev /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/output/iPhoneOS/hello_from_csharp --abi=armv7,armv7s,arm64 --sdkroot /Applications/Xcode.app --targetver 8.0 --dsym:false --msym:false --embeddinator /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/bin/Debug/hello_from_csharp.dll -r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll --sdk 13.2 --linksdkonly --xml=output/bindings.xml --registrar:static --cache /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/output/iPhoneOS/build-cache --debug --assembly-build-target=@all=framework=hello_from_csharp.framework --target-framework Xamarin.iOS,v1.0 "--gcc_flags=-force_load /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/output/iPhoneOS/hello_from_csharp.a" 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/i386/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/i386/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/i386/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/i386/bindings.o 
	xcrun ar cru output/i386/hello_from_csharp.a output/i386/glib.o output/i386/mono_embeddinator.o output/i386/objc-support.o output/i386/bindings.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/glib.c -o output/x86_64/glib.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/mono_embeddinator.c -o output/x86_64/mono_embeddinator.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/objc-support.m -o output/x86_64/objc-support.o 
	xcrun clang -g -O0 -fobjc-arc -ObjC -Wall -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -mios-simulator-version-min=8.0 -I/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/SDKs/MonoTouch.iphonesimulator.sdk/usr/include -DXAMARIN_IOS -DMONO_EMBEDDINATOR_DLL_EXPORT  -c output/bindings.m -o output/x86_64/bindings.o 
	xcrun ar cru output/x86_64/hello_from_csharp.a output/x86_64/glib.o output/x86_64/mono_embeddinator.o output/x86_64/objc-support.o output/x86_64/bindings.o 
	xcrun lipo output/armv7/hello_from_csharp.a output/armv7s/hello_from_csharp.a output/arm64/hello_from_csharp.a output/i386/hello_from_csharp.a output/x86_64/hello_from_csharp.a -create -output output/iPhoneSimulator/hello_from_csharp.a
	xcrun --show-sdk-version --sdk iphonesimulator
	/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch --sim /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/output/iPhoneSimulator/hello_from_csharp --abi=i386,x86_64 --sdkroot /Applications/Xcode.app --targetver 8.0 --dsym:false --msym:false --embeddinator /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/bin/Debug/hello_from_csharp.dll -r:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Xamarin.iOS.dll --sdk 13.2 --linksdkonly --xml=output/bindings.xml --registrar:static --cache /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/output/iPhoneSimulator/build-cache --debug --assembly-build-target=@all=framework=hello_from_csharp.framework --target-framework Xamarin.iOS,v1.0 "--gcc_flags=-force_load /Users/wushenglei/Projects/hello-from-csharp/hello-from-csharp/output/iPhoneSimulator/hello_from_csharp.a" 
	xcrun lipo output/armv7/hello_from_csharp.a output/armv7s/hello_from_csharp.a output/arm64/hello_from_csharp.a output/i386/hello_from_csharp.a output/x86_64/hello_from_csharp.a -create -output output/hello_from_csharp.a
	xcrun lipo output/iPhoneOS/hello_from_csharp.framework/hello_from_csharp output/iPhoneSimulator/hello_from_csharp.framework/hello_from_csharp -create -output output/hello_from_csharp.framework/hello_from_csharp
Successfully created framework: output/hello_from_csharp.framework
Done

[hello_from_csharp.zip](https://github.com/mono/Embeddinator-4000/files/4062660/hello_from_csharp.zip)

**Comment by ezraShenglei** [comment]
> Can you please post the full build log, preferably with the project zipped up as well.
another example:
My code:
namespace hello_new_csharp
{
     public class Class1
     {
         public String text;
         public Class1 ()
         {
             text = "Class1 C #";
         }

     }
}
objcgen /Users/wushenglei/Projects/hello-new-csharp/hello-new-csharp/bin/Debug/hello_new_csharp.dll --target = framework --platform = iOS --outdir = output -c --debug

Error log after using this command

error MT2002: Failed to resolve assembly: 'System.Drawing.Common, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51'
[hello-new-csharp.zip](https://github.com/mono/Embeddinator-4000/files/4075224/hello-new-csharp.zip)

**Comment by chamons** [comment]
The embeddinator tool assumes that all requires assemblies are next to the library in question. 

If you do something like `cp /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/System.Drawing.dll  .` next to the library it binds.
