### ISSUE TITLE
Can't find Embeddinator-4000 objcgen

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#754]
### Steps to Reproduce

1. Install Embeddinator-400 into Visual Studio 2019 on Windows
2. Create Xamarin.ios class library project
3. cd /Users/me/hello-class-5
objcgen /Users/hello-class-5/bin/Debug/ hello-class-5.dll --target=framework --platform=iOS --outdir=output -c --debug

### Expected Behavior
It should convert my hello-class into a library usable by Objective-C on IOS.

### Actual Behavior
-bash: objcgen: command not found

### Environment
visual studio 2019 Pro on Windows 10 for ios target.

```
```

**Comment by chamons** [comment]
`objcgen` needs to point to a relative or absolute path to the tool's nuget folder. It is very likely not in your path.

**Comment by dbell-movano** [comment]
I'm confused.  Isn't "objcgen" an app?  Specifically, objcgen.exe ?

**Comment by chamons** [comment]
objcgen is just a bash script that invokes objcgen.exe with mono:

https://github.com/mono/Embeddinator-4000/blob/master/objcgen/script/objcgen

You will have to adapt to invoking the exe directly on Windows.
