### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by ILAgent** [mono/Embeddinator-4000#758]
It looks like a dead project due to long time without realises. Is there any actual way to embed xamarin parts into native applications?

**Comment by chamons** [comment]
There currently is not active development by members of the Xamarin team, but we are triaging incoming issues and assisting where it makes sense. 

As a community project, the hope is that people will be able to build upon it to bundle C# libraries in native libraries. However, to do so today does involve getting your hands dirty by creating simplified "facade" interfaces in places.
