### ISSUE TITLE
How to use objcgen on Windows 10 to do .Net embedding

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#759]
### Steps to Reproduce

1. I created Xamarin ios class lib project “embedinnator2 class lib “ on Windows 10, Visual Studio 2019 latest.
I installed Embeddinator-4000 NuGet.
I built project. 
Used PowerShell run as admin to enter project’s bin\debug\ and then executed...
C:\Users\Doug\.nuget\packages\embeddinator-4000\0.4.0\tools\Embeddinator-4000.exe --gen=Obj-C --platform=ios --compile --debug --target=static  --static --verbose+ embedinnator2 class lib.dll

But then got this:
“Please use the objcgen tool for Objective-C generation.”

2. 
3. 

### Expected Behavior
To get .Net embedding to convert a Xamarin.IOS class lib project so that it can be called from a Xcode Objective-C project

### Actual Behavior
“Please use the objcgen tool for Objective-C generation.”

### Environment
Visual Studio 2019 Pro on Windows 10

```
```

**Comment by chamons** [comment]
As noted in the duplicate issue you filed:

> The Embeddinator-4000 tool requires invocation the native tool chain to build an Objective-C framework, and does not work remotely from Windows.

See https://github.com/mono/Embeddinator-4000/issues/756 for more details.
