### ISSUE TITLE
EM0000: Unexpected error -EM0000: Unexpected error -

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#760]
### Steps to Reproduce

1. Create hello world Xamarin.ios class library project using Visual Studio 2019 v16.4.5 on windows 10
2. Build it for release
3. Embeddinate by entering directory <proj>\bin\release\  and executing:
 C:\Users\Doug\.nuget\packages\embeddinator-4000\0.4.0\tools\objcgen.exe --gen=Obj-C --platform=ios --compile --debug  --verbose `embedinnator2 class lib.dll'

### Actual Behavior
 C:\Users\Doug\.nuget\packages\embeddinator-4000\0.4.0\tools\objcgen.exe --gen=Obj-C --platform=ios --compile --debug  --verbose `embedinnator2 class lib.dll'

### Environment
Windows 10 Visual Studio 2019 connected to MacBook by wifi

```
```

### Build Logs

 C:\Users\Doug\.nuget\packages\embeddinator-4000\0.4.0\tools\objcgen.exe --gen=Obj-C --platform=ios --compile --debug  --verbose `embedinnator2 class lib.dll'

**Comment by chamons** [comment]
The Embeddinator-4000 tool requires invocation the native tool chain to build an Objective-C framework, and does not work remotely from Windows. 

See https://github.com/mono/Embeddinator-4000/issues/756
