### ISSUE TITLE
make on MacOS 10.14.6 and gets "No shellcheck tool found"

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#765]
### Steps to Reproduce

1.  clone github Embeddinator-4000
2. change to local repo directory
3. make

### Expected Behavior

should build objcgen

### Actual Behavior
Only output was:  "No shellcheck tool found"

but did it build objcgen?

### Environment

```
MacOS 10.14.6
My git tag -l is:  v0.2.0.79
```

### Build Logs

"No shellcheck tool found"

**Comment by chamons** [comment]
Yes. You can run the tool with:

_build/objcgen

It copies everything into the _build directory

or build a nuget with `make nuget`
It is just warning we skilled the shell script validation step, since you don't have the required tool installed.
