### ISSUE TITLE
"Simply run make in Embeddinator-4000/objcgen." build fails on MacOS

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#766]
### Steps to Reproduce

1. I cloned this: Github Embeddinator-4000
2. I went into the clone to: Embeddinator-4000/objcgen
3. make failed with build errors (below)

### Expected Behavior
Generation of objcgen so I can embed my Xamarin.ios project so it can be used by my Xcode project.

### Actual Behavior
make fails.  (see build errors below)

### Environment

macos  10.14.6

```
```

### Build Logs

Building solution objcgen (Debug|x86)
Build started 3/17/2020 9:42:08 AM.
__________________________________________________
Project "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/objcgen/objcgen.csproj" (Build target(s)):

Target BeforeBuild:
  Skipping target "BeforeBuild" because all output files are up-to-date with respect to the input files.
Target _GetProjectReferenceTargetFrameworkProperties:
    __________________________________________________
    Project "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/objcgen/objcgen.csproj" is building "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/projects/IKVM.Reflection.csproj" (GetTargetFrameworks target(s)):

Target ResolveProjectReferences:
    __________________________________________________
    Project "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/objcgen/objcgen.csproj" is building "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/projects/IKVM.Reflection.csproj" (GetTargetPath target(s)):

    __________________________________________________
    Project "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/objcgen/objcgen.csproj" is building "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/projects/IKVM.Reflection.csproj" (GetNativeManifest target(s)):

Target ResolveAssemblyReferences:
    Primary reference "IKVM.Reflection".
        Could not find dependent files. Expected file "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/lib/Debug/IKVM.Reflection.dll" does not exist.
        Could not find dependent files. Expected file "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/lib/Debug/IKVM.Reflection.dll" does not exist.
        Resolved file path is "/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/lib/Debug/IKVM.Reflection.dll".
        Reference found at search path location "".
        The ImageRuntimeVersion for this reference is "".
Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target CoreCompile:
    /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Roslyn/csc.exe /noconfig /nowarn:1701,1702,2008 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /define:DEBUG;NO_AUTHENTICODE;NO_SYMBOL_WRITER;NET_4_0;STATIC /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/lib/Debug/IKVM.Reflection.dll /reference:/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/packages/Mono.Options.4.4.0.0/lib/net4-client/Mono.Options.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/4.6-api/mscorlib.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/4.6-api/System.Core.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/4.6-api/System.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/4.6-api/System.Xml.dll /debug+ /debug:portable /optimize- /out:obj/x86/Debug/objcgen.exe /subsystemversion:6.00 /resource:../support/embeddinator.h,embeddinator.h /resource:../support/glib.h,glib.h /resource:../support/mono_embeddinator.h,mono_embeddinator.h /resource:../support/mono-support.h,mono-support.h /resource:../support/objc-support.h,objc-support.h /resource:../support/glib.c,glib.c /resource:../support/mono_embeddinator.c,mono_embeddinator.c /resource:../support/objc-support.m,objc-support.m /resource:Make.config,Make.config /target:exe /utf8output /langversion:7.3 generator.cs objcgenerator.cs driver.cs error.cs ErrorHelper.cs Version.generated.cs objcgenerator-helpers.cs objcprocessor.cs extensions.cs methodhelper.cs objcgenerator-subscripts.cs processedtypes.cs objcgenerator-postprocessor.cs comparablehelper.cs EqualsHelper.cs HashHelper.cs sourcewriter.cs classhelper.cs OperatorOverloads.cs protocolhelper.cs NameGenerator.cs processor.cs system-check.cs embedder.cs utils.cs CachedValue.cs TypeMapper.cs Logger.cs "/var/folders/gd/vwl8dm5n7fs8xkdkymwxxpm00000gp/T/.NETFramework,Version=v4.6.AssemblyAttributes.cs"
    CSC : error CS0006: Metadata file '/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/lib/Debug/IKVM.Reflection.dll' could not be found
Done building target "CoreCompile" in project "objcgen.csproj" -- FAILED.

Done building project "objcgen.csproj" -- FAILED.

Build FAILED.

CSC : error CS0006: Metadata file '/PRIMARY/WORK/Embeddinator-4000_attempt_2/Embeddinator-4000/build/lib/Debug/IKVM.Reflection.dll' could not be found
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.42

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings

**Comment by chamons** [comment]
You've now opened 3 issues on this, and none of them are bugs. Closing for https://github.com/mono/Embeddinator-4000/issues/768
