### ISSUE TITLE
 Xcode > project > TARGETS > is missing "Embedded Binaries" section in my HELLO WORLD example

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#769]
### Steps to Reproduce

1. Follow the MICROSOFT > DOCS > Getting started with iOS > hello-from-csharp C# example
2. In the Embedded Binary section, add hello-from-csharp.framework.

Bug I can't because "Embedded Binary section" is not there.

3. 

### Environment

MAC OS 10.14.6
XCODE 11.3.1
objcgen as of 3-24-2020

```
```

**Comment by chamons** [comment]
Please provide a link to the documentation in question, are you talking about https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/objective-c/ios?

**Comment by dbell-movano** [comment]
I learned on StackOverflow that "Embedded Binaries" section of project General tab is obsolete and replaced by "Frameworks, Libs, and Embedded Content, and hello_from_csharp.framework was added to this automatically.
