### ISSUE TITLE
.net Embedding hello-world-csharp example crashes on Xcode simulator

### ISSUE THREAD

**Issue by dbell-movano** [mono/Embeddinator-4000#770]
### Steps to Reproduce

1. Follow the Microsoft doc hello-world example in .Net Embedding
2. Build it
3. Run it.  it crashes

Here is my screen shot of the Xcode debugger at the crash...

![XCODE HELLO WORLD](https://user-images.githubusercontent.com/60415855/77666978-e347a400-6f3e-11ea-9261-4a725513375c.jpg)

### Environment

```
```

**Comment by chamons** [comment]
@dbell-movano - You have opened **10 different github issues in the last month**. Almost all of them have been "support" and not bug reports or feature requests. Almost none of them have had the issue template filled out.

I would confirm you have all of the settings listed in https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/objective-c/ios correct, in particular bitcode and copy if needed for the framework in question.

Github issues are not a channel for support in using this tool. Full stop.

There are a number of community channels such as https://gitter.im/managed-interop and https://gitter.im/xamarin/xamarin-macios that also could be useful.
