### ISSUE TITLE
warning EM1011: Type `System.Object` is not generated because it lacks a native counterpart.

### ISSUE THREAD

**Issue by douglaskbell** [mono/Embeddinator-4000#772]
### Steps to Reproduce

1. On Macbook Pro I built my Xamarin.ios .net standard class lib project
2. Fully installed and built github emb4k objcgen
3. Used objcgen to generate Obj-C from .NET standard class lib with this command line:
/PRIMARY/WORK/attempt4_3-24-20b/Embeddinator-4000/objcgen/_build/objcgen     "/PRIMARY/WORK/MOBILE_SYS_HUB/SYS HUB VB standard/bin/Debug/netstandard2.0/SYS_HUB_VB_standard.dll" --target=framework --platform=iOS --outdir=output -c --debug

### Expected Behavior
Should have generated Obj-c 
### Actual Behavior

/PRIMARY/WORK/attempt4_3-24-20b/Embeddinator-4000/objcgen/_build/objcgen     "/PRIMARY/WORK/MOBILE_SYS_HUB/SYS HUB VB standard/bin/Debug/netstandard2.0/SYS_HUB_VB_standard.dll" --target=framework --platform=iOS --outdir=output -c --debug
Parsing assemblies...
	Parsed '/PRIMARY/WORK/MOBILE_SYS_HUB/SYS HUB VB standard/bin/Debug/netstandard2.0/SYS_HUB_VB_standard.dll'
Processing assemblies...
	12 types found

warning EM1011: Type `System.Object` is not generated because it lacks a native counterpart.

### Environment

```
```

**Comment by chamons** [comment]
I don't believe this is a bug, you are being warned that your exposed C# interface has some NSObject types, and there isn't a good mapping to ObjC for those. How would you use those in ObjC?

As you did not give sufficient information, such as a API example, I can't comment further, but this warning is a warning for a reason. Consider tweaking your C# interface to be more usable in ObjC.

If you believe this is a bug, please reopen with more details.

**Comment by douglaskbell** [comment]
Not a bug.  Was usage of VB keyword "object".  Solved by removal of "object" usage.
Thanks.
