### ISSUE TITLE
[objc] camelCase instead of PascalCase for methods

### ISSUE THREAD

**Issue by VincentDondain** [mono/Embeddinator-4000#89]
Currently when generating Objective-C methods, e4k creates them using PascalCase (convention in C#) instead of **camelCase** (convention in ObjC).

[Cocoa coding guidelines](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF)

C#

```
public static void PrintSomething ()
{
	Console.WriteLine ("Hello!!!");
}

public void PrintSomethingNonStatic ()
{
	Console.WriteLine ("Hello (not static)!!!");
}
```

Objective C
```
+ (void) PrintSomething;
- (void) PrintSomethingNonStatic;
```

Those methods names should be using camel case (start with a lowercase).

**Comment by spouliot** [comment]
@VincentDondain were you using the `objc` branch ?

```
+ (instancetype) create:(int)id
```

**Comment by VincentDondain** [comment]
I was but I wasn't using `objcgen.exe`.

This is indeed already fixed on the `objc` branch (if you're using it properly).
